// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         limit: 10,
 *         offset: 0
 *     }
 */
export interface ListClustersRequest {
    /** Number of items per page */
    limit?: number | null;
    /** Number of items to skip */
    offset?: number | null;
    /** Comma-separated list of attributes to return (e.g. id,name). When provided, only the specified fields are fetched. `id` is always included. */
    attributes?: string[] | null;
}
