/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../../../../index";

/**
 * @example
 *     {}
 */
export interface PromptVersionsListRequest {
    fqn?: string;
    prompt_id?: string;
    ml_repo_id?: string;
    name?: string;
    version?: TrueFoundry.PromptVersionsListRequestVersion;
    offset?: number;
    limit?: number;
}
