// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import * as serializers from "../../../../index.js";
import { ResourceType } from "../../../../types/ResourceType.js";

export const UpdateUserRolesRequest: core.serialization.Schema<serializers.UpdateUserRolesRequest.Raw, TrueFoundry.UpdateUserRolesRequest> = core.serialization.object({
        "email": core.serialization.string(),
        "roles": core.serialization.list(core.serialization.string()),
        "resourceType": ResourceType.optional()
    });

export declare namespace UpdateUserRolesRequest {
    export interface Raw {
        email: string;
        roles: string[];
        resourceType?: ResourceType.Raw | null;
    }
}
