// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../../../index.js";

/**
 * @example
 *     {
 *         limit: 10,
 *         offset: 0
 *     }
 */
export interface ListRunsJobsRequest {
    /** Number of items per page */
    limit?: number | null;
    /** Number of items to skip */
    offset?: number | null;
    /** Prefix used to search for job runs by name or identifier */
    searchPrefix?: string | null;
    /** Attribute to sort by */
    sortBy?: TrueFoundry.JobRunsSortBy;
    /** Sorting order */
    order?: TrueFoundry.SortDirection;
    /** Array of subject slugs */
    triggeredBy?: string[] | null;
    /** Status of the job run */
    status?: TrueFoundry.JobRunStatus | TrueFoundry.JobRunStatus[];
    /** Version number of the deployment */
    versionNumbers?: number[] | null;
}
