/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../../../../index";

/**
 * @example
 *     {
 *         manifest: {
 *             metadata: {
 *                 "key": "value"
 *             },
 *             type: "artifact-version"
 *         }
 *     }
 */
export interface ApplyArtifactRequest {
    manifest: TrueFoundry.ArtifactManifest;
}
