// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         limit: 10,
 *         offset: 0,
 *         nameSearchQuery: "ci-token"
 *     }
 */
export interface ListPersonalAccessTokensRequest {
    /** Number of items per page */
    limit?: number | null;
    /** Number of items to skip */
    offset?: number | null;
    /** Return personal access tokens whose name contains this substring. */
    nameSearchQuery?: string | null;
}
