/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../../../../index";

/**
 * @example
 *     {
 *         manifest: {
 *             type: "team",
 *             name: "name",
 *             members: ["members"]
 *         }
 *     }
 */
export interface ApplyTeamRequest {
    /** Team manifest */
    manifest: TrueFoundry.TeamManifest;
    /** Dry run */
    dryRun?: boolean;
}
