// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../../../index.js";

/**
 * @example
 *     {
 *         limit: 10,
 *         offset: 0,
 *         type: "team",
 *         role: "manager",
 *         attributes: ["attributes"]
 *     }
 */
export interface TeamsListRequest {
    /** Number of items per page */
    limit?: number;
    /** Number of items to skip */
    offset?: number;
    /** Filter teams by type. */
    type?: TrueFoundry.TeamsListRequestType;
    /** Filter to teams where the caller holds this role. `manager` returns teams the caller can manage (team managers and admins). */
    role?: "manager";
    /** Comma-separated list of attributes to return (e.g. `id,teamName`). When provided, only the specified fields are fetched. `id` is always included. */
    attributes?: string | string[];
}
