// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ExecuteWorkflowRequest {
    /** Workflow inputs */
    inputs?: Record<string, unknown>;
    /** Workflow inputs literal map */
    inputsLiteralMap?: Record<string, unknown>;
}
