// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         fqn: "fqn",
 *         agent_skill_id: "agent_skill_id",
 *         ml_repo_id: "ml_repo_id",
 *         name: "name",
 *         version: 1,
 *         offset: 1,
 *         limit: 1
 *     }
 */
export interface AgentSkillVersionsListRequest {
    /** FQN filter for agent skill versions */
    fqn?: string;
    /** Parent agent skill artifact ID */
    agent_skill_id?: string;
    /** ML Repo ID filter */
    ml_repo_id?: string;
    /** Agent skill name filter */
    name?: string;
    /** Version number or 'latest' */
    version?: number;
    /** Pagination offset */
    offset?: number;
    /** Page size */
    limit?: number;
}
