// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../../../index.js";

/**
 * @example
 *     {
 *         manifest: {
 *             name: "name",
 *             color: {},
 *             isProduction: true,
 *             optimizeFor: "COST"
 *         }
 *     }
 */
export interface CreateOrUpdateEnvironmentRequest {
    /** Environment manifest. The environment is matched by `name` for upsert. */
    manifest: TrueFoundry.EnvironmentManifest;
    /** When true, validates the manifest without persisting changes. */
    dryRun?: boolean;
}
