// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../../../index.js";

/**
 * @example
 *     {
 *         manifest: {
 *             type: "truefoundry-agent",
 *             name: "name",
 *             description: "description",
 *             model: {
 *                 name: "name"
 *             },
 *             collaborators: [{
 *                     subject: "subject",
 *                     roleId: "role_id"
 *                 }]
 *         }
 *     }
 */
export interface CreateOrUpdateAgentRequest {
    /** Agent Manifest */
    manifest: TrueFoundry.AgentManifest;
    /** Validate the manifest and collaborators without persisting or syncing to the gateway store */
    dryRun?: boolean;
}
