/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../../../../../index";

/**
 * Job trigger input
 */
export type TriggerJobRequestInput = TrueFoundry.JobTriggerInput | TrueFoundry.SparkJobTriggerInput;
