// This file was auto-generated by Fern from our API Definition.

export const PromptVersionsListRequestVersion = {
    Latest: "latest",
} as const;
export type PromptVersionsListRequestVersion =
    (typeof PromptVersionsListRequestVersion)[keyof typeof PromptVersionsListRequestVersion];
