/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../core/index.js";
import * as TrueFoundry from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace DataDirectories {
    export interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<core.BearerToken | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

export class DataDirectories {
    protected readonly _options: DataDirectories.Options;

    constructor(_options: DataDirectories.Options) {
        this._options = _options;
    }

    /**
     * Get a data directory by its ID.
     *
     * Args:
     *     id (str): The ID of the data directory to retrieve
     *     user_info: Current authenticated user info
     *
     * Returns:
     *     DataDirectoryResponse: Response containing the retrieved data directory
     *
     * @param {string} id
     * @param {DataDirectories.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundry.UnprocessableEntityError}
     *
     * @example
     *     await client.dataDirectories.get("id")
     */
    public get(
        id: string,
        requestOptions?: DataDirectories.RequestOptions,
    ): core.HttpResponsePromise<TrueFoundry.GetDataDirectoryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(id, requestOptions));
    }

    private async __get(
        id: string,
        requestOptions?: DataDirectories.RequestOptions,
    ): Promise<core.WithRawResponse<TrueFoundry.GetDataDirectoryResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api/ml/v1/data-directories/${encodeURIComponent(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as TrueFoundry.GetDataDirectoryResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new TrueFoundry.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueFoundryError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TrueFoundryError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TrueFoundryTimeoutError(
                    "Timeout exceeded when calling GET /api/ml/v1/data-directories/{id}.",
                );
            case "unknown":
                throw new errors.TrueFoundryError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Delete a data directory and optionally its contents.
     *
     * Args:
     *     id: Unique identifier of the data directory to delete
     *     delete_contents: If True, also deletes the data directory's contents
     *     user_info: Authenticated user information
     *
     * Returns:
     *     EmptyResponse: Empty response indicating successful deletion
     *
     * @param {string} id
     * @param {TrueFoundry.DataDirectoriesDeleteRequest} request
     * @param {DataDirectories.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundry.UnprocessableEntityError}
     *
     * @example
     *     await client.dataDirectories.delete("id", {
     *         delete_contents: true
     *     })
     */
    public delete(
        id: string,
        request: TrueFoundry.DataDirectoriesDeleteRequest = {},
        requestOptions?: DataDirectories.RequestOptions,
    ): core.HttpResponsePromise<TrueFoundry.EmptyResponse> {
        return core.HttpResponsePromise.fromPromise(this.__delete(id, request, requestOptions));
    }

    private async __delete(
        id: string,
        request: TrueFoundry.DataDirectoriesDeleteRequest = {},
        requestOptions?: DataDirectories.RequestOptions,
    ): Promise<core.WithRawResponse<TrueFoundry.EmptyResponse>> {
        const { delete_contents: deleteContents = false } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (deleteContents != null) {
            _queryParams["delete_contents"] = deleteContents.toString();
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api/ml/v1/data-directories/${encodeURIComponent(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as TrueFoundry.EmptyResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new TrueFoundry.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueFoundryError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TrueFoundryError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TrueFoundryTimeoutError(
                    "Timeout exceeded when calling DELETE /api/ml/v1/data-directories/{id}.",
                );
            case "unknown":
                throw new errors.TrueFoundryError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * List all data directories with optional filtering and pagination.
     *
     * Args:
     *     filters: Query parameters for filtering and pagination
     *         - ml_repo_id: Filter data directories by ml repo ID
     *         - name: Optional filter data directories by name
     *         - limit: Optional maximum number of data directories to return
     *         - offset: Optional number of data directories to skip
     *     user_info: Authenticated user information
     *
     * Returns:
     *     ListDataDirectoriesResponse: List of data directories and pagination info
     *
     * @param {TrueFoundry.DataDirectoriesListRequest} request
     * @param {DataDirectories.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundry.UnprocessableEntityError}
     *
     * @example
     *     await client.dataDirectories.list({
     *         fqn: "fqn",
     *         ml_repo_id: "ml_repo_id",
     *         name: "name",
     *         limit: 1,
     *         offset: 1
     *     })
     */
    public async list(
        request: TrueFoundry.DataDirectoriesListRequest = {},
        requestOptions?: DataDirectories.RequestOptions,
    ): Promise<core.Page<TrueFoundry.DataDirectory>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: TrueFoundry.DataDirectoriesListRequest,
            ): Promise<core.WithRawResponse<TrueFoundry.ListDataDirectoriesResponse>> => {
                const { fqn, ml_repo_id: mlRepoId, name, limit = 100, offset = 0 } = request;
                const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
                if (fqn != null) {
                    _queryParams["fqn"] = fqn;
                }
                if (mlRepoId != null) {
                    _queryParams["ml_repo_id"] = mlRepoId;
                }
                if (name != null) {
                    _queryParams["name"] = name;
                }
                if (limit != null) {
                    _queryParams["limit"] = limit.toString();
                }
                if (offset != null) {
                    _queryParams["offset"] = offset.toString();
                }
                let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    this._options?.headers,
                    mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                    requestOptions?.headers,
                );
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)),
                        "api/ml/v1/data-directories",
                    ),
                    method: "GET",
                    headers: _headers,
                    queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as TrueFoundry.ListDataDirectoriesResponse,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 422:
                            throw new TrueFoundry.UnprocessableEntityError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.TrueFoundryError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.TrueFoundryError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                            rawResponse: _response.rawResponse,
                        });
                    case "timeout":
                        throw new errors.TrueFoundryTimeoutError(
                            "Timeout exceeded when calling GET /api/ml/v1/data-directories.",
                        );
                    case "unknown":
                        throw new errors.TrueFoundryError({
                            message: _response.error.errorMessage,
                            rawResponse: _response.rawResponse,
                        });
                }
            },
        );
        let _offset = request?.offset != null ? request?.offset : 0;
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Pageable<TrueFoundry.ListDataDirectoriesResponse, TrueFoundry.DataDirectory>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) => (response?.data ?? []).length > 0,
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                _offset += response?.data != null ? response.data.length : 1;
                return list(core.setObjectProperty(request, "offset", _offset));
            },
        });
    }

    /**
     * @param {TrueFoundry.ApplyDataDirectoryRequest} request
     * @param {DataDirectories.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundry.UnprocessableEntityError}
     *
     * @example
     *     await client.dataDirectories.createOrUpdate({
     *         manifest: {
     *             type: "data-dir",
     *             name: "name",
     *             ml_repo: "ml_repo",
     *             metadata: {
     *                 "key": "value"
     *             },
     *             source: {
     *                 type: "truefoundry"
     *             }
     *         }
     *     })
     */
    public createOrUpdate(
        request: TrueFoundry.ApplyDataDirectoryRequest,
        requestOptions?: DataDirectories.RequestOptions,
    ): core.HttpResponsePromise<TrueFoundry.GetDataDirectoryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createOrUpdate(request, requestOptions));
    }

    private async __createOrUpdate(
        request: TrueFoundry.ApplyDataDirectoryRequest,
        requestOptions?: DataDirectories.RequestOptions,
    ): Promise<core.WithRawResponse<TrueFoundry.GetDataDirectoryResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "api/ml/v1/data-directories",
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as TrueFoundry.GetDataDirectoryResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new TrueFoundry.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueFoundryError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TrueFoundryError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TrueFoundryTimeoutError(
                    "Timeout exceeded when calling PUT /api/ml/v1/data-directories.",
                );
            case "unknown":
                throw new errors.TrueFoundryError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * List files in a dataset.
     *
     * Args:
     *     request_dto: Request containing dataset ID, path, page token and limit
     *     user_info: Authenticated user information
     *
     * Returns:
     *     ListFilesResponse: Response containing files and pagination info
     *
     * @param {TrueFoundry.ListFilesRequest} request
     * @param {DataDirectories.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundry.UnprocessableEntityError}
     *
     * @example
     *     await client.dataDirectories.listFiles({
     *         id: "id"
     *     })
     */
    public async listFiles(
        request: TrueFoundry.ListFilesRequest,
        requestOptions?: DataDirectories.RequestOptions,
    ): Promise<core.Page<TrueFoundry.FileInfo>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: TrueFoundry.ListFilesRequest,
            ): Promise<core.WithRawResponse<TrueFoundry.ListFilesResponse>> => {
                let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    this._options?.headers,
                    mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                    requestOptions?.headers,
                );
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)),
                        "api/ml/v1/data-directories/files",
                    ),
                    method: "POST",
                    headers: _headers,
                    contentType: "application/json",
                    queryParameters: requestOptions?.queryParams,
                    requestType: "json",
                    body: request,
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as TrueFoundry.ListFilesResponse,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 422:
                            throw new TrueFoundry.UnprocessableEntityError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.TrueFoundryError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.TrueFoundryError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                            rawResponse: _response.rawResponse,
                        });
                    case "timeout":
                        throw new errors.TrueFoundryTimeoutError(
                            "Timeout exceeded when calling POST /api/ml/v1/data-directories/files.",
                        );
                    case "unknown":
                        throw new errors.TrueFoundryError({
                            message: _response.error.errorMessage,
                            rawResponse: _response.rawResponse,
                        });
                }
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Pageable<TrueFoundry.ListFilesResponse, TrueFoundry.FileInfo>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.pagination.nextPageToken != null &&
                !(typeof response?.pagination.nextPageToken === "string" && response?.pagination.nextPageToken === ""),
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "pageToken", response?.pagination.nextPageToken));
            },
        });
    }

    /**
     * Delete files from the dataset.
     *
     * Args:
     *     request_dto: Request containing dataset ID and paths
     *     user_info: Authenticated user information
     *
     * Returns:
     *     EmptyResponse: Empty response indicating successful deletion
     *
     * @param {TrueFoundry.DeleteFilesRequest} request
     * @param {DataDirectories.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundry.UnprocessableEntityError}
     *
     * @example
     *     await client.dataDirectories.deleteFiles({
     *         id: "id",
     *         paths: ["paths"]
     *     })
     */
    public deleteFiles(
        request: TrueFoundry.DeleteFilesRequest,
        requestOptions?: DataDirectories.RequestOptions,
    ): core.HttpResponsePromise<TrueFoundry.EmptyResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deleteFiles(request, requestOptions));
    }

    private async __deleteFiles(
        request: TrueFoundry.DeleteFilesRequest,
        requestOptions?: DataDirectories.RequestOptions,
    ): Promise<core.WithRawResponse<TrueFoundry.EmptyResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "api/ml/v1/data-directories/files",
            ),
            method: "DELETE",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as TrueFoundry.EmptyResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new TrueFoundry.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueFoundryError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TrueFoundryError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TrueFoundryTimeoutError(
                    "Timeout exceeded when calling DELETE /api/ml/v1/data-directories/files.",
                );
            case "unknown":
                throw new errors.TrueFoundryError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get signed URLs for a dataset.
     *
     * Args:
     *     request_dto: Request containing dataset ID, paths and operation
     *     user_info: Authenticated user information
     *
     * Returns:
     *     GetSignedURLsResponse: Response containing signed URLs
     *
     * @param {TrueFoundry.GetSignedUrLsRequest} request
     * @param {DataDirectories.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundry.UnprocessableEntityError}
     *
     * @example
     *     await client.dataDirectories.getSignedUrls({
     *         id: "id",
     *         paths: ["paths"],
     *         operation: "READ"
     *     })
     */
    public getSignedUrls(
        request: TrueFoundry.GetSignedUrLsRequest,
        requestOptions?: DataDirectories.RequestOptions,
    ): core.HttpResponsePromise<TrueFoundry.GetSignedUrLsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getSignedUrls(request, requestOptions));
    }

    private async __getSignedUrls(
        request: TrueFoundry.GetSignedUrLsRequest,
        requestOptions?: DataDirectories.RequestOptions,
    ): Promise<core.WithRawResponse<TrueFoundry.GetSignedUrLsResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "api/ml/v1/data-directories/signed-urls",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as TrueFoundry.GetSignedUrLsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new TrueFoundry.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueFoundryError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TrueFoundryError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TrueFoundryTimeoutError(
                    "Timeout exceeded when calling POST /api/ml/v1/data-directories/signed-urls.",
                );
            case "unknown":
                throw new errors.TrueFoundryError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create a multipart upload for a dataset
     *
     * Args:
     *     request_dto: Request containing dataset ID, path and number of parts
     *     user_info: Authenticated user information
     *
     * Returns:
     *     MultiPartUploadResponse: Response containing multipart upload info
     *
     * @param {TrueFoundry.CreateMultiPartUploadRequest} request
     * @param {DataDirectories.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundry.UnprocessableEntityError}
     *
     * @example
     *     await client.dataDirectories.createMultipartUpload({
     *         id: "id",
     *         path: "path",
     *         num_parts: 1
     *     })
     */
    public createMultipartUpload(
        request: TrueFoundry.CreateMultiPartUploadRequest,
        requestOptions?: DataDirectories.RequestOptions,
    ): core.HttpResponsePromise<TrueFoundry.MultiPartUploadResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createMultipartUpload(request, requestOptions));
    }

    private async __createMultipartUpload(
        request: TrueFoundry.CreateMultiPartUploadRequest,
        requestOptions?: DataDirectories.RequestOptions,
    ): Promise<core.WithRawResponse<TrueFoundry.MultiPartUploadResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "api/ml/v1/data-directories/signed-urls/multipart",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as TrueFoundry.MultiPartUploadResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new TrueFoundry.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueFoundryError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TrueFoundryError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TrueFoundryTimeoutError(
                    "Timeout exceeded when calling POST /api/ml/v1/data-directories/signed-urls/multipart.",
                );
            case "unknown":
                throw new errors.TrueFoundryError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        const bearer = (await core.Supplier.get(this._options.apiKey)) ?? process?.env["TFY_API_KEY"];
        if (bearer == null) {
            throw new errors.TrueFoundryError({
                message:
                    "Please specify a bearer by either passing it in to the constructor or initializing a TFY_API_KEY environment variable",
            });
        }

        return `Bearer ${bearer}`;
    }
}
