/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../../../../../../index.js";

/**
 * @example
 *     {
 *         manifest: {
 *             name: "name",
 *             metadata: {
 *                 "key": "value"
 *             },
 *             mlRepo: "ml_repo",
 *             type: "model-version",
 *             source: {
 *                 type: "truefoundry"
 *             }
 *         }
 *     }
 */
export interface DeleteMlEntityRequest {
    manifest: DeleteMlEntityRequest.Manifest;
}

export namespace DeleteMlEntityRequest {
    export type Manifest =
        | TrueFoundry.ModelManifest
        | TrueFoundry.ChatPromptManifest
        | TrueFoundry.ArtifactManifest
        | TrueFoundry.DataDirectoryManifest
        | TrueFoundry.MlRepoManifest;
}
