/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../../../../../../../../index";

/**
 * @example
 *     {
 *         applicationType: "async-service",
 *         applicationName: "applicationName",
 *         workspaceId: "workspaceId"
 *     }
 */
export interface DeploymentsGetSuggestedEndpointRequest {
    /**
     * Application Type
     */
    applicationType: TrueFoundry.ApplicationType;
    /**
     * Application name
     */
    applicationName: string;
    /**
     * Workspace id
     */
    workspaceId: string;
    /**
     * Base domain
     */
    baseDomain?: string;
    /**
     * Port
     */
    port?: string;
    /**
     * Prefer wildcard
     */
    preferWildcard?: boolean;
}
