// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../../../index.js";

/**
 * @example
 *     {
 *         startTs: "startTs",
 *         endTs: "endTs",
 *         clusterId: "clusterId",
 *         applicationId: "applicationId",
 *         alertStatus: "firing"
 *     }
 */
export interface AlertsListRequest {
    /** Start timestamp for filtering alerts (ISO 8601 format, UTC). Must be before endTs. */
    startTs?: string;
    /** End timestamp for filtering alerts (ISO 8601 format, UTC). Must be after startTs. */
    endTs?: string;
    /** Unique identifier of the cluster. */
    clusterId?: string;
    /** Unique identifier of the application. */
    applicationId?: string;
    /** Filter by alert status. */
    alertStatus?: TrueFoundry.AlertStatus;
}
