// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         limit: 10,
 *         offset: 0
 *     }
 */
export interface ListDataDirectoriesRequest {
    /** Number of items per page */
    limit?: number | null;
    /** Number of items to skip */
    offset?: number | null;
    /** Fully qualified name to filter by */
    fqn?: string | null;
    /** ID of the ML Repo to filter by */
    mlRepoId?: string | null;
    /** Name of the data directory to filter by */
    name?: string | null;
}
