// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";

export const GetGatewayConfigAiGatewayRequestType: core.serialization.Schema<serializers.internal.GetGatewayConfigAiGatewayRequestType.Raw, TrueFoundry.internal.GetGatewayConfigAiGatewayRequestType> = core.serialization.enum_(["gateway-rate-limiting-config", "gateway-fallback-config", "gateway-load-balancing-config", "gateway-guardrails-config", "gateway-budget-config", "tenant-budget-config", "team-budget-config", "gateway-otel-config", "gateway-global-settings", "gateway-data-access-config", "gateway-data-routing-config"]);

export declare namespace GetGatewayConfigAiGatewayRequestType {
    export type Raw = "gateway-rate-limiting-config" | "gateway-fallback-config" | "gateway-load-balancing-config" | "gateway-guardrails-config" | "gateway-budget-config" | "tenant-budget-config" | "team-budget-config" | "gateway-otel-config" | "gateway-global-settings" | "gateway-data-access-config" | "gateway-data-routing-config";
}
