// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as errors from "../../../../errors/index.js";
import * as TrueFoundry from "../../../index.js";

export declare namespace Events {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Events {
    protected readonly _options: Events.Options;

    constructor(_options: Events.Options) {
        this._options = _options;
    }

    /**
     * Get Events for Pod, Job Run, Application. The events are sourced from Kubernetes as well as events captured by truefoundry. Optional query parameters include startTs, endTs for filtering.
     *
     * @param {TrueFoundry.EventsGetRequest} request
     * @param {Events.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundry.BadRequestError}
     * @throws {@link TrueFoundry.ForbiddenError}
     * @throws {@link TrueFoundry.NotFoundError}
     *
     * @example
     *     await client.events.get({
     *         startTs: "startTs",
     *         endTs: "endTs",
     *         applicationId: "applicationId",
     *         applicationFqn: "applicationFqn",
     *         jobRunName: "jobRunName"
     *     })
     */
    public get(
        request: TrueFoundry.EventsGetRequest = {},
        requestOptions?: Events.RequestOptions,
    ): core.HttpResponsePromise<TrueFoundry.GetEventsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: TrueFoundry.EventsGetRequest = {},
        requestOptions?: Events.RequestOptions,
    ): Promise<core.WithRawResponse<TrueFoundry.GetEventsResponse>> {
        const { startTs, endTs, applicationId, applicationFqn, podNames, jobRunName } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (startTs != null) {
            _queryParams.startTs = startTs;
        }

        if (endTs != null) {
            _queryParams.endTs = endTs;
        }

        if (applicationId != null) {
            _queryParams.applicationId = applicationId;
        }

        if (applicationFqn != null) {
            _queryParams.applicationFqn = applicationFqn;
        }

        if (podNames != null) {
            if (Array.isArray(podNames)) {
                _queryParams.podNames = podNames.map((item) => item);
            } else {
                _queryParams.podNames = podNames;
            }
        }

        if (jobRunName != null) {
            _queryParams.jobRunName = jobRunName;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "api/svc/v1/events",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as TrueFoundry.GetEventsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TrueFoundry.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new TrueFoundry.ForbiddenError(
                        _response.error.body as TrueFoundry.HttpError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TrueFoundry.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.TrueFoundryError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TrueFoundryError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TrueFoundryTimeoutError("Timeout exceeded when calling GET /api/svc/v1/events.");
            case "unknown":
                throw new errors.TrueFoundryError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        const bearer = (await core.Supplier.get(this._options.apiKey)) ?? process?.env.TFY_API_KEY;
        if (bearer == null) {
            throw new errors.TrueFoundryError({
                message:
                    "Please specify a bearer by either passing it in to the constructor or initializing a TFY_API_KEY environment variable",
            });
        }

        return `Bearer ${bearer}`;
    }
}
