// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

export interface AgentIdentity {
    id?: string | null;
    tenantName: string;
    /** Agent identity manifest */
    manifest: Record<string, unknown>;
    createdBySubject: TrueFoundry.Subject;
    accountId: string;
    createdAt: Date;
    updatedAt: Date;
}
