// This file was auto-generated by Fern from our API Definition.

/**
 * SKILL.md for this version when using inline source.
 */
export interface AgentSkillSourceInline {
    type: "inline";
    /** Main body of SKILL.md file. */
    skill_md: string;
}
