// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * Shared artifact-version fields (identity, manifest union, ML repo).
 */
export interface AgentSkillVersion {
    /** Unique identifier for the artifact version */
    id: string;
    /** Fully qualified name of the artifact version in the format '{artifact_type}:{tenant_name}/{ml_repo_name}/{artifact_name}:{version}' */
    fqn: string;
    /** Subject (user, team, or service account) that created this artifact version */
    created_by_subject: TrueFoundry.Subject;
    /** Timestamp when the artifact version was created */
    created_at?: string | undefined;
    /** Timestamp when the artifact version was last updated */
    updated_at?: string | undefined;
    /** Manifest containing metadata specific to this agent skill version */
    manifest: TrueFoundry.AgentSkillManifest;
    /** ID of the ML Repo that this artifact version belongs to */
    ml_repo_id: string;
    /** ID of the parent agent skill artifact that this version belongs to */
    agent_skill_id: string;
}
