// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * AI21 Model
 */
export interface Ai21Model {
    /** +value=integration/model/ai21 */
    type: "integration/model/ai21";
    /** A descriptive name to identify this model integration in the UI */
    name: string;
    /** The AI21 model identifier (e.g., jamba-large, jamba-mini). This is the model name from AI21's model catalog. */
    model_id: string;
    /** Specify the type of the AI21 model */
    model_types: TrueFoundry.ModelType[];
    cost?: TrueFoundry.ModelCostMetric;
    /** List of subjects that are authorized to access this integration. List of user fqn in format <user_type>:<username>. */
    authorized_subjects?: string[];
}
