// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../index.js";

/**
 * Akto
 */
export interface AktoGuardrailConfig {
    /** The name of the Guardrail Config. */
    name: string;
    /** Optional description for this Guardrail Config. */
    description?: string;
    /**
     * +uiType=Hidden
     * +value=integration/guardrail-config/akto
     */
    type: "integration/guardrail-config/akto";
    authData: TrueFoundry.AktoTokenAuth;
    /** The operation type for this guardrail. Akto guardrails can only be used for validation. */
    operation: "validate";
    enforcingStrategy: TrueFoundry.EnforcingStrategy;
    /**
     * +uiType=Ignore
     * +uiProps={"forwardJsonKey": true}
     */
    config: TrueFoundry.AktoGuardrailConfigConfig;
}
