// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * All Data
 */
export interface AllDataAccessRule extends TrueFoundry.DataAccessRuleBase {
    /** Data access scope - access to all data with optional filters */
    scope: "all_data";
    /** Optional filters to restrict data access (only applicable for all_data scope) */
    filters?: TrueFoundry.AllDataAccessRuleFiltersItem[];
}
