// This file was auto-generated by Fern from our API Definition.

/**
 * Describes the configuration for the output AMQP worker
 */
export interface AmqpOutputConfig {
    /** +value=amqp */
    type: "amqp";
    /** AMQP Queue URL of Publisher */
    url: string;
    /** AMQP Routing Key to publish to. */
    routing_key: string;
    /** AMQP Exchange Name */
    exchange_name?: string;
}
