// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

export type ApplyMlEntityResponseData =
    | TrueFoundry.ModelVersion
    | TrueFoundry.PromptVersion
    | TrueFoundry.ArtifactVersion
    | TrueFoundry.DataDirectory
    | TrueFoundry.TracingProject;
