// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

export interface ApplicationDebugInfo {
    id?: string | undefined;
    applicationId: string;
    application?: TrueFoundry.Application | undefined;
    debugInfo: Record<string, unknown>;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
}
