// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * Log a new Artifact Version containing files and folders with metadata
 */
export interface ArtifactManifest extends TrueFoundry.BaseArtifactVersion {
    /** Artifact Version */
    type?: "artifact-version" | undefined;
    /** Description */
    description?: string | undefined;
    /** Version alias is alternate, ideally human readable, version string to reference an artifact version. It should start with `v` followed by alphanumeric and it can include `.` and `-` in between (e.g. `v1.0.0`, `v1-prod`, `v3-dev`, etc) */
    version_alias?: string | undefined;
    /** Artifact Source */
    source: TrueFoundry.ArtifactManifestSource;
    /** Step/Epoch number in an iterative training loop the artifact version was created. Generally useful when logging a model version from a MLRepo Run */
    step: number;
    /** ID of the MLRepo Run that generated the artifact version */
    run_id?: string | undefined;
}
