// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * Deploy multiple instances of your pods to distribute incoming traffic across them, ensuring effective load balancing.
 */
export type AsyncServiceReplicas = number | TrueFoundry.AsyncServiceAutoscaling;
