// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

export interface AsyncServiceAutoscaling extends TrueFoundry.BaseAutoscaling {
    /** Metrics to use for the autoscaler */
    metrics: TrueFoundry.AsyncServiceAutoscalingMetrics;
}
