// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../index.js";

/**
 * +uiType=Ignore
 * +uiProps={"forwardJsonKey": true}
 */
export interface AwsBedrockGuardrailConfigConfig {
    /** The unique identifier of the Bedrock Guardrail created in AWS console */
    guardrailId: string;
    /** Version number of the guardrail to use (e.g., 2 for version 2) */
    guardrailVersion: string;
    region: TrueFoundry.AwsRegion;
}
