/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index";

/**
 * +label=AWS ECR
 * +icon=aws-ecr
 */
export interface AwsEcr {
    /** +value=integration/docker-registry/aws/ecr */
    type: "integration/docker-registry/aws/ecr";
    /**
     * +label=Display Name
     * +usage=The name of the integration that will be displayed in the TrueFoundry UI.
     * +sort=100
     * +message=3 to 32 lower case characters long alphanumeric word, may contain - in between, cannot start with a number
     */
    name: string;
    /**
     * +label=Registry URL
     * +usage=The URL of the registry.
     * +sort=200
     */
    registry_url: string;
    /**
     * +label=Auth Data
     * +usage=Custom authentication data for the integration.
     * +sort=300
     */
    auth_data?: TrueFoundry.AwsEcrAuthData;
    /**
     * +label=Access Control
     * +usage=List of subjects that are authorized to access this integration. List of user fqn in format <user_type>:<username>.
     * +sort=600
     * +uiType=AuthorizedSubjects
     */
    authorized_subjects?: string[];
}
