/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

export type AwsIntegrations =
    | TrueFoundry.AwsEcr
    | TrueFoundry.AwsS3
    | TrueFoundry.AwsParameterStore
    | TrueFoundry.AwsSecretsManager
    | TrueFoundry.AwsEksIntegration
    | TrueFoundry.BedrockModel;
