/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

/**
 * +label=Azure Vault
 * +icon=azure-vault
 */
export interface AzureVault {
    /** +value=integration/secret-store/azure/vault */
    type: "integration/secret-store/azure/vault";
    /**
     * +label=Display Name
     * +usage=The name of the integration that will be displayed in the TrueFoundry UI.
     * +sort=150
     * +message=3 to 32 lower case characters long alphanumeric word, may contain - in between, cannot start with a number
     */
    name: string;
    auth_data?: TrueFoundry.AzureOAuth;
    /**
     * +label=Azure Key vault Name
     * +usage=Name of key vault name.
     * +sort=300
     */
    key_vault_name: string;
    /**
     * +label=Access Control
     * +usage=List of subjects that are authorized to access this integration. List of user fqn in format <user_type>:<username>.
     * +sort=400
     * +uiType=AuthorizedSubjects
     */
    authorized_subjects?: string[];
}
