// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * Azure OpenAI Model
 */
export interface AzureOpenAiModel {
    /** +value=integration/model/azure-openai */
    type: "integration/model/azure-openai";
    /** A descriptive name to identify this model integration in the UI */
    name: string;
    /** The model deployment name created in your Azure OpenAI resource (e.g., gpt-4-deployment, gpt-35-turbo-deployment). This is NOT the base model name but the deployment name you configured in Azure. */
    model_id: string;
    /** The Azure OpenAI API version to use */
    api_version: string;
    /** Specify the type of the Azure OpenAI model */
    model_types: TrueFoundry.ModelType[];
    cost?: TrueFoundry.ModelCostMetric;
    /** List of subjects that are authorized to access this integration. List of user fqn in format <user_type>:<username>. */
    authorized_subjects?: string[];
}
