// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * Azure AI Foundry Provider Account
 */
export interface AzureFoundryProviderAccount {
    /** +value=provider-account/azure-foundry */
    type?: "provider-account/azure-foundry" | undefined;
    /** The name of the Azure AI Foundry provider account */
    name: string;
    /** List of integrations that are associated with the Azure Foundry provider account */
    integrations: TrueFoundry.AzureFoundryModel[];
    /** List of users who have access to this provider account */
    collaborators?: TrueFoundry.Collaborator[] | undefined;
    ownedBy?: TrueFoundry.OwnedBy | undefined;
    /** Discount % applied to upstream list price for this provider account. */
    discount_percent?: number | undefined;
}
