// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../index.js";

/**
 * +uiType=Ignore
 * +uiProps={"forwardJsonKey": true}
 */
export interface AzureContentSafetyGuardrailConfigConfig {
    /** Name of your Azure Content Safety resource where the service is deployed (e.g., my-content-safety) */
    resourceName: string;
    /** API version for the Content Safety API */
    apiVersion: string;
    /** Custom endpoint URL for the Content Safety API (optional, uses default Azure endpoint if not specified) */
    customHost?: string;
    /** Names of custom blocklists created in Azure Content Safety to check text against. Leave empty if not using custom blocklists */
    blocklistNames?: string[];
    /** Minimum severity level (0-6) to flag content. Lower values are more restrictive (more content is blocked). 0=Safe, 2=Low risk, 4=Medium risk, 6=High risk */
    severityThreshold: number;
    /** Types of harmful content to detect: Hate (hate speech), SelfHarm (self-injury), Sexual (sexual content), Violence (violent content) */
    categories: TrueFoundry.AzureContentSafetyCategory[];
}
