/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * +label=Azure AI Serverless Deployment
 */
export interface AzureAiServerlessDeployment {
    /** +value=serverless */
    type: "serverless";
    /**
     * +label=Azure Deployment Name
     * +usage=Name of the Azure AI deployment
     * +sort=100
     */
    deploymentName: string;
    /**
     * +label=Azure Region
     * +usage=Region where the Azure AI deployment is located
     * +sort=200
     */
    region: string;
}
