// This file was auto-generated by Fern from our API Definition.

/**
 * Username and password
 */
export interface BasicAuthCreds {
    /** +value=basic_auth */
    type: "basic_auth";
    /** Username for service auth - Username for the user to authenticate with */
    username: string;
    /** Password for service auth - Password for the user to authenticate with */
    password: string;
}
