/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index";

/**
 * +label=Bitbucket
 * +icon=bitbucket
 */
export interface BitbucketProviderAccount {
    /** +value=provider-account/bitbucket */
    type: "provider-account/bitbucket";
    /** +uiProps={"disableEdit":true} */
    name: string;
    /** +uiType=IntegrationsGroup */
    integrations: TrueFoundry.BitbucketIntegration[];
}
