/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * +docs=This strategy brings up the new release completely before switching the complete load to the new release.
 * This minimizes the time that two versions are serving traffic at the same time.
 * +label=Blue Green strategy
 */
export interface BlueGreen {
    /**
     * +docs=Promote the new release to handle the complete traffic after waiting for these many seconds
     * +label=Auto-promotion seconds
     */
    auto_promotion_seconds?: number;
    /**
     * +docs=Promote the new release to handle the complete traffic. A manual promotion would be needed if this is disabled
     * +label=Auto-promotion
     */
    enable_auto_promotion?: boolean;
    /** +value=blue_green */
    type: "blue_green";
}
