// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * +discriminator=type
 */
export type BudgetV2AppliesTo =
    | TrueFoundry.BudgetV2AppliesToAggregate
    | TrueFoundry.BudgetV2AppliesToPerUser
    | TrueFoundry.BudgetV2AppliesToPerModel
    | TrueFoundry.BudgetV2AppliesToPerVirtualAccount
    | TrueFoundry.BudgetV2AppliesToMetadata;
