// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

export interface BudgetEntityUsage {
    /** Entity counter this usage maps to; null for aggregate budgets. */
    entity?: string | null;
    /** Per-period usage keyed by period (cost_per_day, cost_per_month, ...). */
    periods: Record<string, TrueFoundry.PeriodUsage>;
}
