// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../index.js";

/**
 * Budget Alert
 */
export interface BudgetAlert {
    /** List of usage percentages (0-100) at which alerts should be triggered. Default thresholds are [75, 90, 95, 100]. */
    thresholds: number[];
    /** Select where to send budget alert notifications */
    notificationTarget: TrueFoundry.NotificationTarget[];
}
