// This file was auto-generated by Fern from our API Definition.

export const BuildStatus = {
    Started: "STARTED",
    Succeeded: "SUCCEEDED",
    Failed: "FAILED",
} as const;
export type BuildStatus = (typeof BuildStatus)[keyof typeof BuildStatus];
