// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * Cohere Provider Account
 */
export interface CohereProviderAccount {
    /** +value=provider-account/cohere */
    type?: "provider-account/cohere" | undefined;
    /** The name of the Cohere provider account */
    name: string;
    auth_data: TrueFoundry.CohereKeyAuth;
    /** List of integrations that are associated with the Cohere provider account */
    integrations?: TrueFoundry.CohereIntegrations[] | undefined;
    /** List of users who have access to this provider account */
    collaborators?: TrueFoundry.Collaborator[] | undefined;
    ownedBy?: TrueFoundry.OwnedBy | undefined;
    /** Discount % applied to upstream list price for this provider account. */
    discount_percent?: number | undefined;
}
