/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateDeploymentRequest {
    /** Manifest of application */
    manifest: Record<string, unknown>;
    /** Dry run */
    dryRun?: boolean;
    /** Cancels any ongoing deployments */
    forceDeploy?: boolean;
    /** workspace id of the workspace */
    workspaceId?: string;
    /** Id of the application */
    applicationId?: string;
    /** Name of application */
    name?: string;
    /** Application Set Id */
    applicationSetId?: string;
}
