// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * Custom Endpoint
 */
export interface CustomEndpointProviderAccount {
    /** +value=provider-account/custom-endpoint */
    type: "provider-account/custom-endpoint";
    /** The name of the custom endpoint provider account. */
    name: string;
    /** The type of service behind this endpoint (used for tracking purposes) */
    endpoint_type?: TrueFoundry.CustomEndpointProviderAccountEndpointType | undefined;
    auth_data?: TrueFoundry.CustomHeaderAuth | undefined;
    /** List of endpoint integrations associated with this provider account. */
    integrations: TrueFoundry.CustomEndpointIntegrations[];
    /** Collaborators */
    collaborators?: TrueFoundry.Collaborator[] | undefined;
    ownedBy?: TrueFoundry.OwnedBy | undefined;
}
