/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

/**
 * Custom Model
 */
export interface CustomModel {
    /** 2 to 62 characters long alphanumeric word, may contain - in between, cannot start with a number */
    name: string;
    hosted_model_name: string;
    /** enter valid https/http URL that should not end with trailing slash */
    url: string;
    model_server: TrueFoundry.CustomModelModelServer;
    /** +uiType=Hidden */
    tfy_application_id?: string;
    /** +value=integration/model/custom */
    type: "integration/model/custom";
    /** Specify the type of the model */
    model_types: TrueFoundry.ModelType[];
    /** Custom authentication data for the integration. */
    auth_data?: TrueFoundry.CustomModelAuthData;
    /** Custom headers for the integration. Forwarded to the provider as is. For example: `{"Authorization": "APIKey <token>"}` */
    headers?: Record<string, string>;
    cost?: TrueFoundry.ModelCostMetric;
    /** List of subjects that are authorized to access this integration. List of user fqn in format <user_type>:<username>. */
    authorized_subjects?: string[];
}
