/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

/**
 * Databricks Provider Account
 */
export interface DatabricksProviderAccount {
    /** +value=provider-account/databricks */
    type: "provider-account/databricks";
    /** The name of the Databricks provider account */
    name: string;
    /** Databricks authentication credentials */
    auth_data: TrueFoundry.DatabricksProviderAccountAuthData;
    /** The base URL of your Databricks workspace */
    base_url: string;
    /** List of integrations that are associated with the Databricks provider account */
    integrations: TrueFoundry.DatabricksIntegrations[];
    /** List of users who have access to this provider account */
    collaborators?: TrueFoundry.Collaborator[];
    ownedBy?: TrueFoundry.OwnedBy;
}
