/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

/**
 * +label=Databricks Provider Account
 * +icon=databricks
 */
export interface DatabricksProviderAccount {
    /** +value=provider-account/databricks */
    type: "provider-account/databricks";
    /**
     * +label=Name
     * +sort=100
     * +usage=The name of the Databricks provider account
     * +message=3 to 32 lower case characters long alphanumeric word, may contain - in between, cannot start with a number
     * +uiProps={"disableEdit":true}
     */
    name: string;
    /**
     * +label=Auth Data
     * +sort=300
     * +usage=Databricks authentication credentials
     */
    auth_data: DatabricksProviderAccount.AuthData;
    /**
     * +label=Base URL
     * +sort=400
     * +usage=The base URL of your Databricks workspace
     * +message=Base URL must not be empty
     */
    base_url: string;
    /**
     * +label=Integrations
     * +sort=500
     * +usage=List of integrations that are associated with the Databricks provider account
     * +uiType=IntegrationsGroup
     */
    integrations: TrueFoundry.DatabricksIntegrations[];
    /**
     * +label=Collaborators
     * +sort=200
     * +usage=List of users who have access to this provider account
     * +uiType=Collaborators
     */
    collaborators?: TrueFoundry.Collaborator[];
}

export namespace DatabricksProviderAccount {
    /**
     * +label=Auth Data
     * +sort=300
     * +usage=Databricks authentication credentials
     */
    export type AuthData = TrueFoundry.DatabricksServicePrincipalAuth | TrueFoundry.DatabricksApiKeyAuth;
}
