// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

export interface DeploymentBuild {
    id?: string | undefined;
    deploymentId?: string | undefined;
    componentName?: string | undefined;
    build?: TrueFoundry.BuildInfo | undefined;
    buildId?: string | undefined;
    imageUri?: string | undefined;
    name?: string | undefined;
    status?: TrueFoundry.BuildStatus | undefined;
    getLogsUrl?: string | undefined;
    tailLogsUrl?: string | undefined;
    logsStartTs?: string | undefined;
    metadata?: Record<string, unknown> | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
}
