// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * Developer message for the chat
 */
export interface DeveloperMessage {
    /** The role of the messages author, in this case developer. */
    role: "developer";
    /** The contents of the developer message. */
    content: TrueFoundry.DeveloperMessageContent;
    /** An optional name for the participant. */
    name?: string;
}
