/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DeviceConfigurationType =
    | "nvidia_gpu"
    | "aws_inferentia"
    | "nvidia_mig_gpu"
    | "nvidia_timeslicing_gpu"
    | "gcp_tpu";
export const DeviceConfigurationType = {
    NvidiaGpu: "nvidia_gpu",
    AwsInferentia: "aws_inferentia",
    NvidiaMigGpu: "nvidia_mig_gpu",
    NvidiaTimeslicingGpu: "nvidia_timeslicing_gpu",
    GcpTpu: "gcp_tpu",
} as const;
