/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Operation type for duration filter
 */
export type DurationFilterOperation = ">" | "<" | "=" | ">=" | "<=" | "BETWEEN";
export const DurationFilterOperation = {
    GreaterThan: ">",
    LessThan: "<",
    EqualTo: "=",
    GreaterThanOrEqualTo: ">=",
    LessThanOrEqualTo: "<=",
    Between: "BETWEEN",
} as const;
