// This file was auto-generated by Fern from our API Definition.

export interface EnvironmentColor {
    colorHex?: string;
    backgroundColorHex?: string;
    color?: string;
    backgroundColor?: string;
}
