/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ExternalBlobStorageSource {
    /** Type of the source */
    type: "external";
    /** URI referencing a path in the blob storage bucket linked to the MLRepo */
    uri: string;
}
