/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FiddlerKeyAuth {
    /** +value=api-key */
    type: "api-key";
    /**
     * +uiType=Password
     * +sort=100
     * +usage=API key for the Fiddler account
     */
    api_key: string;
}
