// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * Gateway Data Access Configuration
 */
export interface GatewayDataAccessConfig {
    /**
     * +value=gateway-data-access-config
     * +sort=1
     */
    type: "gateway-data-access-config";
    /** List of data access rules */
    rules: TrueFoundry.DataAccessRule[];
}
