// This file was auto-generated by Fern from our API Definition.

export const GatewayRequestMetadataFilterOperator = {
    Equal: "EQUAL",
    GreaterThan: "GREATER_THAN",
    LessThan: "LESS_THAN",
    GreaterThanEqual: "GREATER_THAN_EQUAL",
    LessThanEqual: "LESS_THAN_EQUAL",
    Between: "BETWEEN",
    In: "IN",
    NotIn: "NOT_IN",
    StringContains: "STRING_CONTAINS",
    StringStartsWith: "STRING_STARTS_WITH",
    StringEndsWith: "STRING_ENDS_WITH",
    ArrayHasAny: "ARRAY_HAS_ANY",
    ArrayHasNone: "ARRAY_HAS_NONE",
    Present: "PRESENT",
    IsNull: "IS_NULL",
} as const;
export type GatewayRequestMetadataFilterOperator =
    (typeof GatewayRequestMetadataFilterOperator)[keyof typeof GatewayRequestMetadataFilterOperator];
