// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * Created By Filter
 */
export interface GatewayDataCreatedByFilter {
    /** Filter type */
    field: "created_by";
    /** Comparison operator */
    operator: TrueFoundry.GatewayDataCreatedByFilterOperator;
    /** List of subjects (users, virtual accounts, teams) to filter by */
    value: string[];
}
