/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

/**
 * +icon=gcp-gsm
 * +label=GCP GSM
 */
export interface GcpGsm {
    /** +value=integration/secret-store/gcp/gsm */
    type: "integration/secret-store/gcp/gsm";
    /**
     * +label=Display Name
     * +usage=The name of the integration that will be displayed in the TrueFoundry UI.
     * +sort=100
     * +message=3 to 32 lower case characters long alphanumeric word, may contain - in between, cannot start with a number
     */
    name: string;
    auth_data?: TrueFoundry.GcpKeyFileAuth;
    /**
     * +label=Access Control
     * +usage=List of subjects that are authorized to access this integration. List of user fqn in format <user_type>:<username>.
     * +sort=600
     * +uiType=AuthorizedSubjects
     */
    authorized_subjects?: string[];
}
