// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * GCP GKE
 */
export interface GcpGkeIntegration {
    /** +value=integration/cluster/gcp/gke-standard */
    type: "integration/cluster/gcp/gke-standard";
    /** The name of the integration that will be displayed in the TrueFoundry UI. */
    name: string;
    location: TrueFoundry.GcpRegion;
    /** Name of the cluster given in the cloud account. */
    cluster_name: string;
    auth_data?: TrueFoundry.GcpKeyFileAuth;
    /** List of subjects that are authorized to access this integration. List of user fqn in format <user_type>:<username>. */
    authorized_subjects?: string[];
}
