// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * GCP Key File Auth
 */
export interface GcpKeyFileAuth {
    /** +value=key-file */
    type: "key-file";
    /** Key File Content - Key file content must be valid JSON */
    key_file_content: TrueFoundry.GcpKeyFileAuthKeyFileContent;
}
