// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * Generic Secret Store
 */
export interface GenericSecretStoreIntegration {
    /** +value=integration/secret-store/custom/generic */
    type: "integration/secret-store/custom/generic";
    /** The name of the integration that will be displayed in the TrueFoundry UI. */
    name: string;
    /** Base URL of the generic secret server. */
    base_url: string;
    auth_data: TrueFoundry.CustomHeaderAuth;
    /** List of subjects that are authorized to access this integration. List of user fqn in format <user_type>:<username>. */
    authorized_subjects?: string[] | undefined;
}
