// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../index.js";

export interface GetApplicationResponse {
    /** Application details */
    data: TrueFoundry.Application;
}
