// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

export interface GetEnvironmentResponse {
    /** Environment */
    data: TrueFoundry.Environment;
}
