// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../index.js";

export interface GetMetricHistoryResponse {
    /** Time-series history for the requested metric. */
    metrics: TrueFoundry.Metric[];
}
