/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * +label=Github
 * +icon=github
 */
export interface GithubIntegration {
    /** +value=integration/vcs/github */
    type: "integration/vcs/github";
    /** +sort=100 */
    name: string;
    /**
     * +label=Account Name
     * +sort=200
     */
    account_name: string;
    /** List of subjects that are authorized to access this integration. List of user fqn in format <user_type>:<username>. */
    authorized_subjects?: string[];
}
