/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

/**
 * +label=Google Gemini Provider Account
 * +icon=googleCloud
 */
export interface GoogleGeminiProviderAccount {
    /** +value=provider-account/google-gemini */
    type: "provider-account/google-gemini";
    /**
     * +label=Name
     * +sort=100
     * +usage=The name of the Google Gemini provider account
     * +message=3 to 32 lower case characters long alphanumeric word, may contain - in between, cannot start with a number
     * +uiProps={"disableEdit":true}
     */
    name: string;
    authData: TrueFoundry.GcpApiKeyAuth;
    /**
     * +label=Integrations
     * +sort=500
     * +usage=List of integrations that are associated with the Google Gemini provider account
     * +uiType=IntegrationsGroup
     */
    integrations: TrueFoundry.GeminiModelV2[];
    /**
     * +label=Collaborators
     * +sort=200
     * +usage=List of users who have access to this provider account
     * +uiType=Collaborators
     */
    collaborators?: TrueFoundry.Collaborator[];
}
