/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

/**
 * +label=Google Model
 * +icon=googleCloud
 */
export interface GoogleModel {
    /**
     * +label=Display Name
     * +sort=1
     * +message=2 to 62 characters long alphanumeric word, may contain - or . in between, cannot start with a number
     */
    name: string;
    /** +sort=2 */
    model_id: string;
    /** +value=integration/model/gcp/google */
    type: "integration/model/gcp/google";
    /**
     * +usage=Specify the type of the model
     * +sort=4
     */
    model_types: TrueFoundry.ModelType[];
    auth_data?: TrueFoundry.GcpApiKeyAuth;
    cost?: TrueFoundry.ModelCostMetric;
    /**
     * +label=Access Control
     * +usage=List of subjects that are authorized to access this integration. List of user fqn in format <user_type>:<username>.
     * +uiType=Hidden
     */
    authorized_subjects?: string[];
}
