/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

/**
 * +label=Google Vertex Provider Account
 * +icon=googleCloud
 * +heroDataKey=project_id
 */
export interface GoogleVertexProviderAccount {
    /** +value=provider-account/google-vertex */
    type: "provider-account/google-vertex";
    /**
     * +label=Name
     * +sort=100
     * +usage=The name of the Google Vertex provider account
     * +message=3 to 32 lower case characters long alphanumeric word, may contain - in between, cannot start with a number
     * +uiProps={"disableEdit":true}
     */
    name: string;
    /**
     * +label=Project ID
     * +sort=200
     * +usage=The Google Cloud project ID where Vertex AI is enabled
     * +message=Project ID must not be empty
     */
    project_id: string;
    region: TrueFoundry.GcpRegion;
    auth_data?: TrueFoundry.GcpKeyFileAuth;
    /**
     * +label=Integrations
     * +sort=500
     * +usage=List of integrations that are associated with the Google Vertex provider account
     * +uiType=IntegrationsGroup
     */
    integrations: TrueFoundry.VertexModelV2[];
    /**
     * +label=Collaborators
     * +sort=600
     * +usage=List of users who have access to this provider account
     * +uiType=Collaborators
     */
    collaborators?: TrueFoundry.Collaborator[];
}
