/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

/**
 * Groq Model
 */
export interface GroqModel {
    /** +value=integration/model/groq */
    type: "integration/model/groq";
    /** Name to identify this Groq model in the UI */
    name: string;
    /** The name of the Groq model to use */
    model_id: string;
    /** Specify the type of the Groq model */
    model_types: TrueFoundry.ModelType[];
    cost?: TrueFoundry.ModelCostMetric;
    /** List of subjects that are authorized to access this integration. List of user fqn in format <user_type>:<username>. */
    authorized_subjects?: string[];
}
