// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * Guardrails Rule
 */
export interface GuardrailsRule {
    /** Unique identifier for the rule */
    id: string;
    when: TrueFoundry.GuardrailsWhen;
    /** Guardrail selectors of the guardrails to apply to the input (format: groupName/guardrailName) */
    llm_input_guardrails: string[];
    /** Guardrail selectors of the guardrails to apply to the output (format: groupName/guardrailName) */
    llm_output_guardrails: string[];
    /** Guardrail selectors of the guardrails to apply to the MCP tool pre invoke (format: groupName/guardrailName) */
    mcp_tool_pre_invoke_guardrails: string[];
    /** Guardrail selectors of the guardrails to apply to the MCP tool post invoke (format: groupName/guardrailName) */
    mcp_tool_post_invoke_guardrails: string[];
}
