// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * HashiCorp Vault Integration
 */
export interface HashicorpVaultIntegration {
    /** +value=integration/secret-store/hashicorp/vault */
    type: "integration/secret-store/hashicorp/vault";
    /** The name of the integration that will be displayed in the TrueFoundry UI. */
    name: string;
    /** The URL of the HashiCorp Vault server (e.g., https://vault.example.com:8200). */
    vault_url: string;
    /** Mount path of the KV v2 engine vault to use for secrets. */
    kv_mount_path: string;
    root_path?: string | undefined;
    /** Authentication data for the Vault integration. */
    auth_data: TrueFoundry.HashicorpVaultIntegrationAuthData;
    /** List of subjects that are authorized to access this integration. List of user fqn in format <user_type>:<username>. */
    authorized_subjects?: string[] | undefined;
    /** Namespace for vault operations, used for multi-tenancy in HashiCorp Vault Enterprise. Optional for open source Vault. */
    namespace?: string | undefined;
}
