// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * HashiCorp Vault Integration
 */
export interface HashicorpVaultIntegration {
    /** +value=integration/secret-store/hashicorp/vault */
    type: "integration/secret-store/hashicorp/vault";
    /** The name of the integration that will be displayed in the TrueFoundry UI. */
    name: string;
    /** The URL of the HashiCorp Vault server (e.g., https://vault.example.com:8200). */
    vault_url: string;
    auth_data: TrueFoundry.HashicorpTokenAuth;
    /** List of subjects that are authorized to access this integration. List of user fqn in format <user_type>:<username>. */
    authorized_subjects?: string[];
}
