/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index";

/**
 * +docs=Describes the configuration for the Health Probe's
 * To learn more you can go [here](https://docs.truefoundry.com/docs/liveness-readiness-probe)
 * +icon=fa-heart
 * +uiType=HealthProbe
 */
export interface HealthProbe {
    config: TrueFoundry.HttpProbe;
    /** +usage=Number of consecutive failures before the container is considered down */
    failure_threshold?: number;
    /** +usage=Time to wait after container has started before checking the endpoint */
    initial_delay_seconds?: number;
    /** +usage=How often to check the endpoint */
    period_seconds?: number;
    /** +usage=Number of successful responses from the endpoint before container is considered healthy */
    success_threshold?: number;
    /** +usage=Time to wait for a response from the endpoint before considering it down */
    timeout_seconds?: number;
}
