// This file was auto-generated by Fern from our API Definition.

export interface HelmRepo {
    /** +value=helm-repo */
    type: "helm-repo";
    /** Helm repository URL - Needs to be a valid URL. */
    repoUrl: string;
    /**
     * FQN of the helm repo integration. If you can't find your integration here,
     * add it through the [Integrations](/integrations) page
     */
    integrationFqn?: string;
    /** The helm chart name */
    chart: string;
    /** Helm chart version */
    version: string;
}
