/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

export interface IChange {
    type: TrueFoundry.IChangeOperation;
    key: string;
    value?: Record<string, unknown>;
    oldValue?: Record<string, unknown>;
    changes?: TrueFoundry.IChange[];
}
