// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

export interface IChange {
    type: TrueFoundry.IChangeType;
    key: string;
    value?: Record<string, unknown> | null;
    oldValue?: Record<string, unknown> | null;
    changes?: TrueFoundry.IChange[] | null;
}
