/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

export interface InternalArtifactVersion {
    id: string;
    fqn: string;
    createdBySubject: TrueFoundry.Subject;
    createdAt?: Date;
    updatedAt?: Date;
    manifest: TrueFoundry.ArtifactManifest;
    usageCodeSnippet?: string;
    mlRepoId: string;
    artifactId: string;
    artifactFqn: string;
    artifactSize?: number;
}
