/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index";

/**
 * +docs=Specify whether you want to deploy a Docker image or build and deploy from source code
 * +label=Deploy a Docker image or build and deploy from source code
 * +icon=fa-solid fa-cloud-arrow-up:#21B6A8
 * +sort=200
 */
export type JobImage = TrueFoundry.Build | TrueFoundry.Image;
