// This file was auto-generated by Fern from our API Definition.

/**
 * JSON schema for structured output
 */
export interface JsonSchema {
    /** Name of the schema */
    name: string;
    /** JSON schema object defining the expected structure */
    schema: Record<string, unknown>;
}
