// This file was auto-generated by Fern from our API Definition.

export interface Jwt {
    id: string;
    subjectType: string;
    subjectId: string;
    metadata?: Record<string, unknown> | undefined;
    expiry: string;
    createdAt: string;
    updatedAt: string;
}
