// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../index.js";

export interface Jwt {
    id: string;
    subjectType: string;
    subjectId: string;
    metadata?: Record<string, unknown>;
    expiry: Date;
    tokenType: TrueFoundry.JwtTokenType;
    createdAt: Date;
    updatedAt: Date;
}
