/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * +label=Keras
 * +icon=keras
 */
export interface KerasFramework {
    /**
     * +label=Type
     * +usage=Type of the framework
     * +value=keras
     */
    type: "keras";
}
