/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

/**
 * +label=Latency-based Load Balancing
 */
export interface LatencyBasedLoadBalancing {
    /**
     * +value=latency-based-routing
     * +sort=1
     * +label=Routing Type
     */
    type: "latency-based-routing";
    /** List of targets for latency-based load balancing */
    load_balance_targets: TrueFoundry.LatencyBasedLoadBalanceTarget[];
}
