// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

export interface ListApplicationDeploymentsResponse {
    /** Array of Deployments */
    data: TrueFoundry.Deployment[];
    /** Pagination information */
    pagination: TrueFoundry.Pagination;
}
