// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../index.js";

export interface ListClustersResponse {
    /** List of clusters the caller has access to. */
    data: TrueFoundry.Cluster[];
    /** Pagination metadata. */
    pagination: TrueFoundry.Pagination;
}
