// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../index.js";

/**
 * Weight-based Target
 */
export interface LoadBalanceTarget {
    /** Target model or provider FQN */
    target: string;
    /** Relative weight for routing decisions (higher values mean more traffic) */
    weight: number;
    retryConfig?: TrueFoundry.RetryConfig;
    /** Status Codes for which the request will fallback to other targets. If the status code is not present in fallback_status_codes, it fails immediately. */
    fallbackStatusCodes?: string[];
    /** Whether this target is a fallback candidate.  If set to false, this model will not be considered as a fallback option for targets of this load-balance-rule */
    fallbackCandidate?: boolean;
    /** Optional parameters to override in the request */
    overrideParams?: Record<string, unknown>;
    headersOverride?: TrueFoundry.HeadersOverride;
    /** Optional metadata key-value pairs that must match incoming request metadata headers for this target to be considered for routing. */
    metadataMatch?: Record<string, string>;
}
