/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Log {
    /** Container Name */
    containerName?: string;
    /** Job Name */
    job_name?: string;
    /** Log Content */
    log: string;
    /** Log Stream */
    stream: string;
    /** Log Time */
    time: string;
}
