/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Query filter type for logs search
 */
export type LogsSearchFilterType = "regex" | "substring" | "ignore_case_substring";
export const LogsSearchFilterType = {
    Regex: "regex",
    Substring: "substring",
    IgnoreCaseSubstring: "ignore_case_substring",
} as const;
