/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

/**
 * MCP Server
 */
export interface McpServerIntegration {
    /** +value=integration/mcp-server/remote */
    type: "integration/mcp-server/remote";
    /** The name of the MCP Server. */
    name: string;
    /** Provide a brief description of the purpose of this MCP Server. */
    description: string;
    /** The endpoint URL for the MCP Server. The system will first try a connection using streamable-http transport on this URL. If that fails, it will attempt a connection using SSE transport on <url>/sse. */
    url: string;
    auth_data?: TrueFoundry.McpServerAuth;
    /** List of teams/users who can use this MCP server. */
    authorized_subjects?: string[];
}
