/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Static API key or token authentication via request headers. All users share the same credentials.
 */
export interface McpServerHeaderAuth {
    /** +value=header */
    type: "header";
    headers: Record<string, string>;
}
