/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

/**
 * +label=Mistral AI Model
 * +icon=mistral-ai
 */
export interface MistralAiModel {
    /** +value=integration/model/mistral-ai */
    type: "integration/model/mistral-ai";
    /**
     * +label=Display Name
     * +sort=1
     * +usage=Name to identify this Mistral AI model in the UI
     * +message=2 to 62 characters long alphanumeric word, may contain - in between, cannot start with a number
     */
    name: string;
    /**
     * +label=Model ID
     * +sort=2
     * +usage=The name of the Mistral AI model to use
     * +message=Model ID must not be empty
     */
    model_id: string;
    /**
     * +label=Model Types
     * +sort=3
     * +usage=Specify the type of the Mistral AI model
     * +uiProps={"disableAllOption": true}
     */
    model_types: TrueFoundry.ModelType[];
    cost?: TrueFoundry.ModelCostMetric;
    /**
     * +label=Access Control
     * +sort=5
     * +usage=List of subjects that are authorized to access this integration. List of user fqn in format <user_type>:<username>.
     * +uiType=Hidden
     */
    authorized_subjects?: string[];
}
