// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * MS Teams Provider Account
 */
export interface MsTeamsProviderAccount {
    /** +value=provider-account/ms-teams */
    type?: "provider-account/ms-teams" | undefined;
    /** The name of the MS Teams provider account */
    name: string;
    /** List of integrations that are associated with the MS Teams provider account */
    integrations: TrueFoundry.MsTeamsIntegrations[];
    ownedBy?: TrueFoundry.OwnedBy | undefined;
}
