// This file was auto-generated by Fern from our API Definition.

/**
 * MS Teams Webhook
 */
export interface MsTeamsWebhook {
    /** +value=ms-teams-webhook */
    type: "ms-teams-webhook";
    /** Specify the notification channel to send alerts to */
    notification_channel: string;
}
