// This file was auto-generated by Fern from our API Definition.

/**
 * MS Teams Webhook Auth
 */
export interface MsTeamsWebhookAuth {
    /** +value=auth/ms-teams-webhook */
    type?: "ms-teams-webhook" | undefined;
    /** The Microsoft Teams Incoming Webhook URL */
    webhook_url: string;
}
