/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index";

export interface MultiPartUpload {
    azure_blob_block_ids?: string[];
    finalize_signed_url: TrueFoundry.SignedUrl;
    part_signed_urls: TrueFoundry.SignedUrl[];
    s3_compatible_upload_id?: string;
    storage_provider: TrueFoundry.MultiPartUploadStorageProvider;
}
