// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../index.js";

/**
 * Describes the configuration for the output NATS worker
 */
export interface NatsOutputConfig {
    /** +value=nats */
    type: "nats";
    /** Output NATS URL */
    natsUrl: string;
    /** Root subject of output NATS */
    rootSubject: string;
    auth?: TrueFoundry.NatsUserPasswordAuth;
}
