/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

/**
 * +docs=Describes the configuration for the input NATS worker
 * +label=NATS
 */
export interface NatsInputConfig {
    /** +value=nats */
    type: "nats";
    /**
     * +label=NATS URL
     * +usage=Input NATS URL
     * +sort=1
     */
    natsUrl: string;
    /**
     * +label=Stream Name
     * +usage=Name of the NATS stream
     * +sort=2
     */
    streamName: string;
    /**
     * +label=Root Subject
     * +usage=Root subject of input NATS
     * +message=Input NATS root subject should only contain alphanumeric letters, dashes(-), and periods(.)
     * +sort=3
     */
    rootSubject: string;
    /**
     * +label=Consumer Name
     * +usage=Consumer name of input NATS
     * +message=Consumer name should only contain alphanumeric letters, dashes(-), and underscores(_)
     * +sort=4
     */
    consumerName: string;
    /**
     * +label=Wait Time Seconds
     * +usage=Wait timeout for long polling.
     * +sort=5
     */
    waitTimeSeconds: number;
    /**
     * +label=NATS metrics URL
     * +usage=URL for the NATS metrics endpoint. It is compulsory if you want to use NATS autoscaling.
     * +message=NATS Metrics URL should be a valid HTTP/HTTPS URL
     */
    natsMetricsUrl?: string;
    auth?: TrueFoundry.NatsUserPasswordAuth;
}
