// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * Noma Security
 */
export interface NomaSecurityGuardrailConfig {
    /** The name of the Guardrail Config. */
    name: string;
    /** Optional description for this Guardrail Config. */
    description?: string;
    /**
     * +uiType=Hidden
     * +value=integration/guardrail-config/noma-security
     */
    type: "integration/guardrail-config/noma-security";
    authData: TrueFoundry.NomaSecurityApiKeyAuth;
    /**
     * Validate blocks policy denials. Mutate also applies complete masked request or response payloads returned by Noma.
     * Validate guardrails are run in parallel while mutate guardrails are run sequentially.
     */
    operation: TrueFoundry.NomaSecurityGuardrailConfigOperation;
    /** Execution order for mutate guardrails. Lower values run first. Only applicable when operation is mutate. */
    priority?: number;
    enforcingStrategy: TrueFoundry.EnforcingStrategy;
    /**
     * +uiType=Ignore
     * +uiProps={"forwardJsonKey": true}
     */
    config: TrueFoundry.NomaSecurityGuardrailConfigConfig;
}
