// This file was auto-generated by Fern from our API Definition.

export interface OpenAiModerationsGuardrailConfigCategoryThresholdsValueHarassment {
    harassment: number;
    sexual: number;
    violence: number;
}
