// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * +uiType=Ignore
 * +uiProps={"forwardJsonKey": true}
 */
export interface OpenAiModerationsGuardrailConfigConfig {
    /** The model to use for the OpenAI Moderation API. */
    model: string;
    /** Optional custom base URL for OpenAI API. If not provided, the default base URL will be used. */
    base_url?: string;
    category_thresholds?: Record<string, TrueFoundry.OpenAiModerationsGuardrailConfigConfigCategoryThresholdsValue>;
}
