// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../index.js";

/**
 * HTTP Configuration
 */
export interface OtelTracesExporterHttpConfig extends TrueFoundry.OtelExporterHttpConfigBase, TrueFoundry.OtelTracesExporterCommonConfig {
    /** Configuration type */
    type: "http";
}
