// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * +uiType=Ignore
 * +uiProps={"forwardJsonKey": true}
 */
export interface PaloAltoPrismaAirsGuardrailConfigConfig {
    /** Optional override for the base URL for Palo Alto Prisma AIRS. Defaults to https://service.api.aisecurity.paloaltonetworks.com/v1/ if not provided. */
    base_url?: string;
    /** The profile name associated with this Guardrail Config. */
    profile_name: string;
    /** Execution mode for the guardrail. Sync waits for the guardrail check to complete before proceeding. Async triggers the check without waiting. Defaults to sync. */
    mode?: TrueFoundry.PaloAltoPrismaAirsGuardrailConfigConfigMode;
}
