// This file was auto-generated by Fern from our API Definition.

export interface PaloAltoPrismaAirsKeyAuth {
    /** +value=api-key */
    type?: "api-key" | undefined;
    /** API key for the Palo Alto  Prisma AIRS account */
    api_key: string;
}
