// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

export interface PerThousandTokensCostMetric {
    /** +value=per_1000_tokens */
    metric: string;
    value: TrueFoundry.InputOutputBasedCostMetricValue;
}
