// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

export interface PerThousandEmbeddingTokensCostMetric {
    /** +value=per_1000_embedding_tokens */
    metric: string;
    value: TrueFoundry.NonNegativeFloat;
}
