/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * +usage=Use pip to install requirements files and packages
 * +label=Pip
 */
export interface Pip {
    /** +value=pip */
    type: "pip";
    /**
     * +label=Path to requirements
     * +usage=Path to `requirements.txt` relative to `Path to build context`
     */
    requirements_path?: string;
    /**
     * +label=Pip packages to install
     * +usage=Define pip package requirements.
     * In Python/YAML E.g. ["fastapi>=0.90,<1.0", "uvicorn"]
     * +placeholder=Enter a pip package name E.g. fastapi>=0.90,<1.0
     */
    pip_packages?: string[];
}
