/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Use pip to install requirements files and packages
 */
export interface Pip {
    /** +value=pip */
    type: "pip";
    /** Path to `requirements.txt` relative to `Path to build context` */
    requirements_path?: string;
    /**
     * Define pip package requirements.
     * In Python/YAML E.g. ["fastapi>=0.90,<1.0", "uvicorn"]
     */
    pip_packages?: string[];
}
