// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * Authentication method for inbound traffic
 */
export type PortAuth = TrueFoundry.BasicAuthCreds | TrueFoundry.JwtAuthConfig | TrueFoundry.TrueFoundryInteractiveLogin;
