/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

export interface PriorityBasedLoadBalanceTarget {
    /**
     * +usage=Target model or provider FQN
     * +uiProps={"integrationType":"model", "valuePattern": "${providerAccount.name}/${manifest.name}"}
     * +sort=1
     * +label=Target
     */
    target: string;
    /**
     * +usage=Priority for the target, Lower the number, higher the priority (0 is the highest priority)
     * +uiProps={"descriptionInline":true}
     * +sort=2
     * +label=Priority
     */
    priority: number;
    sla_cutoff?: TrueFoundry.SlaCutoff;
    retry_config?: TrueFoundry.RetryConfig;
    /**
     * +usage=Status Codes for which the request will fallback to other targets. If the status code is not present in fallback_status_codes, it fails immediately.
     * +uiProps={"descriptionInline":true}
     * +sort=5
     * +label=Fallback Status Codes
     */
    fallback_status_codes?: string[];
    /**
     * +usage=Whether this target is a fallback candidate.  If set to false, this model will not be considered as a fallback option for targets of this load-balance-rule
     * +uiProps={"descriptionInline":true}
     * +sort=6
     * +label=Fallback Candidate
     */
    fallback_candidate?: boolean;
    /**
     * +usage=Optional parameters to override in the request
     * +uiProps={"descriptionInline":true}
     * +sort=7
     * +label=Override Parameters
     */
    override_params?: Record<string, unknown>;
}
