// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../index.js";

export interface PromptVersion {
    /** Timestamp when the prompt version was created. */
    createdAt?: Date;
    /** Timestamp when the prompt version was last updated. */
    updatedAt?: Date;
    /** Manifest describing the prompt version. */
    manifest: TrueFoundry.ChatPromptManifest;
    /** Unique identifier of the prompt version. */
    id: string;
    /** Fully Qualified Name uniquely identifying the prompt version. */
    fqn: string;
    /** Subject (user, team, or service account) that created the prompt version. */
    createdBySubject: TrueFoundry.Subject;
    /** Identifier of the ML Repo the prompt version belongs to. */
    mlRepoId: string;
    /** Code snippet showing how to use the prompt version. */
    usageCodeSnippet?: string;
    /** Code snippets showing how to use the prompt version. */
    usageCodeSnippets?: TrueFoundry.UsageCodeSnippet[];
    /** Tags associated with the prompt version. */
    tags?: string[];
    /** Identifier of the prompt this version belongs to. */
    promptId: string;
}
