// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../index.js";

/**
 * Redaction
 */
export interface Redaction {
    /** Predefined patterns to redact from the logged copy. */
    presets?: TrueFoundry.PresetRegexPatternEnum[];
    /** Custom patterns to redact from the logged copy. */
    customPatterns?: TrueFoundry.CustomRegexPattern[];
}
