// This file was auto-generated by Fern from our API Definition.

/**
 * When the key is present, its value must match the regex pattern.
 */
export interface RegexConstraint {
    /** +value=regex */
    constraint: "regex";
    /** Add the regex pattern to compare against. */
    regex: string;
}
