// This file was auto-generated by Fern from our API Definition.

/**
 * Fetch the OpenAPI specification from a remote HTTP/HTTPS endpoint.
 */
export interface RemoteSpecSource {
    /** +value=remote */
    type: "remote";
    /** URL to fetch the OpenAPI specification (JSON or YAML format). */
    url: string;
}
