/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * +docs=Describes that we are using code stored in a remote respository to build our image
 * +label=S3
 * +icon=fa-brands fa-aws:black
 * +sort=200
 */
export interface RemoteSource {
    /**
     * +docs=Remote repository URI
     * +label=Remote URI
     */
    remote_uri: string;
    /** +value=remote */
    type: "remote";
}
