// This file was auto-generated by Fern from our API Definition.

export interface RolePermissions {
    /** Type of resource this role can perform actions on */
    resourceType: string;
    /** Actions this role can perform on the resource */
    actions: string[];
}
