/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

export interface SklearnFramework {
    /** Type of the framework */
    type: "sklearn";
    /** Relative path to the model file in the model version contents */
    model_filepath?: string;
    serialization_format?: TrueFoundry.SklearnSerializationFormat;
    model_schema?: TrueFoundry.SklearnModelSchema;
}
