/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index";

/**
 * +label=Slack Webhook Integration
 * +icon=https://assets.production.truefoundry.com/slack.svg
 */
export interface SlackWebhookIntegration {
    /** +value=integration/notification-channel/slack-webhook */
    type: "integration/notification-channel/slack-webhook";
    /**
     * +label=Display Name
     * +usage=The name of the integration that will be displayed in the TrueFoundry UI.
     * +uiProps={"disableEdit":false}
     * +sort=100
     * +message=3 to 32 lower case characters long alphanumeric word, may contain - in between, cannot start with a number
     */
    name: string;
    auth_data: TrueFoundry.SlackWebhookAuth;
    /**
     * +label=Access Control
     * +usage=List of subjects that are authorized to access this integration. List of user fqn in format <user_type>:<username>.
     * +sort=10005
     * +uiType=AuthorizedSubjects
     */
    authorized_subjects?: string[];
}
