// This file was auto-generated by Fern from our API Definition.

export interface SparkJobTriggerInput {
    /** Main Class for Spark Job */
    mainClass?: string | null;
    /** Main Application File for Spark Job */
    mainApplicationFile?: string | null;
    /** Arguments to pass to the main application file */
    arguments?: string | null;
}
