/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index";

/**
 * +docs=Describes that we are building a new image based on the spec
 * +label=Build a new image
 * +icon=fa-brands fa-docker:#0db7ed
 * TODO (gw): Fix sorting for this such that it looks similar to SparkImage
 */
export interface SparkImageBuild {
    /**
     * TODO (gw): The following is a hack till the uiType GitSelect is fixed fron frontend
     * +label=Fetch source code
     * +sort=1003
     */
    build_source: TrueFoundry.SparkImageBuildBuildSource;
    build_spec: TrueFoundry.SparkBuild;
    /**
     * +docs=FQN of the container registry. You can the FQN of your desired container registry (or add one)
     * in the  Integrations page[Integrations](https://app.truefoundry.tech/integrations?tab=docker-registry) page
     * +label=Docker Registry
     * +usage=FQN of the container registry. If you can't find your registry here,
     * add it through the [Integrations](/integrations?tab=docker-registry) page
     * +sort=1002
     */
    docker_registry?: string;
    /** +value=spark-image-build */
    type: "spark-image-build";
}
