/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

/**
 * +docs=Describes the configuration for the input SQS worker
 * +label=SQS
 */
export interface SqsInputConfig {
    /** +value=sqs */
    type: "sqs";
    /**
     * +label=Queue URL
     * +usage=AWS SQS Queue URL of Subscriber
     * +sort=1
     */
    queueUrl: string;
    /**
     * +label=Region Name
     * +usage=AWS Region Name
     * +sort=2
     */
    regionName: string;
    /**
     * +label=Visibility Timeout (seconds)
     * +usage=A period during which Amazon SQS prevents all consumers from receiving and processing the message. If one message takes 5 seconds to process, you can set this number to 7 or any number higher than 5. This will ensure that while the message is being processed, it will not be available to other replicas. For more information, see [here](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html)
     * +sort=3
     */
    visibilityTimeout: number;
    /**
     * +label=Wait Time Seconds
     * +usage=Wait timeout for long polling. For more information, see [here](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-short-and-long-polling.html)
     */
    waitTimeSeconds: number;
    auth: TrueFoundry.AwsAccessKeyAuth;
}
