/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * +label=StatsModels
 * +icon=statsmodel
 */
export interface StatsModelsFramework {
    /**
     * +label=Type
     * +usage=Type of the framework
     * +value=statsmodels
     */
    type: "statsmodels";
}
