// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * Stdio MCP server configuration.
 */
export interface StdioMcpServerManifest {
    /** The name of the MCP Server. */
    name: string;
    /** Provide a brief description of the purpose of this MCP Server. */
    description: string;
    /** Users and Teams that have access to this MCP Server */
    collaborators: TrueFoundry.Collaborator[];
    /**
     * +value=mcp-server/stdio
     * +sort=400
     */
    type: "mcp-server/stdio";
    /** Executable to run for the stdio MCP server process. */
    command: string;
    /** Arguments passed to the stdio MCP server command. */
    args?: string[] | undefined;
    auth_data?: TrueFoundry.McpServerEnvAuth | undefined;
    ownedBy?: TrueFoundry.OwnedBy | undefined;
    /** Key-value pairs to categorize this MCP Server (e.g., by owner or environment). */
    tags?: Record<string, unknown> | undefined;
}
