// This file was auto-generated by Fern from our API Definition.

export const SubjectType = {
    User: "user",
    Team: "team",
    Serviceaccount: "serviceaccount",
    Virtualaccount: "virtualaccount",
    ExternalIdentity: "external-identity",
    Role: "role",
} as const;
export type SubjectType = (typeof SubjectType)[keyof typeof SubjectType];
