/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

export interface SyncVirtualAccountTokenResponse {
    /** Sync status including timestamp and error (if any) */
    syncTokenInSecretStoreInfo: TrueFoundry.SyncTokenInSecretStoreInfo;
}
