// This file was auto-generated by Fern from our API Definition.

/**
 * Describes the configuration for the python build for a task
 */
export interface TaskPythonBuild {
    /** +value=task-python-build */
    type: "task-python-build";
    /**
     * FQN of the container registry. If you can't find your registry here,
     * add it through the [Integrations](/integrations?tab=docker-registry) page
     */
    docker_registry?: string;
    /** Python version to run your application. Should be one of the tags listed on [Official Python Docker Page](https://hub.docker.com/_/python) */
    python_version?: string;
    /**
     * Path to `requirements.txt` relative to
     * `Path to build context`
     */
    requirements_path?: string;
    /**
     * Define pip package requirements.
     * In Python/YAML E.g. ["fastapi>=0.90,<1.0", "uvicorn"]
     */
    pip_packages?: string[];
    /**
     * Debian packages to install via `apt get`.
     * In Python/YAML E.g. ["git", "ffmpeg", "htop"]
     */
    apt_packages?: string[];
    /**
     * Version of CUDA Toolkit and CUDNN to install in the image
     * These combinations are based off of publically available docker images on docker hub
     * You can also specify a valid tag of the form {cuda_version_number}-cudnn{cudnn_version_number}-{runtime|devel}-ubuntu{ubuntu_version}
     * Refer https://hub.docker.com/r/nvidia/cuda/tags for valid set of values
     * Note: We use deadsnakes ubuntu ppa to add Python that currently supports only Ubuntu 18.04, 20.04 and 22.04
     */
    cuda_version?: string;
}
