/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Names of the owners that own the team
 */
export interface TeamOwnedBy {
    /** The name of the account that owns the team */
    account: string;
}
