// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../index.js";

export interface TeamDto {
    /** System-generated team ID. */
    id: string;
    /** A short description of the team. */
    description: string;
    /** Tenant the team belongs to. */
    tenantName: string;
    /** System-generated ID of the account that owns the team. */
    accountId: string;
    /** The subject (user or service account) that created the team. */
    createdBySubject: TrueFoundry.Subject;
    /** Email addresses of team members. */
    members?: string[];
    /** Timestamp when the team was created. */
    createdAt: Date;
    /** Timestamp when the team was last updated. */
    updatedAt: Date;
    /** The team manifest defining name, members, managers, and ownership. */
    manifest: TrueFoundry.TeamManifest;
    /** SCIM-related metadata for the team. */
    metadata?: TrueFoundry.TeamMetadata;
    /** Whether the team can be edited. SCIM-managed teams may be non-editable. */
    isEditable: boolean;
    /** Role names assigned to the team. */
    roles?: string[];
    /** Up to 5 team member emails, sourced from cache. Absent when the cache is unavailable. */
    topMembers?: string[];
    /** Up to 5 team manager emails, sourced from cache. Absent when the cache is unavailable. */
    topManagers?: string[];
    /** Total number of team members, sourced from cache. Absent when the cache is unavailable. */
    totalMemberCount?: number;
    /** Total number of team managers, sourced from cache. Absent when the cache is unavailable. */
    totalManagerCount?: number;
}
