/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * +label=Together AI API Key Auth
 * +icon=together-ai
 */
export interface TogetherAiKeyAuth {
    /** +value=api-key */
    type: "api-key";
    /** Your Together AI API key for authentication */
    api_key: string;
}
