/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TracingProjectManifest {
    type: "tracing-project";
    /**
     * +label=Name
     * +usage=Name of the tracing project
     * +message=The name should start with lowercase alphabets  and can contain alphanumeric and can include '-' in between
     */
    name: string;
    /**
     * +label=ML Repo
     * +usage=Name of the ML Repo
     * +uiType=Hidden
     */
    ml_repo?: string;
}
