/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index";

export interface TracingProject {
    created_at: string;
    created_by_subject: TrueFoundry.Subject;
    fqn: string;
    id: string;
    manifest: TrueFoundry.TracingProjectManifest;
    ml_repo_id: number;
    name: string;
    updated_at: string;
}
