// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

export interface TracingProject {
    id?: string | null;
    fqn: string;
    createdBySubject: TrueFoundry.Subject;
    tenantName: string;
    accountId: string;
    manifest: Record<string, unknown>;
    createdAt?: Date | null;
    updatedAt?: Date | null;
    storageType: string;
    storageRoot: string;
    storageIntegrationId?: string | null;
}
