/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Tracing Project manifest.
 */
export interface TracingProjectManifest {
    /** Name of the ML Repo */
    ml_repo?: string;
    /** Name of the tracing project */
    name: string;
    type: "tracing-project";
}
