// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../index.js";

export interface TrueFoundryAgentConfig {
    /** Maximum number of iterations for the agent */
    iterationLimit?: number;
    sandbox?: TrueFoundry.TrueFoundryAgentSandboxConfig;
    dynamicSubAgents?: TrueFoundry.TrueFoundryAgentDynamicSubAgentsConfig;
    contextManagement?: TrueFoundry.TrueFoundryAgentContextManagementConfig;
    generativeUi?: TrueFoundry.TrueFoundryAgentGenerativeUiConfig;
    askUserQuestions?: TrueFoundry.TrueFoundryAgentAskUserQuestionsConfig;
}
