/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index";

/**
 * manifest of the resource to be deleted
 */
export type TrueFoundryDeleteRequestManifest =
    | TrueFoundry.MlRepoManifest
    | TrueFoundry.ArtifactManifest
    | TrueFoundry.ModelManifest
    | TrueFoundry.ChatPromptManifest
    | TrueFoundry.DataDirectory
    | TrueFoundry.Service
    | TrueFoundry.ApplicationSet
    | TrueFoundry.ProviderAccounts
    | TrueFoundry.ClusterManifest
    | TrueFoundry.WorkspaceManifest
    | TrueFoundry.Job
    | TrueFoundry.Helm
    | TrueFoundry.Volume
    | TrueFoundry.Notebook
    | TrueFoundry.RStudio
    | TrueFoundry.Workflow
    | TrueFoundry.AsyncService
    | TrueFoundry.SshServer
    | TrueFoundry.SparkJob
    | TrueFoundry.GatewayConfig
    | TrueFoundry.TeamManifest
    | TrueFoundry.PolicyManifest
    | TrueFoundry.AlertConfig
    | TrueFoundry.VirtualAccountManifest
    | TrueFoundry.CommonToolsSettings
    | TrueFoundry.AiFeaturesSettings;
