// This file was auto-generated by Fern from our API Definition.

export interface TrueFoundryAgentSkill {
    /** Fully qualified name of the agent skill */
    fqn: string;
    /** When true, the skill's markdown content is loaded into the agent context before the first turn */
    eager?: boolean | undefined;
}
