/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

/**
 * +label=TTL
 * +icon=puzzle-piece
 */
export interface TtlProviderAccount {
    /** +value=provider-account/ttl */
    type: "provider-account/ttl";
    /**
     * +uiProps={"disableEdit":true}
     * +label=Name
     * +usage=The name of the provider account.
     * +sort=100
     * +message=3 to 32 lower case characters long alphanumeric word, may contain - in between, cannot start with a number
     */
    name: string;
    /**
     * +label=Integrations
     * +usage=List of integrations that are associated with the provider account.
     * +sort=400
     * +uiType=IntegrationsGroup
     */
    integrations: TrueFoundry.TtlIntegrations[];
}
