// This file was auto-generated by Fern from our API Definition.

export interface UsageCodeSnippet {
    display_name: string;
    language: string;
    libraries?: string[] | undefined;
    code: string;
    icon?: string | undefined;
}
