/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Use `uv` to setup env.
 * Your build context root must contain `pyproject.toml` and `uv.lock`
 */
export interface Uv {
    /** +value=uv */
    type: "uv";
    /** UV version to use */
    uv_version?: string;
    /** Sync options to pass to uv command */
    sync_options?: string;
}
