/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

/**
 * Vertex Model
 */
export interface VertexModel {
    /** Display Name - 2 to 62 characters long alphanumeric word, may contain - or . in between, cannot start with a number */
    name: string;
    /** +sort=2 */
    model_id: string;
    /** +value=integration/model/gcp/vertex */
    type: "integration/model/gcp/vertex";
    /** Specify the type of the model */
    model_types: TrueFoundry.ModelType[];
    region?: TrueFoundry.GcpRegion;
    cost?: TrueFoundry.ModelCostMetric;
    /** List of subjects that are authorized to access this integration. List of user fqn in format <user_type>:<username>. */
    authorized_subjects?: string[];
}
