/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

/**
 * +label=Virtual MCP Server Source
 */
export interface VirtualMcpServerSource {
    /** Name of the source MCP server within this group (use {provider_account_name}/{integration_name} format). */
    name: string;
    /** List of tools to enable from this source server. Leave empty to enable all tools. */
    enabled_tools?: string[];
    auth_data?: TrueFoundry.McpServerHeaderOverrideAuth;
}
