// This file was auto-generated by Fern from our API Definition.

/**
 * Wafer API Key Auth
 */
export interface WaferApiKeyAuth {
    /** +value=api-key */
    type?: "api-key" | undefined;
    /** The API key for Wafer Serverless authentication */
    api_key: string;
}
