// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../index.js";

/**
 * Wafer Model
 */
export interface WaferModel {
    /** +value=integration/model/wafer */
    type: "integration/model/wafer";
    /** A descriptive name to identify this model integration in the UI */
    name: string;
    /** The Wafer model identifier (e.g., deepseek-v4-pro, deepseek-v4-flash). See https://docs.wafer.ai/serverless for the public catalog. */
    modelId: string;
    /** Specify the type of the Wafer model */
    modelTypes: TrueFoundry.ModelType[];
    cost?: TrueFoundry.ModelCostMetric;
    /** List of subjects that are authorized to access this integration. List of user fqn in format <user_type>:<username>. */
    authorizedSubjects?: string[];
}
