// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * Webhook Integration
 */
export interface WebhookIntegration {
    /** +value=integration/gateway-request-logger/webhook */
    type: "integration/gateway-request-logger/webhook";
    /** The name of the integration that will be displayed in the TrueFoundry UI. */
    name: string;
    /** The URL of the webhook endpoint */
    webhook_url: string;
    /** Authentication configuration for the webhook */
    auth_data?: TrueFoundry.WebhookIntegrationAuthData;
    /** List of subjects that are authorized to access this integration. List of user fqn in format <user_type>:<username>. */
    authorized_subjects?: string[];
}
