/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

/**
 * +label=Webhook Integration
 * +icon=https://assets.production.truefoundry.com/webhook.svg
 */
export interface WebhookIntegration {
    /** +value=integration/gateway-request-logger/webhook */
    type: "integration/gateway-request-logger/webhook";
    /**
     * +label=Display Name
     * +uiProps={"disableEdit":true}
     * +usage=The name of the integration that will be displayed in the TrueFoundry UI.
     * +sort=100
     * +message=3 to 32 lower case characters long alphanumeric word, may contain - in between, cannot start with a number
     */
    name: string;
    /**
     * +label=Webhook URL
     * +usage=The URL of the webhook endpoint
     * +sort=200
     */
    webhook_url: string;
    /**
     * +label=Authentication
     * +usage=Authentication configuration for the webhook
     * +sort=300
     */
    auth_data?: WebhookIntegration.AuthData;
    /**
     * +label=Access Control
     * +usage=List of subjects that are authorized to access this integration. List of user fqn in format <user_type>:<username>.
     * +sort=10005
     * +uiType=AuthorizedSubjects
     */
    authorized_subjects?: string[];
}

export namespace WebhookIntegration {
    /**
     * +label=Authentication
     * +usage=Authentication configuration for the webhook
     * +sort=300
     */
    export type AuthData = TrueFoundry.WebhookBasicAuth | TrueFoundry.WebhookBearerAuth;
}
