/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WebhookBearerAuth {
    /** +value=auth/webhook-bearer */
    type: "webhook-bearer";
    /** Bearer token for authentication */
    token: string;
    /** Prefix for the token */
    prefix: string;
}
