// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

/**
 * Authentication configuration for the webhook
 */
export type WebhookIntegrationAuthData = TrueFoundry.WebhookBasicAuth | TrueFoundry.WebhookBearerAuth;
