// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../index.js";

export interface Workspace {
    id: string;
    fqn: string;
    name: string;
    tenantName: string;
    clusterId: string;
    createdBySubject: TrueFoundry.Subject;
    createdAt: string;
    updatedAt: string;
    environmentId?: string;
    manifest: TrueFoundry.WorkspaceManifest;
    accountId?: string;
    isSystemWs?: boolean;
    createdBy?: string;
}
