/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index";

/**
 * +label=Output Config
 * +usage=Output Config
 * +sort=2
 */
export type WorkerConfigOutputConfig =
    | TrueFoundry.SqsOutputConfig
    | TrueFoundry.NatsOutputConfig
    | TrueFoundry.CoreNatsOutputConfig
    | TrueFoundry.KafkaOutputConfig
    | TrueFoundry.AmqpOutputConfig;
