/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index";

export interface Workspace {
    id: string;
    fqn: string;
    name: string;
    tenantName: string;
    clusterId: string;
    cluster: TrueFoundry.Cluster;
    createdBySubject: TrueFoundry.Subject;
    metadata: TrueFoundry.WorkspaceMetadata;
    createdAt: string;
    updatedAt: string;
    k8sUid?: string;
    environmentId?: string;
    serviceAccountId?: string;
    manifest: TrueFoundry.WorkspaceManifest;
    isSystemWs?: boolean;
    createdBy?: string;
}
