/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../index.js";

export interface XgBoostFramework {
    /** Type of the framework */
    type: "xgboost";
    serialization_format?: TrueFoundry.XgBoostSerializationFormat;
    /** Relative path to the model file in the model version contents */
    model_filepath?: string;
    model_schema?: TrueFoundry.XgBoostModelSchema;
}
