// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const CheckExistsVirtualAccountsResponse: core.serialization.ObjectSchema<
    serializers.CheckExistsVirtualAccountsResponse.Raw,
    TrueFoundry.CheckExistsVirtualAccountsResponse
> = core.serialization.object({
    exists: core.serialization.boolean(),
});

export declare namespace CheckExistsVirtualAccountsResponse {
    export interface Raw {
        exists: boolean;
    }
}
