// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const TeamsListRequestType: core.serialization.Schema<serializers.TeamsListRequestType.Raw, TrueFoundry.TeamsListRequestType> = core.serialization.enum_(["team", "sso-team"]);

export declare namespace TeamsListRequestType {
    export type Raw = "team" | "sso-team";
}
