// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         limit: 10,
 *         offset: 0,
 *         clusterId: "clusterId",
 *         name: "name",
 *         fqn: "fqn"
 *     }
 */
export interface WorkspacesListRequest {
    /** Number of items per page */
    limit?: number;
    /** Number of items to skip */
    offset?: number;
    /** ClusterId of the Cluster */
    clusterId?: string;
    /** Workspace Name */
    name?: string;
    /** Workspace FQN */
    fqn?: string;
}
