/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SvcMcpMetricsGetMcpMetricsChartsRequestPage = "mcpserver" | "tool";
export const SvcMcpMetricsGetMcpMetricsChartsRequestPage = {
    Mcpserver: "mcpserver",
    Tool: "tool",
} as const;
