// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as errors from "../../../../errors/index.js";
import * as TrueFoundry from "../../../index.js";

export declare namespace Alerts {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Alerts {
    protected readonly _options: Alerts.Options;

    constructor(_options: Alerts.Options) {
        this._options = _options;
    }

    /**
     * Get alerts for a given application or cluster filtered by start and end timestamp
     *
     * @param {TrueFoundry.AlertsListRequest} request
     * @param {Alerts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundry.BadRequestError}
     * @throws {@link TrueFoundry.ForbiddenError}
     *
     * @example
     *     await client.alerts.list({
     *         startTs: "startTs",
     *         endTs: "endTs",
     *         clusterId: "clusterId",
     *         applicationId: "applicationId",
     *         alertStatus: "firing"
     *     })
     */
    public list(
        request: TrueFoundry.AlertsListRequest = {},
        requestOptions?: Alerts.RequestOptions,
    ): core.HttpResponsePromise<TrueFoundry.GetAlertsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: TrueFoundry.AlertsListRequest = {},
        requestOptions?: Alerts.RequestOptions,
    ): Promise<core.WithRawResponse<TrueFoundry.GetAlertsResponse>> {
        const { startTs, endTs, clusterId, applicationId, alertStatus } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (startTs != null) {
            _queryParams.startTs = startTs;
        }

        if (endTs != null) {
            _queryParams.endTs = endTs;
        }

        if (clusterId != null) {
            _queryParams.clusterId = clusterId;
        }

        if (applicationId != null) {
            _queryParams.applicationId = applicationId;
        }

        if (alertStatus != null) {
            _queryParams.alertStatus = alertStatus;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "api/svc/v1/alerts",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as TrueFoundry.GetAlertsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TrueFoundry.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new TrueFoundry.ForbiddenError(
                        _response.error.body as TrueFoundry.HttpError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueFoundryError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TrueFoundryError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TrueFoundryTimeoutError("Timeout exceeded when calling GET /api/svc/v1/alerts.");
            case "unknown":
                throw new errors.TrueFoundryError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        const bearer = (await core.Supplier.get(this._options.apiKey)) ?? process?.env.TFY_API_KEY;
        if (bearer == null) {
            throw new errors.TrueFoundryError({
                message:
                    "Please specify a bearer by either passing it in to the constructor or initializing a TFY_API_KEY environment variable",
            });
        }

        return `Bearer ${bearer}`;
    }
}
