/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ToolVersionsListRequestVersion = "latest";
export const ToolVersionsListRequestVersion = {
    Latest: "latest",
} as const;
