/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index.js";
import * as TrueFoundry from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import { ModelManifest } from "../../../../types/ModelManifest.js";

export const ApplyModelRequest: core.serialization.Schema<
    serializers.ApplyModelRequest.Raw,
    TrueFoundry.ApplyModelRequest
> = core.serialization.object({
    manifest: ModelManifest,
});

export declare namespace ApplyModelRequest {
    export interface Raw {
        manifest: ModelManifest.Raw;
    }
}
