/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TrueFoundry from "../../../../index";

/**
 * @example
 *     {
 *         manifest: {
 *             messages: [{
 *                     content: "content",
 *                     role: "system"
 *                 }],
 *             metadata: {
 *                 "key": "value"
 *             },
 *             ml_repo: "ml_repo",
 *             name: "name",
 *             type: "chat_prompt"
 *         }
 *     }
 */
export interface ApplyPromptRequest {
    manifest: TrueFoundry.ChatPromptManifest;
}
