// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { AddonComponentName } from "./AddonComponentName.js";
import { AddOnComponentSource } from "./AddOnComponentSource.js";
import { AddonComponentStatus } from "./AddonComponentStatus.js";
import { ClusterType } from "./ClusterType.js";
import { Recommendation } from "./Recommendation.js";
import { UpgradeData } from "./UpgradeData.js";

export const AddonComponent: core.serialization.ObjectSchema<serializers.AddonComponent.Raw, TrueFoundry.AddonComponent> = core.serialization.object({
        "name": AddonComponentName,
        "appName": core.serialization.string().optionalNullable(),
        "namespace": core.serialization.string().optionalNullable(),
        "applicationId": core.serialization.string().optionalNullable(),
        "description": core.serialization.string().optionalNullable(),
        "path": core.serialization.string().optionalNullable(),
        "addonFolder": core.serialization.string().optionalNullable(),
        "installed": core.serialization.boolean().optionalNullable(),
        "status": AddonComponentStatus.optionalNullable(),
        "version": core.serialization.string().optionalNullable(),
        "manifest": core.serialization.record(core.serialization.string(), core.serialization.unknown()).optionalNullable(),
        "installationSource": core.serialization.string().optionalNullable(),
        "unsupportedClusterTypes": core.serialization.list(ClusterType).optionalNullable(),
        "required": core.serialization.boolean().optionalNullable(),
        "knownCrDs": core.serialization.property("knownCRDs", core.serialization.list(core.serialization.string()).optionalNullable()),
        "source": AddOnComponentSource.optionalNullable(),
        "upgrades": UpgradeData.optionalNullable(),
        "labels": core.serialization.list(core.serialization.string()).optionalNullable(),
        "recommendations": core.serialization.list(Recommendation).optionalNullable(),
        "workspaceId": core.serialization.string().optionalNullable(),
        "metadata": core.serialization.record(core.serialization.string(), core.serialization.unknown()).optionalNullable()
    });

export declare namespace AddonComponent {
    export interface Raw {
        name: AddonComponentName.Raw;
        appName?: (string | null | undefined) | null;
        namespace?: (string | null | undefined) | null;
        applicationId?: (string | null | undefined) | null;
        description?: (string | null | undefined) | null;
        path?: (string | null | undefined) | null;
        addonFolder?: (string | null | undefined) | null;
        installed?: (boolean | null | undefined) | null;
        status?: (AddonComponentStatus.Raw | null | undefined) | null;
        version?: (string | null | undefined) | null;
        manifest?: (Record<string, unknown> | null | undefined) | null;
        installationSource?: (string | null | undefined) | null;
        unsupportedClusterTypes?: (ClusterType.Raw[] | null | undefined) | null;
        required?: (boolean | null | undefined) | null;
        knownCRDs?: (string[] | null | undefined) | null;
        source?: (AddOnComponentSource.Raw | null | undefined) | null;
        upgrades?: (UpgradeData.Raw | null | undefined) | null;
        labels?: (string[] | null | undefined) | null;
        recommendations?: (Recommendation.Raw[] | null | undefined) | null;
        workspaceId?: (string | null | undefined) | null;
        metadata?: (Record<string, unknown> | null | undefined) | null;
    }
}
