// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentIdentitySecretStoreConfig: core.serialization.ObjectSchema<
    serializers.AgentIdentitySecretStoreConfig.Raw,
    TrueFoundry.AgentIdentitySecretStoreConfig
> = core.serialization.object({
    integrationFqn: core.serialization.property("integration_fqn", core.serialization.string()),
    secretPath: core.serialization.property("secret_path", core.serialization.string()),
});

export declare namespace AgentIdentitySecretStoreConfig {
    export interface Raw {
        integration_fqn: string;
        secret_path: string;
    }
}
