// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { AgentChannelAgent } from "./AgentChannelAgent.js";
import { AgentChannelConfig } from "./AgentChannelConfig.js";

export const AgentChannelManifest: core.serialization.ObjectSchema<serializers.AgentChannelManifest.Raw, TrueFoundry.AgentChannelManifest> = core.serialization.object({
        "type": core.serialization.stringLiteral("agent-channel"),
        "name": core.serialization.string(),
        "agent": AgentChannelAgent,
        "channel": AgentChannelConfig
    });

export declare namespace AgentChannelManifest {
    export interface Raw {
        type: "agent-channel";
        name: string;
        agent: AgentChannelAgent.Raw;
        channel: AgentChannelConfig.Raw;
    }
}
