/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";

export const AiFeaturesSettings: core.serialization.ObjectSchema<
    serializers.AiFeaturesSettings.Raw,
    TrueFoundry.AiFeaturesSettings
> = core.serialization.object({
    type: core.serialization.stringLiteral("settings/ai-features"),
    enabled: core.serialization.boolean(),
    ai_provider: core.serialization.stringLiteral("truefoundry"),
});

export declare namespace AiFeaturesSettings {
    export interface Raw {
        type: "settings/ai-features";
        enabled: boolean;
        ai_provider: "truefoundry";
    }
}
