// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AlertConfigResourceType: core.serialization.Schema<
    serializers.AlertConfigResourceType.Raw,
    TrueFoundry.AlertConfigResourceType
> = core.serialization.enum_(["application", "cluster"]);

export declare namespace AlertConfigResourceType {
    export type Raw = "application" | "cluster";
}
