// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { ArtifactManifest } from "./ArtifactManifest.js";
import { Subject } from "./Subject.js";

export const ArtifactVersion: core.serialization.ObjectSchema<serializers.ArtifactVersion.Raw, TrueFoundry.ArtifactVersion> = core.serialization.object({
        "createdAt": core.serialization.property("created_at", core.serialization.date().optional()),
        "updatedAt": core.serialization.property("updated_at", core.serialization.date().optional()),
        "manifest": ArtifactManifest.optional(),
        "id": core.serialization.string(),
        "fqn": core.serialization.string(),
        "createdBySubject": core.serialization.property("created_by_subject", Subject),
        "mlRepoId": core.serialization.property("ml_repo_id", core.serialization.string()),
        "usageCodeSnippet": core.serialization.property("usage_code_snippet", core.serialization.string().optional()),
        "tags": core.serialization.list(core.serialization.string()).optional(),
        "artifactId": core.serialization.property("artifact_id", core.serialization.string())
    });

export declare namespace ArtifactVersion {
    export interface Raw {
        created_at?: string | null;
        updated_at?: string | null;
        manifest?: ArtifactManifest.Raw | null;
        id: string;
        fqn: string;
        created_by_subject: Subject.Raw;
        ml_repo_id: string;
        usage_code_snippet?: string | null;
        tags?: string[] | null;
        artifact_id: string;
    }
}
