// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const AutoRotate: core.serialization.ObjectSchema<serializers.AutoRotate.Raw, TrueFoundry.AutoRotate> = core.serialization.object({
        "autoRotateInterval": core.serialization.property("auto_rotate_interval", core.serialization.number()),
        "gracePeriod": core.serialization.property("grace_period", core.serialization.number())
    });

export declare namespace AutoRotate {
    export interface Raw {
        auto_rotate_interval: number;
        grace_period: number;
    }
}
