/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";

export const AwsAssumedRoleBasedAuth: core.serialization.ObjectSchema<
    serializers.AwsAssumedRoleBasedAuth.Raw,
    TrueFoundry.AwsAssumedRoleBasedAuth
> = core.serialization.object({
    type: core.serialization.stringLiteral("assumed-role-based"),
    assumed_role_arn: core.serialization.string(),
});

export declare namespace AwsAssumedRoleBasedAuth {
    export interface Raw {
        type: "assumed-role-based";
        assumed_role_arn: string;
    }
}
