/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import { AwsRegion } from "./AwsRegion.js";
import { AwsBedrockProviderAccountAuthData } from "./AwsBedrockProviderAccountAuthData";
import { BedrockModelV2 } from "./BedrockModelV2.js";
import { Collaborator } from "./Collaborator.js";

export const AwsBedrockProviderAccount: core.serialization.ObjectSchema<
    serializers.AwsBedrockProviderAccount.Raw,
    TrueFoundry.AwsBedrockProviderAccount
> = core.serialization.object({
    type: core.serialization.stringLiteral("provider-account/aws-bedrock"),
    name: core.serialization.string(),
    region: AwsRegion,
    authData: core.serialization.property("auth_data", AwsBedrockProviderAccountAuthData.optional()),
    integrations: core.serialization.list(BedrockModelV2),
    collaborators: core.serialization.list(Collaborator).optional(),
});

export declare namespace AwsBedrockProviderAccount {
    export interface Raw {
        type: "provider-account/aws-bedrock";
        name: string;
        region: AwsRegion.Raw;
        auth_data?: AwsBedrockProviderAccountAuthData.Raw | null;
        integrations: BedrockModelV2.Raw[];
        collaborators?: Collaborator.Raw[] | null;
    }
}
