// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AzureOpenAiModelDeploymentType: core.serialization.Schema<
    serializers.AzureOpenAiModelDeploymentType.Raw,
    TrueFoundry.AzureOpenAiModelDeploymentType
> = core.serialization.enum_(["standard", "datazone_us", "datazone_eu", "global"]);

export declare namespace AzureOpenAiModelDeploymentType {
    export type Raw = "standard" | "datazone_us" | "datazone_eu" | "global";
}
