// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { AzurePromptShieldGuardrailConfigAuthData } from "./AzurePromptShieldGuardrailConfigAuthData.js";
import { AzurePromptShieldGuardrailConfigConfig } from "./AzurePromptShieldGuardrailConfigConfig.js";
import { EnforcingStrategy } from "./EnforcingStrategy.js";

export const AzurePromptShieldGuardrailConfig: core.serialization.ObjectSchema<serializers.AzurePromptShieldGuardrailConfig.Raw, TrueFoundry.AzurePromptShieldGuardrailConfig> = core.serialization.object({
        "name": core.serialization.string(),
        "description": core.serialization.string().optional(),
        "type": core.serialization.stringLiteral("integration/guardrail-config/azure-prompt-shield"),
        "authData": core.serialization.property("auth_data", AzurePromptShieldGuardrailConfigAuthData),
        "operation": core.serialization.stringLiteral("validate"),
        "enforcingStrategy": core.serialization.property("enforcing_strategy", EnforcingStrategy),
        "config": AzurePromptShieldGuardrailConfigConfig
    });

export declare namespace AzurePromptShieldGuardrailConfig {
    export interface Raw {
        name: string;
        description?: string | null;
        type: "integration/guardrail-config/azure-prompt-shield";
        auth_data: AzurePromptShieldGuardrailConfigAuthData.Raw;
        operation: "validate";
        enforcing_strategy: EnforcingStrategy.Raw;
        config: AzurePromptShieldGuardrailConfigConfig.Raw;
    }
}
