/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import { AzureAksIntegration } from "./AzureAksIntegration.js";
import { AzureContainerRegistry } from "./AzureContainerRegistry.js";
import { AzureBlobStorage } from "./AzureBlobStorage.js";
import { AzureOpenAiModel } from "./AzureOpenAiModel.js";
import { AzureVault } from "./AzureVault.js";
import { AzureReposIntegration } from "./AzureReposIntegration.js";
import { AzureAiInferenceModel } from "./AzureAiInferenceModel.js";
import { AzureFoundryModel } from "./AzureFoundryModel.js";

export const AzureIntegrations: core.serialization.Schema<
    serializers.AzureIntegrations.Raw,
    TrueFoundry.AzureIntegrations
> = core.serialization.undiscriminatedUnion([
    AzureAksIntegration,
    AzureContainerRegistry,
    AzureBlobStorage,
    AzureOpenAiModel,
    AzureVault,
    AzureReposIntegration,
    AzureAiInferenceModel,
    AzureFoundryModel,
]);

export declare namespace AzureIntegrations {
    export type Raw =
        | AzureAksIntegration.Raw
        | AzureContainerRegistry.Raw
        | AzureBlobStorage.Raw
        | AzureOpenAiModel.Raw
        | AzureVault.Raw
        | AzureReposIntegration.Raw
        | AzureAiInferenceModel.Raw
        | AzureFoundryModel.Raw;
}
