// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AzureCertificateAuth } from "./AzureCertificateAuth.js";
import { AzureClientSecretAuth } from "./AzureClientSecretAuth.js";
import { AzureKeyAuth } from "./AzureKeyAuth.js";
import { AzureWorkloadIdentityAuth } from "./AzureWorkloadIdentityAuth.js";

export const AzurePiiGuardrailConfigAuthData: core.serialization.Schema<
    serializers.AzurePiiGuardrailConfigAuthData.Raw,
    TrueFoundry.AzurePiiGuardrailConfigAuthData
> = core.serialization.undiscriminatedUnion([
    AzureKeyAuth,
    AzureCertificateAuth,
    AzureClientSecretAuth,
    AzureWorkloadIdentityAuth,
]);

export declare namespace AzurePiiGuardrailConfigAuthData {
    export type Raw =
        | AzureKeyAuth.Raw
        | AzureCertificateAuth.Raw
        | AzureClientSecretAuth.Raw
        | AzureWorkloadIdentityAuth.Raw;
}
