// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { AzureCertificateAuth } from "./AzureCertificateAuth.js";
import { AzureClientSecretAuth } from "./AzureClientSecretAuth.js";
import { AzureKeyAuth } from "./AzureKeyAuth.js";
import { AzureWorkloadIdentityAuth } from "./AzureWorkloadIdentityAuth.js";

export const AzureFoundryModelAuthData: core.serialization.Schema<serializers.AzureFoundryModelAuthData.Raw, TrueFoundry.AzureFoundryModelAuthData> = core.serialization.undiscriminatedUnion([AzureKeyAuth, AzureCertificateAuth, AzureClientSecretAuth, AzureWorkloadIdentityAuth]);

export declare namespace AzureFoundryModelAuthData {
    export type Raw = AzureKeyAuth.Raw | AzureCertificateAuth.Raw | AzureClientSecretAuth.Raw | AzureWorkloadIdentityAuth.Raw;
}
