// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const BaseArtifactVersion: core.serialization.ObjectSchema<serializers.BaseArtifactVersion.Raw, TrueFoundry.BaseArtifactVersion> = core.serialization.object({
        "name": core.serialization.string().optional(),
        "metadata": core.serialization.record(core.serialization.string(), core.serialization.unknown()),
        "mlRepo": core.serialization.property("ml_repo", core.serialization.string().optional()),
        "version": core.serialization.number().optional()
    });

export declare namespace BaseArtifactVersion {
    export interface Raw {
        name?: string | null;
        metadata: Record<string, unknown>;
        ml_repo?: string | null;
        version?: number | null;
    }
}
