// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { BasetenModel } from "./BasetenModel.js";

export const BasetenIntegrations: core.serialization.ObjectSchema<serializers.BasetenIntegrations.Raw, TrueFoundry.BasetenIntegrations> = BasetenModel;

export declare namespace BasetenIntegrations {
    export type Raw = BasetenModel.Raw;
}
