/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";

export const BaseAutoscaling: core.serialization.ObjectSchema<
    serializers.BaseAutoscaling.Raw,
    TrueFoundry.BaseAutoscaling
> = core.serialization.object({
    minReplicas: core.serialization.property("min_replicas", core.serialization.number()),
    maxReplicas: core.serialization.property("max_replicas", core.serialization.number()),
    pollingInterval: core.serialization.property("polling_interval", core.serialization.number().optional()),
});

export declare namespace BaseAutoscaling {
    export interface Raw {
        min_replicas: number;
        max_replicas: number;
        polling_interval?: number | null;
    }
}
