// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { BitbucketIntegrationAuthData } from "./BitbucketIntegrationAuthData.js";

export const BitbucketIntegration: core.serialization.ObjectSchema<serializers.BitbucketIntegration.Raw, TrueFoundry.BitbucketIntegration> = core.serialization.object({
        "type": core.serialization.stringLiteral("integration/vcs/bitbucket"),
        "name": core.serialization.string(),
        "accountName": core.serialization.property("account_name", core.serialization.string()),
        "authData": core.serialization.property("auth_data", BitbucketIntegrationAuthData.optional()),
        "authorizedSubjects": core.serialization.property("authorized_subjects", core.serialization.list(core.serialization.string()).optional())
    });

export declare namespace BitbucketIntegration {
    export interface Raw {
        type: "integration/vcs/bitbucket";
        name: string;
        account_name: string;
        auth_data?: BitbucketIntegrationAuthData.Raw | null;
        authorized_subjects?: string[] | null;
    }
}
