// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { BudgetV2AppliesToAggregate } from "./BudgetV2AppliesToAggregate.js";
import { BudgetV2AppliesToMetadata } from "./BudgetV2AppliesToMetadata.js";
import { BudgetV2AppliesToPerModel } from "./BudgetV2AppliesToPerModel.js";
import { BudgetV2AppliesToPerUser } from "./BudgetV2AppliesToPerUser.js";
import { BudgetV2AppliesToPerVirtualAccount } from "./BudgetV2AppliesToPerVirtualAccount.js";

export const BudgetV2AppliesTo: core.serialization.Schema<serializers.BudgetV2AppliesTo.Raw, TrueFoundry.BudgetV2AppliesTo> = core.serialization.undiscriminatedUnion([BudgetV2AppliesToAggregate, BudgetV2AppliesToPerUser, BudgetV2AppliesToPerModel, BudgetV2AppliesToPerVirtualAccount, BudgetV2AppliesToMetadata]);

export declare namespace BudgetV2AppliesTo {
    export type Raw = BudgetV2AppliesToAggregate.Raw | BudgetV2AppliesToPerUser.Raw | BudgetV2AppliesToPerModel.Raw | BudgetV2AppliesToPerVirtualAccount.Raw | BudgetV2AppliesToMetadata.Raw;
}
