// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { BudgetV2OverrideLimits } from "./BudgetV2OverrideLimits.js";

export const BudgetV2PerModelOverride: core.serialization.ObjectSchema<serializers.BudgetV2PerModelOverride.Raw, TrueFoundry.BudgetV2PerModelOverride> = core.serialization.object({
        "models": core.serialization.list(core.serialization.string()),
        "limits": BudgetV2OverrideLimits
    });

export declare namespace BudgetV2PerModelOverride {
    export interface Raw {
        models: string[];
        limits: BudgetV2OverrideLimits.Raw;
    }
}
