// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { GitSource } from "./GitSource.js";
import { LocalSource } from "./LocalSource.js";
import { RemoteSource } from "./RemoteSource.js";

export const BuildBuildSource: core.serialization.Schema<serializers.BuildBuildSource.Raw, TrueFoundry.BuildBuildSource> = core.serialization.undiscriminatedUnion([RemoteSource, GitSource, LocalSource]);

export declare namespace BuildBuildSource {
    export type Raw = RemoteSource.Raw | GitSource.Raw | LocalSource.Raw;
}
