// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { McpServerWithFqn } from "./McpServerWithFqn.js";
import { McpServerWithUrl } from "./McpServerWithUrl.js";

export const ChatPromptManifestMcpServersItem: core.serialization.Schema<
    serializers.ChatPromptManifestMcpServersItem.Raw,
    TrueFoundry.ChatPromptManifestMcpServersItem
> = core.serialization.undiscriminatedUnion([McpServerWithFqn, McpServerWithUrl]);

export declare namespace ChatPromptManifestMcpServersItem {
    export type Raw = McpServerWithFqn.Raw | McpServerWithUrl.Raw;
}
