// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { LatencyBasedLoadBalancing } from "./LatencyBasedLoadBalancing.js";
import { PriorityBasedLoadBalancing } from "./PriorityBasedLoadBalancing.js";
import { WeightBasedLoadBalancing } from "./WeightBasedLoadBalancing.js";

export const ChatPromptManifestRoutingConfig: core.serialization.Schema<
    serializers.ChatPromptManifestRoutingConfig.Raw,
    TrueFoundry.ChatPromptManifestRoutingConfig
> = core.serialization.undiscriminatedUnion([
    WeightBasedLoadBalancing,
    LatencyBasedLoadBalancing,
    PriorityBasedLoadBalancing,
]);

export declare namespace ChatPromptManifestRoutingConfig {
    export type Raw = WeightBasedLoadBalancing.Raw | LatencyBasedLoadBalancing.Raw | PriorityBasedLoadBalancing.Raw;
}
