/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";

export const CommonToolsSettings: core.serialization.ObjectSchema<
    serializers.CommonToolsSettings.Raw,
    TrueFoundry.CommonToolsSettings
> = core.serialization.object({
    type: core.serialization.stringLiteral("settings/common-tools"),
    web_search: core.serialization.boolean(),
    code_executor: core.serialization.boolean(),
    sequential_thinking: core.serialization.boolean(),
    vision_ocr: core.serialization.boolean(),
    web_scrape: core.serialization.boolean(),
});

export declare namespace CommonToolsSettings {
    export interface Raw {
        type: "settings/common-tools";
        web_search: boolean;
        code_executor: boolean;
        sequential_thinking: boolean;
        vision_ocr: boolean;
        web_scrape: boolean;
    }
}
