// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const CommonToolsSettings: core.serialization.ObjectSchema<serializers.CommonToolsSettings.Raw, TrueFoundry.CommonToolsSettings> = core.serialization.object({
        "type": core.serialization.stringLiteral("settings/common-tools"),
        "webSearch": core.serialization.property("web_search", core.serialization.boolean()),
        "codeExecutor": core.serialization.property("code_executor", core.serialization.boolean()),
        "sandboxExec": core.serialization.property("sandbox_exec", core.serialization.boolean()),
        "sequentialThinking": core.serialization.property("sequential_thinking", core.serialization.boolean()),
        "webScrape": core.serialization.property("web_scrape", core.serialization.boolean())
    });

export declare namespace CommonToolsSettings {
    export interface Raw {
        type: "settings/common-tools";
        web_search: boolean;
        code_executor: boolean;
        sandbox_exec: boolean;
        sequential_thinking: boolean;
        web_scrape: boolean;
    }
}
