// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Build } from "./Build.js";
import { Image } from "./Image.js";

export const ContainerTaskConfigImage: core.serialization.Schema<
    serializers.ContainerTaskConfigImage.Raw,
    TrueFoundry.ContainerTaskConfigImage
> = core.serialization.undiscriminatedUnion([Build, Image]);

export declare namespace ContainerTaskConfigImage {
    export type Raw = Build.Raw | Image.Raw;
}
