// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { Run } from "./Run.js";

export const CreateRunResponse: core.serialization.ObjectSchema<serializers.CreateRunResponse.Raw, TrueFoundry.CreateRunResponse> = core.serialization.object({
        "run": Run
    });

export declare namespace CreateRunResponse {
    export interface Raw {
        run: Run.Raw;
    }
}
