// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const CrowdStrikeAidrGuardrailConfigConfig: core.serialization.ObjectSchema<serializers.CrowdStrikeAidrGuardrailConfigConfig.Raw, TrueFoundry.CrowdStrikeAidrGuardrailConfigConfig> = core.serialization.object({
        "baseUrl": core.serialization.property("base_url", core.serialization.string().optional())
    });

export declare namespace CrowdStrikeAidrGuardrailConfigConfig {
    export interface Raw {
        base_url?: string | null;
    }
}
