// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { Collaborator } from "./Collaborator.js";
import { CustomEndpointIntegrations } from "./CustomEndpointIntegrations.js";
import { CustomEndpointProviderAccountEndpointType } from "./CustomEndpointProviderAccountEndpointType.js";
import { CustomEndpointProviderAccountRoutingType } from "./CustomEndpointProviderAccountRoutingType.js";
import { CustomHeaderAuth } from "./CustomHeaderAuth.js";
import { OwnedBy } from "./OwnedBy.js";

export const CustomEndpointProviderAccount: core.serialization.ObjectSchema<serializers.CustomEndpointProviderAccount.Raw, TrueFoundry.CustomEndpointProviderAccount> = core.serialization.object({
        "type": core.serialization.stringLiteral("provider-account/custom-endpoint"),
        "name": core.serialization.string(),
        "endpointType": core.serialization.property("endpoint_type", CustomEndpointProviderAccountEndpointType.optional()),
        "routingType": core.serialization.property("routing_type", CustomEndpointProviderAccountRoutingType.optional()),
        "slug": core.serialization.string().optional(),
        "authData": core.serialization.property("auth_data", CustomHeaderAuth.optional()),
        "integrations": core.serialization.list(CustomEndpointIntegrations),
        "collaborators": core.serialization.list(Collaborator).optional(),
        "ownedBy": OwnedBy.optional()
    });

export declare namespace CustomEndpointProviderAccount {
    export interface Raw {
        type: "provider-account/custom-endpoint";
        name: string;
        endpoint_type?: CustomEndpointProviderAccountEndpointType.Raw | null;
        routing_type?: CustomEndpointProviderAccountRoutingType.Raw | null;
        slug?: string | null;
        auth_data?: CustomHeaderAuth.Raw | null;
        integrations: CustomEndpointIntegrations.Raw[];
        collaborators?: Collaborator.Raw[] | null;
        ownedBy?: OwnedBy.Raw | null;
    }
}
