// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CustomBearerAuth: core.serialization.ObjectSchema<
    serializers.CustomBearerAuth.Raw,
    TrueFoundry.CustomBearerAuth
> = core.serialization.object({
    type: core.serialization.stringLiteral("bearer-auth"),
    bearerToken: core.serialization.property("bearer_token", core.serialization.string()),
});

export declare namespace CustomBearerAuth {
    export interface Raw {
        type: "bearer-auth";
        bearer_token: string;
    }
}
