// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ExternalBlobStorageSource } from "./ExternalBlobStorageSource.js";
import { TrueFoundryManagedSource } from "./TrueFoundryManagedSource.js";

export const DataDirectoryManifestSource: core.serialization.Schema<
    serializers.DataDirectoryManifestSource.Raw,
    TrueFoundry.DataDirectoryManifestSource
> = core.serialization.undiscriminatedUnion([TrueFoundryManagedSource, ExternalBlobStorageSource]);

export declare namespace DataDirectoryManifestSource {
    export type Raw = TrueFoundryManagedSource.Raw | ExternalBlobStorageSource.Raw;
}
