// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const DeleteVirtualAccountResponse: core.serialization.ObjectSchema<
    serializers.DeleteVirtualAccountResponse.Raw,
    TrueFoundry.DeleteVirtualAccountResponse
> = core.serialization.object({});

export declare namespace DeleteVirtualAccountResponse {
    export type Raw = {};
}
