// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ApplicationSummary } from "./ApplicationSummary.js";
import { BuildInfo } from "./BuildInfo.js";
import { DeploymentManifest } from "./DeploymentManifest.js";
import { DeploymentStatus } from "./DeploymentStatus.js";
import { Recommendation } from "./Recommendation.js";
import { Subject } from "./Subject.js";

export const Deployment: core.serialization.ObjectSchema<serializers.Deployment.Raw, TrueFoundry.Deployment> =
    core.serialization.object({
        id: core.serialization.string().optionalNullable(),
        version: core.serialization.number().optionalNullable(),
        fqn: core.serialization.string().optionalNullable(),
        applicationId: core.serialization.string().optionalNullable(),
        manifest: DeploymentManifest,
        application: ApplicationSummary.optionalNullable(),
        createdBySubject: Subject,
        createdAt: core.serialization.date().optionalNullable(),
        updatedAt: core.serialization.date().optionalNullable(),
        deploymentBuilds: core.serialization.list(BuildInfo).optionalNullable(),
        deploymentStatuses: core.serialization.list(DeploymentStatus).optionalNullable(),
        currentStatusId: core.serialization.string().optionalNullable(),
        currentStatus: DeploymentStatus.optionalNullable(),
        appliedRecommendations: core.serialization.list(Recommendation).optionalNullable(),
        createdBy: core.serialization.string().optionalNullable(),
    });

export declare namespace Deployment {
    export interface Raw {
        id?: (string | null | undefined) | null;
        version?: (number | null | undefined) | null;
        fqn?: (string | null | undefined) | null;
        applicationId?: (string | null | undefined) | null;
        manifest: DeploymentManifest.Raw;
        application?: (ApplicationSummary.Raw | null | undefined) | null;
        createdBySubject: Subject.Raw;
        createdAt?: (string | null | undefined) | null;
        updatedAt?: (string | null | undefined) | null;
        deploymentBuilds?: (BuildInfo.Raw[] | null | undefined) | null;
        deploymentStatuses?: (DeploymentStatus.Raw[] | null | undefined) | null;
        currentStatusId?: (string | null | undefined) | null;
        currentStatus?: (DeploymentStatus.Raw | null | undefined) | null;
        appliedRecommendations?: (Recommendation.Raw[] | null | undefined) | null;
        createdBy?: (string | null | undefined) | null;
    }
}
