// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const ExactMatchCacheConfig: core.serialization.ObjectSchema<serializers.ExactMatchCacheConfig.Raw, TrueFoundry.ExactMatchCacheConfig> = core.serialization.object({
        "type": core.serialization.stringLiteral("exact-match"),
        "namespace": core.serialization.string().optional(),
        "ttl": core.serialization.number()
    });

export declare namespace ExactMatchCacheConfig {
    export interface Raw {
        type: "exact-match";
        namespace?: string | null;
        ttl: number;
    }
}
