// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const FiddlerGuardType: core.serialization.Schema<
    serializers.FiddlerGuardType.Raw,
    TrueFoundry.FiddlerGuardType
> = core.serialization.enum_(["fiddler-safety", "fiddler-response-faithfulness"]);

export declare namespace FiddlerGuardType {
    export type Raw = "fiddler-safety" | "fiddler-response-faithfulness";
}
