/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import { FlyteTaskTemplate } from "./FlyteTaskTemplate.js";

export const FlyteTask: core.serialization.ObjectSchema<serializers.FlyteTask.Raw, TrueFoundry.FlyteTask> =
    core.serialization.object({
        template: FlyteTaskTemplate,
        description: core.serialization.unknown().optional(),
    });

export declare namespace FlyteTask {
    export interface Raw {
        template: FlyteTaskTemplate.Raw;
        description?: unknown | null;
    }
}
