/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import { FlyteWorkflowTemplate } from "./FlyteWorkflowTemplate.js";

export const FlyteWorkflow: core.serialization.ObjectSchema<serializers.FlyteWorkflow.Raw, TrueFoundry.FlyteWorkflow> =
    core.serialization.object({
        template: FlyteWorkflowTemplate,
        description: core.serialization.unknown().optional(),
    });

export declare namespace FlyteWorkflow {
    export interface Raw {
        template: FlyteWorkflowTemplate.Raw;
        description?: unknown | null;
    }
}
