// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const FlyteTaskId: core.serialization.ObjectSchema<serializers.FlyteTaskId.Raw, TrueFoundry.FlyteTaskId> =
    core.serialization.object({
        resourceType: core.serialization.stringLiteral("TASK"),
        name: core.serialization.string(),
    });

export declare namespace FlyteTaskId {
    export interface Raw {
        resourceType: "TASK";
        name: string;
    }
}
