// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { GatewayLoggingRule } from "./GatewayLoggingRule.js";

export const GatewayLoggingConfig: core.serialization.ObjectSchema<serializers.GatewayLoggingConfig.Raw, TrueFoundry.GatewayLoggingConfig> = core.serialization.object({
        "name": core.serialization.string(),
        "type": core.serialization.stringLiteral("gateway-logging-config"),
        "rules": core.serialization.list(GatewayLoggingRule)
    });

export declare namespace GatewayLoggingConfig {
    export interface Raw {
        name: string;
        type: "gateway-logging-config";
        rules: GatewayLoggingRule.Raw[];
    }
}
