// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Subject } from "./Subject.js";

export const GatewayInstallation: core.serialization.ObjectSchema<
    serializers.GatewayInstallation.Raw,
    TrueFoundry.GatewayInstallation
> = core.serialization.object({
    id: core.serialization.string(),
    serviceAccountId: core.serialization.string().optionalNullable(),
    manifest: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    enabled: core.serialization.boolean(),
    tenantName: core.serialization.string(),
    createdBySubject: Subject.optionalNullable(),
    createdAt: core.serialization.date(),
    updatedAt: core.serialization.date(),
    isDefault: core.serialization.boolean(),
    createdBy: core.serialization.string().optionalNullable(),
});

export declare namespace GatewayInstallation {
    export interface Raw {
        id: string;
        serviceAccountId?: (string | null | undefined) | null;
        manifest: Record<string, unknown>;
        enabled: boolean;
        tenantName: string;
        createdBySubject?: (Subject.Raw | null | undefined) | null;
        createdAt: string;
        updatedAt: string;
        isDefault: boolean;
        createdBy?: (string | null | undefined) | null;
    }
}
