// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const GatewayDataRoutingConfigDestinationMetadataCondition: core.serialization.ObjectSchema<serializers.GatewayDataRoutingConfigDestinationMetadataCondition.Raw, TrueFoundry.GatewayDataRoutingConfigDestinationMetadataCondition> = core.serialization.object({
        "field": core.serialization.stringLiteral("metadata"),
        "key": core.serialization.string(),
        "operator": core.serialization.stringLiteral("IN"),
        "value": core.serialization.list(core.serialization.string())
    });

export declare namespace GatewayDataRoutingConfigDestinationMetadataCondition {
    export interface Raw {
        field: "metadata";
        key: string;
        operator: "IN";
        value: string[];
    }
}
