/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import { GcpKeyFileAuth } from "./GcpKeyFileAuth.js";

export const GcpGcs: core.serialization.ObjectSchema<serializers.GcpGcs.Raw, TrueFoundry.GcpGcs> =
    core.serialization.object({
        type: core.serialization.stringLiteral("integration/blob-storage/gcp/gcs"),
        name: core.serialization.string(),
        storageRoot: core.serialization.property("storage_root", core.serialization.string()),
        authData: core.serialization.property("auth_data", GcpKeyFileAuth.optional()),
        authorizedSubjects: core.serialization.property(
            "authorized_subjects",
            core.serialization.list(core.serialization.string()).optional(),
        ),
    });

export declare namespace GcpGcs {
    export interface Raw {
        type: "integration/blob-storage/gcp/gcs";
        name: string;
        storage_root: string;
        auth_data?: GcpKeyFileAuth.Raw | null;
        authorized_subjects?: string[] | null;
    }
}
