// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { GcpIntegrations } from "./GcpIntegrations.js";
import { GcpKeyFileAuth } from "./GcpKeyFileAuth.js";
import { OwnedBy } from "./OwnedBy.js";

export const GcpProviderAccount: core.serialization.ObjectSchema<serializers.GcpProviderAccount.Raw, TrueFoundry.GcpProviderAccount> = core.serialization.object({
        "type": core.serialization.stringLiteral("provider-account/gcp"),
        "name": core.serialization.string(),
        "projectId": core.serialization.property("project_id", core.serialization.string().optional()),
        "authData": core.serialization.property("auth_data", GcpKeyFileAuth.optional()),
        "integrations": core.serialization.list(GcpIntegrations),
        "ownedBy": OwnedBy.optional()
    });

export declare namespace GcpProviderAccount {
    export interface Raw {
        type: "provider-account/gcp";
        name: string;
        project_id?: string | null;
        auth_data?: GcpKeyFileAuth.Raw | null;
        integrations: GcpIntegrations.Raw[];
        ownedBy?: OwnedBy.Raw | null;
    }
}
