// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { ModelCostMetric } from "./ModelCostMetric.js";
import { ModelType } from "./ModelType.js";

export const GeminiModel: core.serialization.ObjectSchema<serializers.GeminiModel.Raw, TrueFoundry.GeminiModel> = core.serialization.object({
        "type": core.serialization.stringLiteral("integration/model/gemini"),
        "name": core.serialization.string(),
        "modelId": core.serialization.property("model_id", core.serialization.string()),
        "modelTypes": core.serialization.property("model_types", core.serialization.list(ModelType)),
        "cost": ModelCostMetric.optional(),
        "authorizedSubjects": core.serialization.property("authorized_subjects", core.serialization.list(core.serialization.string()).optional())
    });

export declare namespace GeminiModel {
    export interface Raw {
        type: "integration/model/gemini";
        name: string;
        model_id: string;
        model_types: ModelType.Raw[];
        cost?: ModelCostMetric.Raw | null;
        authorized_subjects?: string[] | null;
    }
}
