// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { Agent } from "./Agent.js";

export const GetAgentResponse: core.serialization.ObjectSchema<serializers.GetAgentResponse.Raw, TrueFoundry.GetAgentResponse> = core.serialization.object({
        "data": Agent
    });

export declare namespace GetAgentResponse {
    export interface Raw {
        data: Agent.Raw;
    }
}
