// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Event } from "./Event.js";

export const GetEventsResponse: core.serialization.ObjectSchema<
    serializers.GetEventsResponse.Raw,
    TrueFoundry.GetEventsResponse
> = core.serialization.object({
    data: core.serialization.list(Event),
});

export declare namespace GetEventsResponse {
    export interface Raw {
        data: Event.Raw[];
    }
}
