/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import { MlRepo } from "./MlRepo.js";

export const GetMlRepoResponse: core.serialization.ObjectSchema<
    serializers.GetMlRepoResponse.Raw,
    TrueFoundry.GetMlRepoResponse
> = core.serialization.object({
    data: MlRepo,
});

export declare namespace GetMlRepoResponse {
    export interface Raw {
        data: MlRepo.Raw;
    }
}
