/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import { VirtualAccount } from "./VirtualAccount.js";

export const GetVirtualAccountResponse: core.serialization.ObjectSchema<
    serializers.GetVirtualAccountResponse.Raw,
    TrueFoundry.GetVirtualAccountResponse
> = core.serialization.object({
    data: VirtualAccount,
    token: core.serialization.string().optional(),
});

export declare namespace GetVirtualAccountResponse {
    export interface Raw {
        data: VirtualAccount.Raw;
        token?: string | null;
    }
}
