// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { GithubIntegrationAuthData } from "./GithubIntegrationAuthData.js";

export const GithubIntegration: core.serialization.ObjectSchema<serializers.GithubIntegration.Raw, TrueFoundry.GithubIntegration> = core.serialization.object({
        "type": core.serialization.stringLiteral("integration/vcs/github"),
        "name": core.serialization.string(),
        "accountName": core.serialization.property("account_name", core.serialization.string()),
        "authData": core.serialization.property("auth_data", GithubIntegrationAuthData.optional()),
        "authorizedSubjects": core.serialization.property("authorized_subjects", core.serialization.list(core.serialization.string()).optional())
    });

export declare namespace GithubIntegration {
    export interface Raw {
        type: "integration/vcs/github";
        name: string;
        account_name: string;
        auth_data?: GithubIntegrationAuthData.Raw | null;
        authorized_subjects?: string[] | null;
    }
}
