// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const GraphChartType: core.serialization.Schema<serializers.GraphChartType.Raw, TrueFoundry.GraphChartType> = core.serialization.enum_(["line", "vertical_line", "stacked_bar", "stacked_area", "bubble", "horizontal_bar", "horizontal_stacked_bar", "horizontal_box_plot", "bar_list"]);

export declare namespace GraphChartType {
    export type Raw = "line" | "vertical_line" | "stacked_bar" | "stacked_area" | "bubble" | "horizontal_bar" | "horizontal_stacked_bar" | "horizontal_box_plot" | "bar_list";
}
