/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import { HttpErrorCode } from "./HttpErrorCode";

export const HttpError: core.serialization.ObjectSchema<serializers.HttpError.Raw, TrueFoundry.HttpError> =
    core.serialization.object({
        statusCode: core.serialization.number(),
        message: core.serialization.string(),
        code: HttpErrorCode.optional(),
        details: core.serialization
            .list(core.serialization.record(core.serialization.string(), core.serialization.unknown()))
            .optional(),
    });

export declare namespace HttpError {
    export interface Raw {
        statusCode: number;
        message: string;
        code?: HttpErrorCode.Raw | null;
        details?: Record<string, unknown>[] | null;
    }
}
