// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ImageCommand } from "./ImageCommand.js";

export const Image: core.serialization.ObjectSchema<serializers.Image.Raw, TrueFoundry.Image> =
    core.serialization.object({
        type: core.serialization.stringLiteral("image"),
        imageUri: core.serialization.property("image_uri", core.serialization.string()),
        dockerRegistry: core.serialization.property("docker_registry", core.serialization.string().optional()),
        command: ImageCommand.optional(),
    });

export declare namespace Image {
    export interface Raw {
        type: "image";
        image_uri: string;
        docker_registry?: string | null;
        command?: ImageCommand.Raw | null;
    }
}
