/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";

export const KafkaMetricConfig: core.serialization.ObjectSchema<
    serializers.KafkaMetricConfig.Raw,
    TrueFoundry.KafkaMetricConfig
> = core.serialization.object({
    type: core.serialization.stringLiteral("kafka"),
    lag_threshold: core.serialization.number(),
});

export declare namespace KafkaMetricConfig {
    export interface Raw {
        type: "kafka";
        lag_threshold: number;
    }
}
