// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const KeyPresenceSpec: core.serialization.ObjectSchema<serializers.KeyPresenceSpec.Raw, TrueFoundry.KeyPresenceSpec> = core.serialization.object({
        "required": core.serialization.booleanLiteral(true).optional()
    });

export declare namespace KeyPresenceSpec {
    export interface Raw {
        required?: true | null;
    }
}
