// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { MetricCollection } from "./MetricCollection.js";

export const ListMetricHistoryResponse: core.serialization.ObjectSchema<serializers.ListMetricHistoryResponse.Raw, TrueFoundry.ListMetricHistoryResponse> = core.serialization.object({
        "metricCollections": core.serialization.property("metric_collections", core.serialization.list(MetricCollection))
    });

export declare namespace ListMetricHistoryResponse {
    export interface Raw {
        metric_collections: MetricCollection.Raw[];
    }
}
