// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GatewayBudget } from "./GatewayBudget.js";

export const ListBudgetsResponse: core.serialization.ObjectSchema<
    serializers.ListBudgetsResponse.Raw,
    TrueFoundry.ListBudgetsResponse
> = core.serialization.object({
    data: core.serialization.list(GatewayBudget),
});

export declare namespace ListBudgetsResponse {
    export interface Raw {
        data: GatewayBudget.Raw[];
    }
}
