/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import { User } from "./User.js";
import { Pagination } from "./Pagination.js";

export const ListUsersResponse: core.serialization.ObjectSchema<
    serializers.ListUsersResponse.Raw,
    TrueFoundry.ListUsersResponse
> = core.serialization.object({
    data: core.serialization.list(User),
    pagination: Pagination,
});

export declare namespace ListUsersResponse {
    export interface Raw {
        data: User.Raw[];
        pagination: Pagination.Raw;
    }
}
