/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import { Pagination } from "./Pagination.js";

export const ListApplicationsResponse: core.serialization.ObjectSchema<
    serializers.ListApplicationsResponse.Raw,
    TrueFoundry.ListApplicationsResponse
> = core.serialization.object({
    data: core.serialization.list(core.serialization.lazyObject(() => serializers.Application)),
    pagination: Pagination,
});

export declare namespace ListApplicationsResponse {
    export interface Raw {
        data: serializers.Application.Raw[];
        pagination: Pagination.Raw;
    }
}
