// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { LoadBalancingRule } from "./LoadBalancingRule.js";

export const LoadBalancingConfig: core.serialization.ObjectSchema<
    serializers.LoadBalancingConfig.Raw,
    TrueFoundry.LoadBalancingConfig
> = core.serialization.object({
    type: core.serialization.stringLiteral("gateway-load-balancing-config"),
    rules: core.serialization.list(LoadBalancingRule),
});

export declare namespace LoadBalancingConfig {
    export interface Raw {
        type: "gateway-load-balancing-config";
        rules: LoadBalancingRule.Raw[];
    }
}
