// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const LogsSortingDirection: core.serialization.Schema<serializers.LogsSortingDirection.Raw, TrueFoundry.LogsSortingDirection> = core.serialization.enum_(["asc", "desc"]);

export declare namespace LogsSortingDirection {
    export type Raw = "asc" | "desc";
}
