// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const McpServerOAuth2GrantType: core.serialization.Schema<
    serializers.McpServerOAuth2GrantType.Raw,
    TrueFoundry.McpServerOAuth2GrantType
> = core.serialization.enum_(["authorization_code", "client_credentials", "token_exchange", "id_jag"]);

export declare namespace McpServerOAuth2GrantType {
    export type Raw = "authorization_code" | "client_credentials" | "token_exchange" | "id_jag";
}
