// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { McpToolsOperatorCondition } from "./McpToolsOperatorCondition.js";
import { McpToolTarget } from "./McpToolTarget.js";

export const McpToolsOperator: core.serialization.ObjectSchema<
    serializers.McpToolsOperator.Raw,
    TrueFoundry.McpToolsOperator
> = core.serialization.object({
    condition: McpToolsOperatorCondition,
    values: core.serialization.list(McpToolTarget),
});

export declare namespace McpToolsOperator {
    export interface Raw {
        condition: McpToolsOperatorCondition.Raw;
        values: McpToolTarget.Raw[];
    }
}
