/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import { MlRepoManifest } from "./MlRepoManifest.js";
import { Subject } from "./Subject.js";

export const MlRepo: core.serialization.ObjectSchema<serializers.MlRepo.Raw, TrueFoundry.MlRepo> =
    core.serialization.object({
        tenantName: core.serialization.property("tenant_name", core.serialization.string()),
        manifest: MlRepoManifest,
        createdBySubject: core.serialization.property("created_by_subject", Subject),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        id: core.serialization.string(),
        numRuns: core.serialization.property("num_runs", core.serialization.number().optional()),
        artifactTypeCounts: core.serialization.property(
            "artifact_type_counts",
            core.serialization.record(core.serialization.string(), core.serialization.number()).optional(),
        ),
        datasetsCount: core.serialization.property("datasets_count", core.serialization.number().optional()),
    });

export declare namespace MlRepo {
    export interface Raw {
        tenant_name: string;
        manifest: MlRepoManifest.Raw;
        created_by_subject: Subject.Raw;
        created_at: string;
        id: string;
        num_runs?: number | null;
        artifact_type_counts?: Record<string, number> | null;
        datasets_count?: number | null;
    }
}
