// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { ExternalBlobStorageSource } from "./ExternalBlobStorageSource.js";
import { LocalModelSource } from "./LocalModelSource.js";
import { TrueFoundryManagedSource } from "./TrueFoundryManagedSource.js";

export const ModelManifestSource: core.serialization.Schema<serializers.ModelManifestSource.Raw, TrueFoundry.ModelManifestSource> = core.serialization.undiscriminatedUnion([TrueFoundryManagedSource, ExternalBlobStorageSource, LocalModelSource]);

export declare namespace ModelManifestSource {
    export type Raw = TrueFoundryManagedSource.Raw | ExternalBlobStorageSource.Raw | LocalModelSource.Raw;
}
