// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { FlyteTaskId } from "./FlyteTaskId.js";
import { SnowflakeConfig } from "./SnowflakeConfig.js";
import { SnowflakeSql } from "./SnowflakeSql.js";

export const NativeSnowflakeFlyteTaskTemplate: core.serialization.ObjectSchema<serializers.NativeSnowflakeFlyteTaskTemplate.Raw, TrueFoundry.NativeSnowflakeFlyteTaskTemplate> = core.serialization.object({
        "id": FlyteTaskId,
        "type": core.serialization.stringLiteral("snowflake"),
        "config": SnowflakeConfig,
        "sql": SnowflakeSql
    });

export declare namespace NativeSnowflakeFlyteTaskTemplate {
    export interface Raw {
        id: FlyteTaskId.Raw;
        type: "snowflake";
        config: SnowflakeConfig.Raw;
        sql: SnowflakeSql.Raw;
    }
}
