/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import { NomicModel } from "./NomicModel.js";

export const NomicIntegrations: core.serialization.ObjectSchema<
    serializers.NomicIntegrations.Raw,
    TrueFoundry.NomicIntegrations
> = NomicModel;

export declare namespace NomicIntegrations {
    export type Raw = NomicModel.Raw;
}
