// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import type * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { OllamaModel } from "./OllamaModel.js";

export const OllamaIntegrations: core.serialization.ObjectSchema<
    serializers.OllamaIntegrations.Raw,
    TrueFoundry.OllamaIntegrations
> = OllamaModel;

export declare namespace OllamaIntegrations {
    export type Raw = OllamaModel.Raw;
}
