// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const OpaBearerAuth: core.serialization.ObjectSchema<serializers.OpaBearerAuth.Raw, TrueFoundry.OpaBearerAuth> = core.serialization.object({
        "type": core.serialization.stringLiteral("bearer-auth"),
        "bearerToken": core.serialization.property("bearer_token", core.serialization.string())
    });

export declare namespace OpaBearerAuth {
    export interface Raw {
        type: "bearer-auth";
        bearer_token: string;
    }
}
