// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const OpenAiModerationsGuardrailConfigConfig: core.serialization.ObjectSchema<serializers.OpenAiModerationsGuardrailConfigConfig.Raw, TrueFoundry.OpenAiModerationsGuardrailConfigConfig> = core.serialization.object({
        "model": core.serialization.string(),
        "baseUrl": core.serialization.property("base_url", core.serialization.string().optional()),
        "categoryThresholds": core.serialization.property("category_thresholds", core.serialization.record(core.serialization.string(), core.serialization.number()).optional())
    });

export declare namespace OpenAiModerationsGuardrailConfigConfig {
    export interface Raw {
        model: string;
        base_url?: string | null;
        category_thresholds?: Record<string, number> | null;
    }
}
