// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const Operation: core.serialization.Schema<serializers.Operation.Raw, TrueFoundry.Operation> = core.serialization.enum_(["READ", "WRITE"]);

export declare namespace Operation {
    export type Raw = "READ" | "WRITE";
}
