/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import { PagerDutyIntegrationKeyAuth } from "./PagerDutyIntegrationKeyAuth.js";

export const PagerDutyIntegration: core.serialization.ObjectSchema<
    serializers.PagerDutyIntegration.Raw,
    TrueFoundry.PagerDutyIntegration
> = core.serialization.object({
    type: core.serialization.stringLiteral("integration/notification-channel/pagerduty"),
    name: core.serialization.string(),
    auth_data: PagerDutyIntegrationKeyAuth,
    authorized_subjects: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace PagerDutyIntegration {
    export interface Raw {
        type: "integration/notification-channel/pagerduty";
        name: string;
        auth_data: PagerDutyIntegrationKeyAuth.Raw;
        authorized_subjects?: string[] | null;
    }
}
