// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PatronusToxicityCriteria: core.serialization.Schema<
    serializers.PatronusToxicityCriteria.Raw,
    TrueFoundry.PatronusToxicityCriteria
> = core.serialization.stringLiteral("patronus:toxicity");

export declare namespace PatronusToxicityCriteria {
    export type Raw = "patronus:toxicity";
}
