// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const PatronusJudgeCriteria: core.serialization.Schema<serializers.PatronusJudgeCriteria.Raw, TrueFoundry.PatronusJudgeCriteria> = core.serialization.enum_(["patronus:answer-refusal", "patronus:no-openai-reference", "patronus:is-concise", "patronus:no-apologies", "patronus:is-polite", "patronus:is-helpful", "patronus:clinically-inappropriate-tone", "patronus:no-harmful-therapeutic-guidance", "patronus:is-code", "patronus:is-csv", "patronus:is-json", "patronus:no-age-bias", "patronus:no-gender-bias", "patronus:no-racial-bias", "patronus:prompt-injection"]);

export declare namespace PatronusJudgeCriteria {
    export type Raw = "patronus:answer-refusal" | "patronus:no-openai-reference" | "patronus:is-concise" | "patronus:no-apologies" | "patronus:is-polite" | "patronus:is-helpful" | "patronus:clinically-inappropriate-tone" | "patronus:no-harmful-therapeutic-guidance" | "patronus:is-code" | "patronus:is-csv" | "patronus:is-json" | "patronus:no-age-bias" | "patronus:no-gender-bias" | "patronus:no-racial-bias" | "patronus:prompt-injection";
}
