// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PolicyValidationOperation: core.serialization.ObjectSchema<
    serializers.PolicyValidationOperation.Raw,
    TrueFoundry.PolicyValidationOperation
> = core.serialization.object({
    type: core.serialization.stringLiteral("validate"),
});

export declare namespace PolicyValidationOperation {
    export interface Raw {
        type: "validate";
    }
}
