/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";

export const PolicyActions: core.serialization.Schema<serializers.PolicyActions.Raw, TrueFoundry.PolicyActions> =
    core.serialization.stringLiteral("apply");

export declare namespace PolicyActions {
    export type Raw = "apply";
}
