// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { NonNegativeFloat } from "./NonNegativeFloat.js";

export const PrivatePricingTier: core.serialization.ObjectSchema<serializers.PrivatePricingTier.Raw, TrueFoundry.PrivatePricingTier> = core.serialization.object({
        "from": core.serialization.number(),
        "costPerToken": core.serialization.property("cost_per_token", NonNegativeFloat)
    });

export declare namespace PrivatePricingTier {
    export interface Raw {
        from: number;
        cost_per_token: NonNegativeFloat.Raw;
    }
}
