/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import { PythonTaskConfigImage } from "./PythonTaskConfigImage";
import { Resources } from "./Resources.js";
import { PythonTaskConfigMountsItem } from "./PythonTaskConfigMountsItem";

export const PythonTaskConfig: core.serialization.ObjectSchema<
    serializers.PythonTaskConfig.Raw,
    TrueFoundry.PythonTaskConfig
> = core.serialization.object({
    type: core.serialization.stringLiteral("python-task-config"),
    image: PythonTaskConfigImage,
    env: core.serialization.record(core.serialization.string(), core.serialization.string().optional()).optional(),
    resources: Resources.optional(),
    mounts: core.serialization.list(PythonTaskConfigMountsItem).optional(),
    serviceAccount: core.serialization.property("service_account", core.serialization.string().optional()),
});

export declare namespace PythonTaskConfig {
    export interface Raw {
        type: "python-task-config";
        image: PythonTaskConfigImage.Raw;
        env?: Record<string, string | null | undefined> | null;
        resources?: Resources.Raw | null;
        mounts?: PythonTaskConfigMountsItem.Raw[] | null;
        service_account?: string | null;
    }
}
