// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const RemoteSpecSource: core.serialization.ObjectSchema<
    serializers.RemoteSpecSource.Raw,
    TrueFoundry.RemoteSpecSource
> = core.serialization.object({
    type: core.serialization.stringLiteral("remote"),
    url: core.serialization.string(),
});

export declare namespace RemoteSpecSource {
    export interface Raw {
        type: "remote";
        url: string;
    }
}
