// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const RoleBindingPermission: core.serialization.ObjectSchema<serializers.RoleBindingPermission.Raw, TrueFoundry.RoleBindingPermission> = core.serialization.object({
        "resourceType": core.serialization.string(),
        "resourceFqn": core.serialization.string(),
        "role": core.serialization.string()
    });

export declare namespace RoleBindingPermission {
    export interface Raw {
        resourceType: string;
        resourceFqn: string;
        role: string;
    }
}
