// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { RoleBindingPermission } from "./RoleBindingPermission.js";
import { RoleBindingSubject } from "./RoleBindingSubject.js";

export const RoleBindingManifest: core.serialization.ObjectSchema<serializers.RoleBindingManifest.Raw, TrueFoundry.RoleBindingManifest> = core.serialization.object({
        "type": core.serialization.stringLiteral("role-binding"),
        "name": core.serialization.string(),
        "subjects": core.serialization.list(RoleBindingSubject),
        "permissions": core.serialization.list(RoleBindingPermission)
    });

export declare namespace RoleBindingManifest {
    export interface Raw {
        type: "role-binding";
        name: string;
        subjects: RoleBindingSubject.Raw[];
        permissions: RoleBindingPermission.Raw[];
    }
}
