// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SecretDetectionGuardrailConfigOperation: core.serialization.Schema<
    serializers.SecretDetectionGuardrailConfigOperation.Raw,
    TrueFoundry.SecretDetectionGuardrailConfigOperation
> = core.serialization.enum_(["validate", "mutate"]);

export declare namespace SecretDetectionGuardrailConfigOperation {
    export type Raw = "validate" | "mutate";
}
