/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import { SlackWebhookIntegration } from "./SlackWebhookIntegration.js";
import { SlackBotIntegration } from "./SlackBotIntegration.js";

export const SlackIntegrations: core.serialization.Schema<
    serializers.SlackIntegrations.Raw,
    TrueFoundry.SlackIntegrations
> = core.serialization.undiscriminatedUnion([SlackWebhookIntegration, SlackBotIntegration]);

export declare namespace SlackIntegrations {
    export type Raw = SlackWebhookIntegration.Raw | SlackBotIntegration.Raw;
}
