// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const SnowflakeConfig: core.serialization.ObjectSchema<serializers.SnowflakeConfig.Raw, TrueFoundry.SnowflakeConfig> = core.serialization.object({
        "account": core.serialization.string(),
        "schema": core.serialization.string(),
        "user": core.serialization.string(),
        "warehouse": core.serialization.string(),
        "database": core.serialization.string()
    });

export declare namespace SnowflakeConfig {
    export interface Raw {
        account: string;
        schema: string;
        user: string;
        warehouse: string;
        database: string;
    }
}
