// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const SnowflakeTaskConfig: core.serialization.ObjectSchema<serializers.SnowflakeTaskConfig.Raw, TrueFoundry.SnowflakeTaskConfig> = core.serialization.object({
        "type": core.serialization.stringLiteral("snowflake-task-config"),
        "user": core.serialization.string(),
        "account": core.serialization.string(),
        "database": core.serialization.string(),
        "schemaName": core.serialization.property("schema_name", core.serialization.string()),
        "warehouse": core.serialization.string()
    });

export declare namespace SnowflakeTaskConfig {
    export interface Raw {
        type: "snowflake-task-config";
        user: string;
        account: string;
        database: string;
        schema_name: string;
        warehouse: string;
    }
}
