// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const SortDirection: core.serialization.Schema<serializers.SortDirection.Raw, TrueFoundry.SortDirection> = core.serialization.enum_(["asc", "desc"]);

export declare namespace SortDirection {
    export type Raw = "asc" | "desc";
}
