// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Manual } from "./Manual.js";
import { Schedule } from "./Schedule.js";

export const SparkJobTrigger: core.serialization.Schema<serializers.SparkJobTrigger.Raw, TrueFoundry.SparkJobTrigger> =
    core.serialization.undiscriminatedUnion([Manual, Schedule]);

export declare namespace SparkJobTrigger {
    export type Raw = Manual.Raw | Schedule.Raw;
}
