// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SparkDriverConfig } from "./SparkDriverConfig.js";

export const SparkJobDriverConfig: core.serialization.ObjectSchema<
    serializers.SparkJobDriverConfig.Raw,
    TrueFoundry.SparkJobDriverConfig
> = core.serialization
    .object({
        kustomize: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    })
    .extend(SparkDriverConfig);

export declare namespace SparkJobDriverConfig {
    export interface Raw extends SparkDriverConfig.Raw {
        kustomize?: Record<string, unknown> | null;
    }
}
