// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { SparkImage } from "./SparkImage.js";
import { SparkImageBuild } from "./SparkImageBuild.js";

export const SparkJobImage: core.serialization.Schema<serializers.SparkJobImage.Raw, TrueFoundry.SparkJobImage> = core.serialization.undiscriminatedUnion([SparkImage, SparkImageBuild]);

export declare namespace SparkJobImage {
    export type Raw = SparkImage.Raw | SparkImageBuild.Raw;
}
