/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";

export const SparkJobJavaEntrypoint: core.serialization.ObjectSchema<
    serializers.SparkJobJavaEntrypoint.Raw,
    TrueFoundry.SparkJobJavaEntrypoint
> = core.serialization.object({
    type: core.serialization.stringLiteral("java"),
    mainApplicationFile: core.serialization.property("main_application_file", core.serialization.string()),
    mainClass: core.serialization.property("main_class", core.serialization.string()),
    arguments: core.serialization.string().optional(),
});

export declare namespace SparkJobJavaEntrypoint {
    export interface Raw {
        type: "java";
        main_application_file: string;
        main_class: string;
        arguments?: string | null;
    }
}
