// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { SubjectClause } from "./SubjectClause.js";
import { SubjectConditionGroupOperator } from "./SubjectConditionGroupOperator.js";

export const SubjectConditionGroup: core.serialization.ObjectSchema<serializers.SubjectConditionGroup.Raw, TrueFoundry.SubjectConditionGroup> = core.serialization.object({
        "operator": SubjectConditionGroupOperator,
        "conditions": SubjectClause
    });

export declare namespace SubjectConditionGroup {
    export interface Raw {
        operator: SubjectConditionGroupOperator.Raw;
        conditions: SubjectClause.Raw;
    }
}
