// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { EnforcingStrategy } from "./EnforcingStrategy.js";

export const TfyPromptInjectionGuardrailConfig: core.serialization.ObjectSchema<serializers.TfyPromptInjectionGuardrailConfig.Raw, TrueFoundry.TfyPromptInjectionGuardrailConfig> = core.serialization.object({
        "name": core.serialization.string(),
        "description": core.serialization.string().optional(),
        "type": core.serialization.stringLiteral("integration/guardrail-config/tfy-prompt-injection"),
        "operation": core.serialization.stringLiteral("validate"),
        "enforcingStrategy": core.serialization.property("enforcing_strategy", EnforcingStrategy)
    });

export declare namespace TfyPromptInjectionGuardrailConfig {
    export interface Raw {
        name: string;
        description?: string | null;
        type: "integration/guardrail-config/tfy-prompt-injection";
        operation: "validate";
        enforcing_strategy: EnforcingStrategy.Raw;
    }
}
