// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { EnforcingStrategy } from "./EnforcingStrategy.js";
import { TfyPiiGuardrailConfigConfig } from "./TfyPiiGuardrailConfigConfig.js";
import { TfyPiiGuardrailConfigOperation } from "./TfyPiiGuardrailConfigOperation.js";

export const TfyPiiGuardrailConfig: core.serialization.ObjectSchema<serializers.TfyPiiGuardrailConfig.Raw, TrueFoundry.TfyPiiGuardrailConfig> = core.serialization.object({
        "name": core.serialization.string(),
        "description": core.serialization.string().optional(),
        "type": core.serialization.stringLiteral("integration/guardrail-config/tfy-pii"),
        "operation": TfyPiiGuardrailConfigOperation,
        "priority": core.serialization.number().optional(),
        "enforcingStrategy": core.serialization.property("enforcing_strategy", EnforcingStrategy),
        "config": TfyPiiGuardrailConfigConfig
    });

export declare namespace TfyPiiGuardrailConfig {
    export interface Raw {
        name: string;
        description?: string | null;
        type: "integration/guardrail-config/tfy-pii";
        operation: TfyPiiGuardrailConfigOperation.Raw;
        priority?: number | null;
        enforcing_strategy: EnforcingStrategy.Raw;
        config: TfyPiiGuardrailConfigConfig.Raw;
    }
}
