/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import { TrueFoundryIntegrations } from "./TrueFoundryIntegrations.js";

export const TrueFoundryProviderAccount: core.serialization.ObjectSchema<
    serializers.TrueFoundryProviderAccount.Raw,
    TrueFoundry.TrueFoundryProviderAccount
> = core.serialization.object({
    type: core.serialization.stringLiteral("provider-account/truefoundry"),
    name: core.serialization.string(),
    integrations: core.serialization.list(TrueFoundryIntegrations).optional(),
});

export declare namespace TrueFoundryProviderAccount {
    export interface Raw {
        type: "provider-account/truefoundry";
        name: string;
        integrations?: TrueFoundryIntegrations.Raw[] | null;
    }
}
