// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TrueFoundryAgentDynamicSubAgentsConfig: core.serialization.ObjectSchema<
    serializers.TrueFoundryAgentDynamicSubAgentsConfig.Raw,
    TrueFoundry.TrueFoundryAgentDynamicSubAgentsConfig
> = core.serialization.object({
    enabled: core.serialization.boolean(),
});

export declare namespace TrueFoundryAgentDynamicSubAgentsConfig {
    export interface Raw {
        enabled: boolean;
    }
}
