/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";

export const TtlRegistry: core.serialization.ObjectSchema<serializers.TtlRegistry.Raw, TrueFoundry.TtlRegistry> =
    core.serialization.object({
        type: core.serialization.stringLiteral("integration/docker-registry/ttl"),
        name: core.serialization.string(),
        registry_url: core.serialization.string(),
        authorized_subjects: core.serialization.list(core.serialization.string()).optional(),
    });

export declare namespace TtlRegistry {
    export interface Raw {
        type: "integration/docker-registry/ttl";
        name: string;
        registry_url: string;
        authorized_subjects?: string[] | null;
    }
}
