/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";

export const UsageLimits: core.serialization.ObjectSchema<serializers.UsageLimits.Raw, TrueFoundry.UsageLimits> =
    core.serialization.object({
        tokens_per_minute: core.serialization.number().optional(),
        requests_per_minute: core.serialization.number().optional(),
    });

export declare namespace UsageLimits {
    export interface Raw {
        tokens_per_minute?: number | null;
        requests_per_minute?: number | null;
    }
}
