// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { AccountInfo } from "./AccountInfo.js";
import { RoleWithResource } from "./RoleWithResource.js";
import { UserMetadata } from "./UserMetadata.js";

export const User: core.serialization.ObjectSchema<serializers.User.Raw, TrueFoundry.User> = core.serialization.object({
        "id": core.serialization.string(),
        "email": core.serialization.string(),
        "tenantName": core.serialization.string(),
        "metadata": UserMetadata,
        "roles": core.serialization.list(core.serialization.string()).optionalNullable(),
        "rolesWithResource": core.serialization.list(RoleWithResource).optionalNullable(),
        "accounts": core.serialization.list(AccountInfo).optionalNullable(),
        "active": core.serialization.boolean(),
        "isEditable": core.serialization.boolean(),
        "createdAt": core.serialization.date(),
        "updatedAt": core.serialization.date(),
        "lastAccessedAt": core.serialization.date().optionalNullable()
    });

export declare namespace User {
    export interface Raw {
        id: string;
        email: string;
        tenantName: string;
        metadata: UserMetadata.Raw;
        roles?: (string[] | null | undefined) | null;
        rolesWithResource?: (RoleWithResource.Raw[] | null | undefined) | null;
        accounts?: (AccountInfo.Raw[] | null | undefined) | null;
        active: boolean;
        isEditable: boolean;
        createdAt: string;
        updatedAt: string;
        lastAccessedAt?: (string | null | undefined) | null;
    }
}
