// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HeaderRoutingConfig } from "./HeaderRoutingConfig.js";
import { VirtualModelModelType } from "./VirtualModelModelType.js";

export const VirtualModel: core.serialization.ObjectSchema<serializers.VirtualModel.Raw, TrueFoundry.VirtualModel> =
    core.serialization.object({
        name: core.serialization.string(),
        type: core.serialization.stringLiteral("integration/model/virtual"),
        modelTypes: core.serialization.property("model_types", core.serialization.list(VirtualModelModelType)),
        slug: core.serialization.string().optional(),
        alias: core.serialization.list(core.serialization.string()).optional(),
        routingConfig: core.serialization.property("routing_config", HeaderRoutingConfig),
    });

export declare namespace VirtualModel {
    export interface Raw {
        name: string;
        type: "integration/model/virtual";
        model_types: VirtualModelModelType.Raw[];
        slug?: string | null;
        alias?: string[] | null;
        routing_config: HeaderRoutingConfig.Raw;
    }
}
