/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import { VolumeConfig } from "./VolumeConfig";
import { VolumeBrowser } from "./VolumeBrowser.js";

export const Volume: core.serialization.ObjectSchema<serializers.Volume.Raw, TrueFoundry.Volume> =
    core.serialization.object({
        type: core.serialization.stringLiteral("volume"),
        name: core.serialization.string(),
        config: VolumeConfig,
        volume_browser: VolumeBrowser.optional(),
        workspace_fqn: core.serialization.string().optional(),
    });

export declare namespace Volume {
    export interface Raw {
        type: "volume";
        name: string;
        config: VolumeConfig.Raw;
        volume_browser?: VolumeBrowser.Raw | null;
        workspace_fqn?: string | null;
    }
}
