// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { DynamicVolumeConfig } from "./DynamicVolumeConfig.js";
import { StaticVolumeConfig } from "./StaticVolumeConfig.js";

export const VolumeConfig: core.serialization.Schema<serializers.VolumeConfig.Raw, TrueFoundry.VolumeConfig> = core.serialization.undiscriminatedUnion([DynamicVolumeConfig, StaticVolumeConfig]);

export declare namespace VolumeConfig {
    export type Raw = DynamicVolumeConfig.Raw | StaticVolumeConfig.Raw;
}
