/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import { LoadBalancingWhen } from "./LoadBalancingWhen.js";
import { LoadBalanceTarget } from "./LoadBalanceTarget.js";

export const WeightBasedLoadBalancingRule: core.serialization.ObjectSchema<
    serializers.WeightBasedLoadBalancingRule.Raw,
    TrueFoundry.WeightBasedLoadBalancingRule
> = core.serialization.object({
    id: core.serialization.string(),
    when: LoadBalancingWhen,
    load_balance_targets: core.serialization.list(LoadBalanceTarget),
    type: core.serialization.stringLiteral("weight-based-routing"),
});

export declare namespace WeightBasedLoadBalancingRule {
    export interface Raw {
        id: string;
        when: LoadBalancingWhen.Raw;
        load_balance_targets: LoadBalanceTarget.Raw[];
        type: "weight-based-routing";
    }
}
