// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { AmqpInputConfig } from "./AmqpInputConfig.js";
import { KafkaInputConfig } from "./KafkaInputConfig.js";
import { NatsInputConfig } from "./NatsInputConfig.js";
import { SqsInputConfig } from "./SqsInputConfig.js";

export const WorkerConfigInputConfig: core.serialization.Schema<serializers.WorkerConfigInputConfig.Raw, TrueFoundry.WorkerConfigInputConfig> = core.serialization.undiscriminatedUnion([SqsInputConfig, NatsInputConfig, KafkaInputConfig, AmqpInputConfig]);

export declare namespace WorkerConfigInputConfig {
    export type Raw = SqsInputConfig.Raw | NatsInputConfig.Raw | KafkaInputConfig.Raw | AmqpInputConfig.Raw;
}
