/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import { WorkerConfigInputConfig } from "./WorkerConfigInputConfig";
import { WorkerConfigOutputConfig } from "./WorkerConfigOutputConfig";

export const WorkerConfig: core.serialization.ObjectSchema<serializers.WorkerConfig.Raw, TrueFoundry.WorkerConfig> =
    core.serialization.object({
        inputConfig: core.serialization.property("input_config", WorkerConfigInputConfig),
        outputConfig: core.serialization.property("output_config", WorkerConfigOutputConfig.optional()),
        numConcurrentWorkers: core.serialization.property("num_concurrent_workers", core.serialization.number()),
    });

export declare namespace WorkerConfig {
    export interface Raw {
        input_config: WorkerConfigInputConfig.Raw;
        output_config?: WorkerConfigOutputConfig.Raw | null;
        num_concurrent_workers: number;
    }
}
