/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as TrueFoundry from "../../api/index.js";
import * as core from "../../core/index.js";
import { XgBoostSerializationFormat } from "./XgBoostSerializationFormat.js";
import { XgBoostModelSchema } from "./XgBoostModelSchema.js";

export const XgBoostFramework: core.serialization.ObjectSchema<
    serializers.XgBoostFramework.Raw,
    TrueFoundry.XgBoostFramework
> = core.serialization.object({
    type: core.serialization.stringLiteral("xgboost"),
    serializationFormat: core.serialization.property("serialization_format", XgBoostSerializationFormat.optional()),
    modelFilepath: core.serialization.property("model_filepath", core.serialization.string().optional()),
    modelSchema: core.serialization.property("model_schema", XgBoostModelSchema.optional()),
});

export declare namespace XgBoostFramework {
    export interface Raw {
        type: "xgboost";
        serialization_format?: XgBoostSerializationFormat.Raw | null;
        model_filepath?: string | null;
        model_schema?: XgBoostModelSchema.Raw | null;
    }
}
