// This file was auto-generated by Fern from our API Definition.

export const ApplicationsListRequestLifecycleStage = {
    Active: "active",
    Deleting: "deleting",
    DeletionFailed: "deletion_failed",
} as const;
export type ApplicationsListRequestLifecycleStage =
    (typeof ApplicationsListRequestLifecycleStage)[keyof typeof ApplicationsListRequestLifecycleStage];
