/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { TrueFoundryClient } from "../../src/Client";

describe("Applications", () => {
    test("create_or_update", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { manifest: { key: "value" } };
        const rawResponseBody = {
            data: {
                id: "id",
                version: 1.1,
                fqn: "fqn",
                applicationId: "applicationId",
                manifest: {
                    name: "name",
                    image: {
                        type: "build",
                        build_source: { type: "remote", remote_uri: "remote_uri" },
                        build_spec: {
                            type: "dockerfile",
                            dockerfile_path: "dockerfile_path",
                            build_context_path: "build_context_path",
                        },
                    },
                    artifacts_download: {
                        artifacts: [
                            {
                                type: "truefoundry-artifact",
                                artifact_version_fqn: "artifact_version_fqn",
                                download_path_env_variable: "download_path_env_variable",
                            },
                        ],
                    },
                    resources: {
                        cpu_request: 1.1,
                        cpu_limit: 1.1,
                        memory_request: 1,
                        memory_limit: 1,
                        ephemeral_storage_request: 1,
                        ephemeral_storage_limit: 1,
                    },
                    ports: [{ port: 1, protocol: "TCP", expose: true }],
                    service_account: "service_account",
                    mounts: [{ type: "secret", mount_path: "mount_path", secret_fqn: "secret_fqn" }],
                    labels: { key: "value" },
                    liveness_probe: { config: { type: "http", path: "path", port: 1 } },
                    readiness_probe: { config: { type: "http", path: "path", port: 1 } },
                    workspace_fqn: "workspace_fqn",
                    type: "service",
                    replicas: 1.1,
                    auto_shutdown: { wait_time: 1 },
                    allow_interception: true,
                    rollout_strategy: {
                        type: "rolling_update",
                        max_unavailable_percentage: 1,
                        max_surge_percentage: 1,
                    },
                },
                application: {
                    id: "id",
                    fqn: "fqn",
                    name: "name",
                    type: "async-service",
                    createdBySubject: { subjectId: "subjectId", subjectType: "user" },
                    tenantName: "tenantName",
                    lifecycleStage: "active",
                    workspaceId: "workspaceId",
                    lastVersion: 1,
                    activeVersion: 1,
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                    recommendations: [
                        {
                            recommendationData: { key: "value" },
                            recommendationType: "recommendationType",
                            expiryTimestamp: "2024-01-15T09:30:00Z",
                        },
                    ],
                    alerts: [
                        {
                            name: "name",
                            timestamps: ["2024-01-15T09:30:00Z"],
                            startTime: "2024-01-15T09:30:00Z",
                            clusterId: "clusterId",
                            fingerprint: "fingerprint",
                        },
                    ],
                    alertsSummary: { key: "value" },
                    applicationDebugInfos: [{ applicationId: "applicationId", debugInfo: { key: "value" } }],
                    potentialProblems: [{ name: "name", description: "description" }],
                    autopilot: { key: "value" },
                    workspaceFqn: "workspaceFqn",
                    createdBy: "createdBy",
                    activeDeploymentId: "activeDeploymentId",
                    lastDeploymentId: "lastDeploymentId",
                },
                createdBySubject: {
                    subjectId: "subjectId",
                    subjectType: "user",
                    subjectSlug: "subjectSlug",
                    subjectDisplayName: "subjectDisplayName",
                },
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                deploymentBuilds: [{ name: "name", status: 20 }],
                deploymentStatuses: [{}],
                currentStatusId: "currentStatusId",
                currentStatus: {
                    id: "id",
                    deploymentId: "deploymentId",
                    status: "INITIALIZED",
                    state: { key: "value" },
                    transition: "BUILDING",
                    message: "message",
                    retryCount: 1.1,
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
                appliedRecommendations: [
                    {
                        recommendationData: { key: "value" },
                        recommendationType: "recommendationType",
                        expiryTimestamp: "2024-01-15T09:30:00Z",
                    },
                ],
                createdBy: "createdBy",
            },
        };
        server
            .mockEndpoint()
            .put("/api/svc/v1/apps")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.applications.createOrUpdate({
            manifest: {
                key: "value",
            },
        });
        expect(response).toEqual({
            data: {
                id: "id",
                version: 1.1,
                fqn: "fqn",
                applicationId: "applicationId",
                manifest: {
                    name: "name",
                    image: {
                        type: "build",
                        buildSource: {
                            type: "remote",
                            remoteUri: "remote_uri",
                        },
                        buildSpec: {
                            type: "dockerfile",
                            dockerfilePath: "dockerfile_path",
                            buildContextPath: "build_context_path",
                        },
                    },
                    artifactsDownload: {
                        artifacts: [
                            {
                                type: "truefoundry-artifact",
                                artifactVersionFqn: "artifact_version_fqn",
                                downloadPathEnvVariable: "download_path_env_variable",
                            },
                        ],
                    },
                    resources: {
                        cpuRequest: 1.1,
                        cpuLimit: 1.1,
                        memoryRequest: 1,
                        memoryLimit: 1,
                        ephemeralStorageRequest: 1,
                        ephemeralStorageLimit: 1,
                    },
                    ports: [
                        {
                            port: 1,
                            protocol: "TCP",
                            expose: true,
                        },
                    ],
                    serviceAccount: "service_account",
                    mounts: [
                        {
                            type: "secret",
                            mountPath: "mount_path",
                            secretFqn: "secret_fqn",
                        },
                    ],
                    labels: {
                        key: "value",
                    },
                    livenessProbe: {
                        config: {
                            type: "http",
                            path: "path",
                            port: 1,
                        },
                    },
                    readinessProbe: {
                        config: {
                            type: "http",
                            path: "path",
                            port: 1,
                        },
                    },
                    workspaceFqn: "workspace_fqn",
                    type: "service",
                    replicas: 1.1,
                    autoShutdown: {
                        waitTime: 1,
                    },
                    allowInterception: true,
                    rolloutStrategy: {
                        type: "rolling_update",
                        maxUnavailablePercentage: 1,
                        maxSurgePercentage: 1,
                    },
                },
                application: {
                    id: "id",
                    fqn: "fqn",
                    name: "name",
                    type: "async-service",
                    createdBySubject: {
                        subjectId: "subjectId",
                        subjectType: "user",
                    },
                    tenantName: "tenantName",
                    lifecycleStage: "active",
                    workspaceId: "workspaceId",
                    lastVersion: 1,
                    activeVersion: 1,
                    createdAt: new Date("2024-01-15T09:30:00.000Z"),
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                    recommendations: [
                        {
                            recommendationData: {
                                key: "value",
                            },
                            recommendationType: "recommendationType",
                            expiryTimestamp: new Date("2024-01-15T09:30:00.000Z"),
                        },
                    ],
                    alerts: [
                        {
                            name: "name",
                            timestamps: [new Date("2024-01-15T09:30:00.000Z")],
                            startTime: new Date("2024-01-15T09:30:00.000Z"),
                            clusterId: "clusterId",
                            fingerprint: "fingerprint",
                        },
                    ],
                    alertsSummary: {
                        key: "value",
                    },
                    applicationDebugInfos: [
                        {
                            applicationId: "applicationId",
                            debugInfo: {
                                key: "value",
                            },
                        },
                    ],
                    potentialProblems: [
                        {
                            name: "name",
                            description: "description",
                        },
                    ],
                    autopilot: {
                        key: "value",
                    },
                    workspaceFqn: "workspaceFqn",
                    createdBy: "createdBy",
                    activeDeploymentId: "activeDeploymentId",
                    lastDeploymentId: "lastDeploymentId",
                },
                createdBySubject: {
                    subjectId: "subjectId",
                    subjectType: "user",
                    subjectSlug: "subjectSlug",
                    subjectDisplayName: "subjectDisplayName",
                },
                createdAt: new Date("2024-01-15T09:30:00.000Z"),
                updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                deploymentBuilds: [
                    {
                        name: "name",
                        status: 20,
                    },
                ],
                deploymentStatuses: [{}],
                currentStatusId: "currentStatusId",
                currentStatus: {
                    id: "id",
                    deploymentId: "deploymentId",
                    status: "INITIALIZED",
                    state: {
                        key: "value",
                    },
                    transition: "BUILDING",
                    message: "message",
                    retryCount: 1.1,
                    createdAt: new Date("2024-01-15T09:30:00.000Z"),
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                },
                appliedRecommendations: [
                    {
                        recommendationData: {
                            key: "value",
                        },
                        recommendationType: "recommendationType",
                        expiryTimestamp: new Date("2024-01-15T09:30:00.000Z"),
                    },
                ],
                createdBy: "createdBy",
            },
        });
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                fqn: "fqn",
                name: "name",
                type: "async-service",
                createdBySubject: {
                    subjectId: "subjectId",
                    subjectType: "user",
                    subjectSlug: "subjectSlug",
                    subjectDisplayName: "subjectDisplayName",
                },
                tenantName: "tenantName",
                metadata: { paused: true },
                lifecycleStage: "active",
                workspaceId: "workspaceId",
                lastVersion: 1,
                activeVersion: 1,
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                recommendations: [
                    {
                        recommendationData: { key: "value" },
                        recommendationType: "recommendationType",
                        expiryTimestamp: "2024-01-15T09:30:00Z",
                    },
                ],
                alerts: [
                    {
                        name: "name",
                        timestamps: ["2024-01-15T09:30:00Z"],
                        startTime: "2024-01-15T09:30:00Z",
                        clusterId: "clusterId",
                        fingerprint: "fingerprint",
                    },
                ],
                alertsSummary: { key: "value" },
                applicationDebugInfos: [{ applicationId: "applicationId", debugInfo: { key: "value" } }],
                potentialProblems: [{ name: "name", description: "description" }],
                autopilot: { key: "value" },
                workspaceFqn: "workspaceFqn",
                createdBy: "createdBy",
                deployment: {
                    id: "id",
                    version: 1.1,
                    fqn: "fqn",
                    applicationId: "applicationId",
                    manifest: {
                        name: "name",
                        image: {
                            type: "build",
                            build_source: { type: "remote", remote_uri: "remote_uri" },
                            build_spec: {
                                type: "dockerfile",
                                dockerfile_path: "dockerfile_path",
                                build_context_path: "build_context_path",
                            },
                        },
                        ports: [{ port: 1, protocol: "TCP", expose: true }],
                    },
                    createdBySubject: { subjectId: "subjectId", subjectType: "user" },
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                    deploymentBuilds: [{ name: "name", status: 20 }],
                    deploymentStatuses: [{}],
                    currentStatusId: "currentStatusId",
                    appliedRecommendations: [
                        {
                            recommendationData: { key: "value" },
                            recommendationType: "recommendationType",
                            expiryTimestamp: "2024-01-15T09:30:00Z",
                        },
                    ],
                    createdBy: "createdBy",
                },
                activeDeploymentId: "activeDeploymentId",
                lastDeploymentId: "lastDeploymentId",
            },
        };
        server
            .mockEndpoint()
            .get("/api/svc/v1/apps/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.applications.get("id");
        expect(response).toEqual({
            data: {
                id: "id",
                fqn: "fqn",
                name: "name",
                type: "async-service",
                createdBySubject: {
                    subjectId: "subjectId",
                    subjectType: "user",
                    subjectSlug: "subjectSlug",
                    subjectDisplayName: "subjectDisplayName",
                },
                tenantName: "tenantName",
                metadata: {
                    paused: true,
                },
                lifecycleStage: "active",
                workspaceId: "workspaceId",
                lastVersion: 1,
                activeVersion: 1,
                createdAt: new Date("2024-01-15T09:30:00.000Z"),
                updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                recommendations: [
                    {
                        recommendationData: {
                            key: "value",
                        },
                        recommendationType: "recommendationType",
                        expiryTimestamp: new Date("2024-01-15T09:30:00.000Z"),
                    },
                ],
                alerts: [
                    {
                        name: "name",
                        timestamps: [new Date("2024-01-15T09:30:00.000Z")],
                        startTime: new Date("2024-01-15T09:30:00.000Z"),
                        clusterId: "clusterId",
                        fingerprint: "fingerprint",
                    },
                ],
                alertsSummary: {
                    key: "value",
                },
                applicationDebugInfos: [
                    {
                        applicationId: "applicationId",
                        debugInfo: {
                            key: "value",
                        },
                    },
                ],
                potentialProblems: [
                    {
                        name: "name",
                        description: "description",
                    },
                ],
                autopilot: {
                    key: "value",
                },
                workspaceFqn: "workspaceFqn",
                createdBy: "createdBy",
                deployment: {
                    id: "id",
                    version: 1.1,
                    fqn: "fqn",
                    applicationId: "applicationId",
                    manifest: {
                        name: "name",
                        image: {
                            type: "build",
                            buildSource: {
                                type: "remote",
                                remoteUri: "remote_uri",
                            },
                            buildSpec: {
                                type: "dockerfile",
                                dockerfilePath: "dockerfile_path",
                                buildContextPath: "build_context_path",
                            },
                        },
                        ports: [
                            {
                                port: 1,
                                protocol: "TCP",
                                expose: true,
                            },
                        ],
                    },
                    createdBySubject: {
                        subjectId: "subjectId",
                        subjectType: "user",
                    },
                    createdAt: new Date("2024-01-15T09:30:00.000Z"),
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                    deploymentBuilds: [
                        {
                            name: "name",
                            status: 20,
                        },
                    ],
                    deploymentStatuses: [{}],
                    currentStatusId: "currentStatusId",
                    appliedRecommendations: [
                        {
                            recommendationData: {
                                key: "value",
                            },
                            recommendationType: "recommendationType",
                            expiryTimestamp: new Date("2024-01-15T09:30:00.000Z"),
                        },
                    ],
                    createdBy: "createdBy",
                },
                activeDeploymentId: "activeDeploymentId",
                lastDeploymentId: "lastDeploymentId",
            },
        });
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .delete("/api/svc/v1/apps/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.applications.delete("id");
        expect(response).toEqual({
            message: "message",
        });
    });

    test("scale_to_zero", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryClient({ apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().patch("/api/svc/v1/apps/id/scale-to-zero").respondWith().statusCode(200).build();

        const response = await client.applications.scaleToZero("id");
        expect(response).toEqual(undefined);
    });

    test("scale_to_original", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            version: 1.1,
            fqn: "fqn",
            applicationId: "applicationId",
            manifest: {
                name: "name",
                image: {
                    type: "build",
                    docker_registry: "docker_registry",
                    build_source: { type: "remote", remote_uri: "remote_uri" },
                    build_spec: {
                        type: "dockerfile",
                        dockerfile_path: "dockerfile_path",
                        build_context_path: "build_context_path",
                    },
                },
                artifacts_download: {
                    cache_volume: { storage_class: "storage_class", cache_size: 1 },
                    artifacts: [
                        {
                            type: "truefoundry-artifact",
                            artifact_version_fqn: "artifact_version_fqn",
                            download_path_env_variable: "download_path_env_variable",
                        },
                    ],
                },
                resources: {
                    cpu_request: 1.1,
                    cpu_limit: 1.1,
                    memory_request: 1,
                    memory_limit: 1,
                    ephemeral_storage_request: 1,
                    ephemeral_storage_limit: 1,
                    shared_memory_size: 1,
                    node: { type: "node_selector" },
                    devices: [{ type: "nvidia_gpu", count: 1 }],
                },
                env: { key: "value" },
                ports: [{ port: 1, protocol: "TCP", expose: true }],
                service_account: "service_account",
                mounts: [{ type: "secret", mount_path: "mount_path", secret_fqn: "secret_fqn" }],
                labels: { key: "value" },
                kustomize: { patch: { key: "value" }, additions: [{ key: "value" }] },
                liveness_probe: {
                    config: { type: "http", path: "path", port: 1 },
                    initial_delay_seconds: 1,
                    period_seconds: 1,
                    timeout_seconds: 1,
                    success_threshold: 1,
                    failure_threshold: 1,
                },
                readiness_probe: {
                    config: { type: "http", path: "path", port: 1 },
                    initial_delay_seconds: 1,
                    period_seconds: 1,
                    timeout_seconds: 1,
                    success_threshold: 1,
                    failure_threshold: 1,
                },
                workspace_fqn: "workspace_fqn",
                type: "service",
                replicas: 1.1,
                auto_shutdown: { wait_time: 1 },
                allow_interception: true,
                rollout_strategy: { type: "rolling_update", max_unavailable_percentage: 1, max_surge_percentage: 1 },
            },
            application: {
                id: "id",
                fqn: "fqn",
                name: "name",
                type: "async-service",
                createdBySubject: {
                    subjectId: "subjectId",
                    subjectType: "user",
                    subjectSlug: "subjectSlug",
                    subjectDisplayName: "subjectDisplayName",
                },
                tenantName: "tenantName",
                metadata: { paused: true },
                lifecycleStage: "active",
                workspaceId: "workspaceId",
                lastVersion: 1,
                activeVersion: 1,
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                recommendations: [
                    {
                        recommendationData: { key: "value" },
                        recommendationType: "recommendationType",
                        expiryTimestamp: "2024-01-15T09:30:00Z",
                    },
                ],
                alerts: [
                    {
                        name: "name",
                        timestamps: ["2024-01-15T09:30:00Z"],
                        startTime: "2024-01-15T09:30:00Z",
                        clusterId: "clusterId",
                        fingerprint: "fingerprint",
                    },
                ],
                alertsSummary: { key: "value" },
                applicationDebugInfos: [{ applicationId: "applicationId", debugInfo: { key: "value" } }],
                potentialProblems: [{ name: "name", description: "description" }],
                autopilot: { key: "value" },
                workspaceFqn: "workspaceFqn",
                createdBy: "createdBy",
                activeDeploymentId: "activeDeploymentId",
                lastDeploymentId: "lastDeploymentId",
            },
            createdBySubject: {
                subjectId: "subjectId",
                subjectType: "user",
                subjectSlug: "subjectSlug",
                subjectDisplayName: "subjectDisplayName",
            },
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            deploymentBuilds: [{ name: "name", status: 20 }],
            deploymentStatuses: [
                {
                    id: "id",
                    deploymentId: "deploymentId",
                    status: "INITIALIZED",
                    state: { key: "value" },
                    transition: "BUILDING",
                    message: "message",
                    retryCount: 1.1,
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
            currentStatusId: "currentStatusId",
            currentStatus: {
                id: "id",
                deploymentId: "deploymentId",
                status: "INITIALIZED",
                state: { key: "value" },
                transition: "BUILDING",
                message: "message",
                retryCount: 1.1,
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
            appliedRecommendations: [
                {
                    id: "id",
                    clusterId: "clusterId",
                    applicationId: "applicationId",
                    deploymentId: "deploymentId",
                    applicationVersion: 1,
                    recommendationData: { key: "value" },
                    recommendationType: "recommendationType",
                    appliedDeploymentId: "appliedDeploymentId",
                    expiryTimestamp: "2024-01-15T09:30:00Z",
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
            createdBy: "createdBy",
        };
        server
            .mockEndpoint()
            .patch("/api/svc/v1/apps/id/scale-to-original")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.applications.scaleToOriginal("id");
        expect(response).toEqual({
            id: "id",
            version: 1.1,
            fqn: "fqn",
            applicationId: "applicationId",
            manifest: {
                name: "name",
                image: {
                    type: "build",
                    dockerRegistry: "docker_registry",
                    buildSource: {
                        type: "remote",
                        remoteUri: "remote_uri",
                    },
                    buildSpec: {
                        type: "dockerfile",
                        dockerfilePath: "dockerfile_path",
                        buildContextPath: "build_context_path",
                    },
                },
                artifactsDownload: {
                    cacheVolume: {
                        storageClass: "storage_class",
                        cacheSize: 1,
                    },
                    artifacts: [
                        {
                            type: "truefoundry-artifact",
                            artifactVersionFqn: "artifact_version_fqn",
                            downloadPathEnvVariable: "download_path_env_variable",
                        },
                    ],
                },
                resources: {
                    cpuRequest: 1.1,
                    cpuLimit: 1.1,
                    memoryRequest: 1,
                    memoryLimit: 1,
                    ephemeralStorageRequest: 1,
                    ephemeralStorageLimit: 1,
                    sharedMemorySize: 1,
                    node: {
                        type: "node_selector",
                    },
                    devices: [
                        {
                            type: "nvidia_gpu",
                            count: 1,
                        },
                    ],
                },
                env: {
                    key: "value",
                },
                ports: [
                    {
                        port: 1,
                        protocol: "TCP",
                        expose: true,
                    },
                ],
                serviceAccount: "service_account",
                mounts: [
                    {
                        type: "secret",
                        mountPath: "mount_path",
                        secretFqn: "secret_fqn",
                    },
                ],
                labels: {
                    key: "value",
                },
                kustomize: {
                    patch: {
                        key: "value",
                    },
                    additions: [
                        {
                            key: "value",
                        },
                    ],
                },
                livenessProbe: {
                    config: {
                        type: "http",
                        path: "path",
                        port: 1,
                    },
                    initialDelaySeconds: 1,
                    periodSeconds: 1,
                    timeoutSeconds: 1,
                    successThreshold: 1,
                    failureThreshold: 1,
                },
                readinessProbe: {
                    config: {
                        type: "http",
                        path: "path",
                        port: 1,
                    },
                    initialDelaySeconds: 1,
                    periodSeconds: 1,
                    timeoutSeconds: 1,
                    successThreshold: 1,
                    failureThreshold: 1,
                },
                workspaceFqn: "workspace_fqn",
                type: "service",
                replicas: 1.1,
                autoShutdown: {
                    waitTime: 1,
                },
                allowInterception: true,
                rolloutStrategy: {
                    type: "rolling_update",
                    maxUnavailablePercentage: 1,
                    maxSurgePercentage: 1,
                },
            },
            application: {
                id: "id",
                fqn: "fqn",
                name: "name",
                type: "async-service",
                createdBySubject: {
                    subjectId: "subjectId",
                    subjectType: "user",
                    subjectSlug: "subjectSlug",
                    subjectDisplayName: "subjectDisplayName",
                },
                tenantName: "tenantName",
                metadata: {
                    paused: true,
                },
                lifecycleStage: "active",
                workspaceId: "workspaceId",
                lastVersion: 1,
                activeVersion: 1,
                createdAt: new Date("2024-01-15T09:30:00.000Z"),
                updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                recommendations: [
                    {
                        recommendationData: {
                            key: "value",
                        },
                        recommendationType: "recommendationType",
                        expiryTimestamp: new Date("2024-01-15T09:30:00.000Z"),
                    },
                ],
                alerts: [
                    {
                        name: "name",
                        timestamps: [new Date("2024-01-15T09:30:00.000Z")],
                        startTime: new Date("2024-01-15T09:30:00.000Z"),
                        clusterId: "clusterId",
                        fingerprint: "fingerprint",
                    },
                ],
                alertsSummary: {
                    key: "value",
                },
                applicationDebugInfos: [
                    {
                        applicationId: "applicationId",
                        debugInfo: {
                            key: "value",
                        },
                    },
                ],
                potentialProblems: [
                    {
                        name: "name",
                        description: "description",
                    },
                ],
                autopilot: {
                    key: "value",
                },
                workspaceFqn: "workspaceFqn",
                createdBy: "createdBy",
                activeDeploymentId: "activeDeploymentId",
                lastDeploymentId: "lastDeploymentId",
            },
            createdBySubject: {
                subjectId: "subjectId",
                subjectType: "user",
                subjectSlug: "subjectSlug",
                subjectDisplayName: "subjectDisplayName",
            },
            createdAt: new Date("2024-01-15T09:30:00.000Z"),
            updatedAt: new Date("2024-01-15T09:30:00.000Z"),
            deploymentBuilds: [
                {
                    name: "name",
                    status: 20,
                },
            ],
            deploymentStatuses: [
                {
                    id: "id",
                    deploymentId: "deploymentId",
                    status: "INITIALIZED",
                    state: {
                        key: "value",
                    },
                    transition: "BUILDING",
                    message: "message",
                    retryCount: 1.1,
                    createdAt: new Date("2024-01-15T09:30:00.000Z"),
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                },
            ],
            currentStatusId: "currentStatusId",
            currentStatus: {
                id: "id",
                deploymentId: "deploymentId",
                status: "INITIALIZED",
                state: {
                    key: "value",
                },
                transition: "BUILDING",
                message: "message",
                retryCount: 1.1,
                createdAt: new Date("2024-01-15T09:30:00.000Z"),
                updatedAt: new Date("2024-01-15T09:30:00.000Z"),
            },
            appliedRecommendations: [
                {
                    id: "id",
                    clusterId: "clusterId",
                    applicationId: "applicationId",
                    deploymentId: "deploymentId",
                    applicationVersion: 1,
                    recommendationData: {
                        key: "value",
                    },
                    recommendationType: "recommendationType",
                    appliedDeploymentId: "appliedDeploymentId",
                    expiryTimestamp: new Date("2024-01-15T09:30:00.000Z"),
                    createdAt: new Date("2024-01-15T09:30:00.000Z"),
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                },
            ],
            createdBy: "createdBy",
        });
    });

    test("cancel_deployment", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .post("/api/svc/v1/apps/id/deployments/deploymentId/cancel")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.applications.cancelDeployment("id", "deploymentId");
        expect(response).toEqual({
            message: "message",
        });
    });
});
