/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { TrueFoundryClient } from "../../src/Client";

describe("Internal", () => {
    test("get_id_from_fqn", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/api/svc/v1/fqn/type")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.internal.getIdFromFqn("type", {
            fqn: "fqn",
        });
        expect(response).toEqual({
            key: "value",
        });
    });
});
