// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         email: "email",
 *         roles: ["roles"]
 *     }
 */
export interface UpdateUserRolesRequest {
    /** Email of the user */
    email: string;
    /** Roles for the user */
    roles: string[];
}
