// This file was auto-generated by Fern from our API Definition.

export const MetricsGetChartsRequestFilterEntity = {
    Application: "application",
    Pod: "pod",
    JobRun: "job-run",
    Event: "event",
    Cluster: "cluster",
} as const;
export type MetricsGetChartsRequestFilterEntity =
    (typeof MetricsGetChartsRequestFilterEntity)[keyof typeof MetricsGetChartsRequestFilterEntity];
