// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundry from "../../../../index.js";

/**
 * @example
 *     {
 *         manifest: {
 *             name: "name",
 *             metadata: {
 *                 "key": "value"
 *             },
 *             ml_repo: "ml_repo",
 *             type: "agent_skill",
 *             source: {
 *                 type: "inline",
 *                 skill_md: "skill_md"
 *             }
 *         }
 *     }
 */
export interface ApplyAgentSkillRequest {
    /** Manifest containing metadata for the agent skill to apply */
    manifest: TrueFoundry.AgentSkillManifest;
}
