/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../../../core";
import * as TrueFoundry from "../../../../../index";
import urlJoin from "url-join";
import * as errors from "../../../../../../errors/index";

export declare namespace ModelVersions {
    export interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<core.BearerToken | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class ModelVersions {
    constructor(protected readonly _options: ModelVersions.Options) {}

    /**
     * Get model version API
     *
     * @param {string} id
     * @param {ModelVersions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundry.UnprocessableEntityError}
     *
     * @example
     *     await client.v1.modelVersions.get("id")
     */
    public async get(
        id: string,
        requestOptions?: ModelVersions.RequestOptions,
    ): Promise<TrueFoundry.GetModelVersionResponse> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api/ml/v1/model-versions/${encodeURIComponent(id)}`,
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "truefoundry-sdk",
                "X-Fern-SDK-Version": "0.0.2",
                "User-Agent": "truefoundry-sdk/0.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return _response.body as TrueFoundry.GetModelVersionResponse;
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new TrueFoundry.UnprocessableEntityError(
                        _response.error.body as TrueFoundry.HttpValidationError,
                    );
                default:
                    throw new errors.TrueFoundryError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TrueFoundryError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.TrueFoundryTimeoutError(
                    "Timeout exceeded when calling GET /api/ml/v1/model-versions/{id}.",
                );
            case "unknown":
                throw new errors.TrueFoundryError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Delete model versions API
     *
     * @param {string} id
     * @param {ModelVersions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundry.UnprocessableEntityError}
     *
     * @example
     *     await client.v1.modelVersions.delete("id")
     */
    public async delete(id: string, requestOptions?: ModelVersions.RequestOptions): Promise<TrueFoundry.EmptyResponse> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api/ml/v1/model-versions/${encodeURIComponent(id)}`,
            ),
            method: "DELETE",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "truefoundry-sdk",
                "X-Fern-SDK-Version": "0.0.2",
                "User-Agent": "truefoundry-sdk/0.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return _response.body as TrueFoundry.EmptyResponse;
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new TrueFoundry.UnprocessableEntityError(
                        _response.error.body as TrueFoundry.HttpValidationError,
                    );
                default:
                    throw new errors.TrueFoundryError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TrueFoundryError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.TrueFoundryTimeoutError(
                    "Timeout exceeded when calling DELETE /api/ml/v1/model-versions/{id}.",
                );
            case "unknown":
                throw new errors.TrueFoundryError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * List model version API
     *
     * @param {TrueFoundry.v1.ModelVersionsListRequest} request
     * @param {ModelVersions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundry.UnprocessableEntityError}
     *
     * @example
     *     await client.v1.modelVersions.list()
     */
    public async list(
        request: TrueFoundry.v1.ModelVersionsListRequest = {},
        requestOptions?: ModelVersions.RequestOptions,
    ): Promise<core.Page<TrueFoundry.ModelVersion>> {
        const list = async (
            request: TrueFoundry.v1.ModelVersionsListRequest,
        ): Promise<TrueFoundry.ListModelVersionsResponse> => {
            const {
                model_id: modelId,
                fqn,
                offset,
                limit,
                run_ids: runIds,
                run_steps: runSteps,
                include_internal_metadata: includeInternalMetadata,
                include_model_versions: includeModelVersions,
            } = request;
            const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
            if (modelId != null) {
                _queryParams["model_id"] = modelId;
            }
            if (fqn != null) {
                _queryParams["fqn"] = fqn;
            }
            if (offset != null) {
                _queryParams["offset"] = offset.toString();
            }
            if (limit != null) {
                _queryParams["limit"] = limit.toString();
            }
            if (runIds != null) {
                if (Array.isArray(runIds)) {
                    _queryParams["run_ids"] = runIds.map((item) => item);
                } else {
                    _queryParams["run_ids"] = runIds;
                }
            }
            if (runSteps != null) {
                if (Array.isArray(runSteps)) {
                    _queryParams["run_steps"] = runSteps.map((item) => item.toString());
                } else {
                    _queryParams["run_steps"] = runSteps.toString();
                }
            }
            if (includeInternalMetadata != null) {
                _queryParams["include_internal_metadata"] = includeInternalMetadata.toString();
            }
            if (includeModelVersions != null) {
                _queryParams["include_model_versions"] = includeModelVersions.toString();
            }
            const _response = await (this._options.fetcher ?? core.fetcher)({
                url: urlJoin(
                    (await core.Supplier.get(this._options.baseUrl)) ??
                        (await core.Supplier.get(this._options.environment)),
                    "api/ml/v1/model-versions",
                ),
                method: "GET",
                headers: {
                    Authorization: await this._getAuthorizationHeader(),
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "truefoundry-sdk",
                    "X-Fern-SDK-Version": "0.0.2",
                    "User-Agent": "truefoundry-sdk/0.0.2",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                    ...requestOptions?.headers,
                },
                contentType: "application/json",
                queryParameters: _queryParams,
                requestType: "json",
                timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions?.maxRetries,
                abortSignal: requestOptions?.abortSignal,
            });
            if (_response.ok) {
                return _response.body as TrueFoundry.ListModelVersionsResponse;
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 422:
                        throw new TrueFoundry.UnprocessableEntityError(
                            _response.error.body as TrueFoundry.HttpValidationError,
                        );
                    default:
                        throw new errors.TrueFoundryError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.TrueFoundryError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                    });
                case "timeout":
                    throw new errors.TrueFoundryTimeoutError(
                        "Timeout exceeded when calling GET /api/ml/v1/model-versions.",
                    );
                case "unknown":
                    throw new errors.TrueFoundryError({
                        message: _response.error.errorMessage,
                    });
            }
        };
        let _offset = request?.offset != null ? request?.offset : 1;
        return new core.Pageable<TrueFoundry.ListModelVersionsResponse, TrueFoundry.ModelVersion>({
            response: await list(request),
            hasNextPage: (response) => (response?.data ?? []).length > 0,
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                _offset += response?.data != null ? response.data.length : 1;
                return list(core.setObjectProperty(request, "offset", _offset));
            },
        });
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = (await core.Supplier.get(this._options.apiKey)) ?? process?.env["TFY_API_KEY"];
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
