/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface AgentVersionsListRequest {
    fqn?: string;
    agent_id?: string;
    ml_repo_id?: string;
    name?: string;
    offset?: number;
    limit?: number;
}
