// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundry from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import * as serializers from "../../../../index.js";

export const SetTagRequest: core.serialization.Schema<serializers.SetTagRequest.Raw, TrueFoundry.SetTagRequest> = core.serialization.object({
        "key": core.serialization.string(),
        "value": core.serialization.string()
    });

export declare namespace SetTagRequest {
    export interface Raw {
        key: string;
        value: string;
    }
}
