/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ClustersListRequest {
    /**
     * Number of Items Skipped. Defaults to 0 if not provided.
     */
    offset?: number;
    /**
     * The maximum number of items to return per page. Defaults to a pre-defined value if not provided.
     */
    limit?: number;
}
